Repository hmcts/cmc-citizen-frontend, pull requests merged in 2018-11, with the labels that each got.

#1095 Rename a wrongly named variable
  src/main/features/claimant-response/routes/payment-date.ts
Labels: ns:cmc-citizen-frontend-pr-1095

#1084 ROC- 4620 - allow negative disposable income
  src/main/app/common/court-calculations/courtDecision.ts
  src/main/common/helpers/paymentPlanHelper.ts
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/test/app/common/court-calculations/courtDecision.ts
Labels: ns:cmc-citizen-frontend-pr-1084

#1094 ROC-4318-ImmediatePayment-PR2
  src/main/features/claimant-response/routes/payment-option.ts
Labels: ns:cmc-citizen-frontend-pr-1094

#1086 Fix functional tests on master
  src/integration-test/helpers/claimStoreHelper.ts
  src/integration-test/helpers/clients/claimStoreClient.ts
  src/integration-test/tests/citizen/defence/defence_handoff_test.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  types/steps-override.d.ts
Labels: ns:cmc-citizen-frontend-pr-1086

#1102 Change importer job to cronjob every 5mins
  src/kubernetes/deployment.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1102

#1056 ROC-4403 full admission by set date
  src/integration-test/tests/citizen/claimantResponse/data/ClaimantResponseTestData.ts
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-accept-payment-method.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-ccj-paid-amount-summary.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-ccj-paid-any-money.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-check-and-send.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-confirmation.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-counter-offer-accepted.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-court-offered-set-date.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-pay-by-set-date-accepted.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-payment-date.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-payment-option.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-payment-plan.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-rejection-reason.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-sign-settlement-agreement.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-task-list.ts
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-response.ts
  src/integration-test/tests/citizen/claimantResponse/steps/defendant.ts
  src/integration-test/tests/citizen/defence/data/DefenceTest.ts
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/defence/full_admission_test.ts
  src/integration-test/tests/citizen/defence/pages/defendant-more-time-request.ts
  src/integration-test/tests/citizen/defence/pages/defendant-why-do-you-disagree.ts
  src/integration-test/tests/citizen/defence/pages/defendant-you-have-paid-less.ts
  src/integration-test/tests/citizen/defence/pages/statement-of-means/monthlyExpenses.ts
  src/integration-test/tests/citizen/defence/pages/statement-of-means/monthlyIncome.ts
  src/integration-test/tests/citizen/defence/part_admission_test.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/integration-test/tests/citizen/endToEnd/data/EndToEndTestData.ts
  src/integration-test/tests/citizen/endToEnd/endToend_test.ts
  src/integration-test/tests/citizen/endToEnd/steps/helper.ts
  src/integration-test/tests/citizen/home/pages/login.ts
  types/integration-test-model.d.ts
Labels: ns:cmc-citizen-frontend-pr-1056

#1058 ROC-4599 Free Mediation on States Fully Paid Defendant Response
  src/main/app/claims/responseModelConverter.ts
  src/test/data/entity/responseData.ts
Labels: ns:cmc-citizen-frontend-pr-1058

#1110 Save disposable income in draft
  src/main/common/helpers/CourtDecisionHelper.ts
  src/main/common/helpers/paymentPlanHelper.ts
  src/main/features/claimant-response/helpers/settlementHelper.ts
  src/main/features/claimant-response/routes/counter-offer-accepted.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-option.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/test/common/helpers/courtDecisionHelper.ts
  src/test/common/helpers/paymentIntentionHelper.ts
  src/test/common/helpers/paymentPlanHelper.ts
  src/test/features/claimant-response/helpers/settlementHelper.ts
  src/test/features/claimant-response/routes/counter-offer-accepted.ts
  src/test/features/claimant-response/routes/payment-date.ts
  src/test/features/claimant-response/routes/payment-option.ts
  src/test/features/claimant-response/routes/payment-plan.ts
Labels: ns:cmc-citizen-frontend-pr-1110

#1062 ROC-4095 Make bank details optional
  src/main/app/claims/models/response/statement-of-means/statementOfMeans.ts
  src/main/app/common/statement-of-means/statementOfMeansCalculations.ts
  src/main/features/response/form/models/statement-of-means/bankAccounts.ts
  src/main/features/response/views/statement-of-means/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1062

#1119 ROC-4571 Update Settlement agreement with total claim amount
  src/main/features/claimant-response/helpers/settlementHelper.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/macro/termsOfAgreementTable.njk
  src/test/features/claimant-response/helpers/settlementHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1119

#1122 Update dependencies that sonar is stuck on
  package.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1122

#1073 Update email addresses so automated tests are better identified
  src/integration-test/data/test-data.ts
  src/integration-test/helpers/idamHelper.ts
  src/integration-test/tests/citizen/claim/steps/payment.ts
Labels: ns:cmc-citizen-frontend-pr-1073

#1097 ROC-4566:CourtDetermination-PR2
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/claims/models/response/core/paymentIntention.ts
  src/main/common/components/payment-intention/model/paymentIntention.ts
  src/main/common/helpers/paymentPlanHelper.ts
  src/main/features/claimant-response/draft/courtDetermination.ts
  src/main/features/claimant-response/draft/draftClaimantResponse.ts
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/routes/counter-offer-accepted.ts
  src/main/features/claimant-response/routes/court-offer.ts
  src/main/features/claimant-response/routes/court-offered-set-date.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-option.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/main/features/claimant-response/routes/rejection-reason.ts
  src/main/features/claimant-response/routes/sign-settlement-agreement.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/app/claims/models/paymentIntention.ts
  src/test/common/components/payment-intention/model/paymentIntention.ts
  src/test/common/helpers/courtDecisionHelper.ts
  src/test/common/helpers/paymentIntentionHelper.ts
  src/test/common/helpers/paymentPlanHelper.ts
  src/test/data/draft/paymentIntentionDraft.ts
  src/test/features/claimant-response/draft/courtDetermination.ts
  src/test/features/claimant-response/draft/draftClaimantResponse.ts
  src/test/features/claimant-response/routes/counter-offer-accepted.ts
  src/test/features/claimant-response/routes/court-offered-set-date.ts
  src/test/features/claimant-response/routes/payment-date.ts
  src/test/features/claimant-response/routes/payment-option.ts
  src/test/features/claimant-response/routes/payment-plan.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1097

#1120 ROC-4642 fixed wording for 'Frequency of payments'
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/counter-offer-accepted.njk
  src/main/features/claimant-response/views/macro/paymentPlanTable.njk
  src/main/features/claimant-response/views/macro/termsOfAgreementTable.njk
  src/main/features/dashboard/index.ts
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmitted.njk
  src/main/views/macro/paymentPlanTable.njk
Labels: ns:cmc-citizen-frontend-pr-1120

#1041 ROC-4315 Update content for court calculated plan
  src/main/features/claimant-response/views/court-offer.njk
  src/main/features/claimant-response/views/court-offered-set-date.njk
Labels: ns:cmc-citizen-frontend-pr-1041

#1130 ROC-4301 Add paid in full to demo and preview
  infrastructure/demo.tfvars
  infrastructure/preview.tfvars
Labels: ns:cmc-citizen-frontend-pr-1130

#1127 ROC-4399 Extend data model with claimant response
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimant-response/acceptationClaimantResponse.ts
  src/main/app/claims/models/claimant-response/claimantResponseCommon.ts
  src/main/app/claims/models/claimant-response/claimantResponseType.ts
  src/main/app/claims/models/claimant-response/court-determination/courtDetermination.ts
  src/main/app/claims/models/claimant-response/court-determination/decisionType.ts
  src/main/app/claims/models/claimant-response/formaliseOption.ts
  src/main/app/claims/models/claimant-response/rejectionClaimantResponse.ts
  src/main/app/claims/models/claimantResponse.ts
  src/test/app/claims/models/claimant-response/acceptationClaimantResponse.ts
  src/test/app/claims/models/claimant-response/court-determination/courtDetermination.ts
  src/test/app/claims/models/claimant-response/rejectionClaimantResponse.ts
  src/test/app/claims/models/claimantResponse.ts
  src/test/app/claims/models/response/core/paymentIntention.ts
  src/test/data/entity/claimantResponseData.ts
  src/test/data/entity/courtDeterminationData.ts
  src/test/data/entity/paymentIntentionData.ts
  src/test/data/entity/repaymentPlanData.ts
  src/test/rawObjectUtils.ts
Labels: ns:cmc-citizen-frontend-pr-1127

#1128 ROC-4566:Reset court determination when user goes back in journey from task list
  src/main/features/claimant-response/routes/accept-payment-method.ts
Labels: ns:cmc-citizen-frontend-pr-1128

#1133 sidam dry-run
  infrastructure/aat.tfvars
  infrastructure/prod.tfvars
Labels: ns:cmc-citizen-frontend-pr-1133

#1131 ROC-4700:Get defendant paymentPlan only when defendant chooses instalment
  src/main/common/helpers/CourtDecisionHelper.ts
  src/main/common/helpers/paymentPlanHelper.ts
  src/test/common/helpers/courtDecisionHelper.ts
  src/test/data/entity/responseData.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1131

#1135 ROC-4682 Login issues on production
  src/main/app/logging/customEventTracker.ts
  src/main/routes/receiver.ts
Labels: ns:cmc-citizen-frontend-pr-1135

#1132 Remove redundant code for settlement endpoint
  src/main/app/claims/offerClient.ts
Labels: ns:cmc-citizen-frontend-pr-1132

#1112 ROC-4448: Update court calculation to use claimant's first start date
  src/main/app/common/payment-plan/paymentPlan.ts
  src/main/features/claimant-response/routes/payment-plan.ts
Labels: ns:cmc-citizen-frontend-pr-1112

#1129 ROC-4687: fixing check-and-send page bug
  src/main/features/claimant-response/routes/check-and-send.ts
  src/test/features/claimant-response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1129

#1136 ROC-4536 Update allowances for court calculations
  src/main/resources/meansAllowance.json
Labels: ns:cmc-citizen-frontend-pr-1136

#1138 ROC-4690 Add Unit Tests for Different Claimant Response
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/data/draft/claimantPaymentIntentionDraft.ts
Labels: ns:cmc-citizen-frontend-pr-1138

#1137 ROC-4632: Refer to judge
  src/main/features/claimant-response/form/models/formaliseRepaymentPlanOption.ts
  src/main/features/claimant-response/routes/rejection-reason.ts
  src/test/features/claimant-response/form/models/formaliseRepaymentPlanOption.ts
Labels: ns:cmc-citizen-frontend-pr-1137

#1082 ROC-4399 Dashboards
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjEligible.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmissionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmitted.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/moreTimeRequested.njk
  src/main/features/dashboard/views/macro/claimStatus/noReponse.njk
  src/main/features/dashboard/views/macro/claimStatus/offerAccepted.njk
  src/main/features/dashboard/views/macro/claimStatus/offerRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/offerSettlement.njk
  src/main/features/dashboard/views/macro/claimStatus/offerSubmitted.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
  src/main/modules/nunjucks/index.ts
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1082

#1109 ROC-4679 Enable admissions e2e - depending on feature toggle
  Jenkinsfile_CNP
  docker-compose.functional-tests.yml
  src/integration-test/README.md
  src/integration-test/helpers/claimStoreHelper.ts
  src/integration-test/helpers/clients/appClient.ts
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/integration-test/tests/citizen/claimantResponse/steps/defendant.ts
  src/integration-test/tests/citizen/defence/defence_handoff_test.ts
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/defence/full_admission_test.ts
  src/integration-test/tests/citizen/defence/part_admission_test.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/integration-test/tests/citizen/endToEnd/data/EndToEndTestData.ts
  types/steps-override.d.ts
Labels: ns:cmc-citizen-frontend-pr-1109

#1143 ROC-4308: Re-determination by defendant
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimant-response/reDetermination.ts
  src/main/features/ccj/paths.ts
  src/main/features/ccj/routes/confirmation.ts
  src/main/features/ccj/routes/redetermination.ts
  src/main/features/ccj/routes/repayment-plan-summary.ts
  src/main/features/ccj/views/confirmation.njk
  src/main/features/ccj/views/redetermination.njk
  src/main/features/ccj/views/repayment-plan-summary.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
  src/main/modules/nunjucks/index.ts
  src/test/a11y/a11y.ts
  src/test/features/ccj/routes/ccjGuard.ts
  src/test/features/ccj/routes/confirmation.ts
  src/test/features/ccj/routes/reDetermination.ts
  src/test/features/ccj/routes/repayment-plan-summary.ts
Labels: ns:cmc-citizen-frontend-pr-1143

#1149 ROC-4679 Enable admissions e2e - depending on feature toggle (change approach back to env vars)
  Jenkinsfile_CNP
  docker-compose.functional-tests.yml
  docker-compose.smoke-tests.yml
  infrastructure/output.tf
  src/integration-test/README.md
  src/integration-test/bootstrap/bootstrap.ts
  src/integration-test/helpers/clients/appClient.ts
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/defence/full_admission_test.ts
  src/integration-test/tests/citizen/defence/part_admission_test.ts
Labels: ns:cmc-citizen-frontend-pr-1149

#1146 ROC-4609 defendant repayment plan page shows wrong amount for part admission
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/common/components/payment-intention/payment-plan.ts
Labels: ns:cmc-citizen-frontend-pr-1146

#849 ROC-3809: Claimant response to states paid defence
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/claims/models/claimant-response/responseAcceptation.ts
  src/main/app/claims/models/claimant-response/responseRejection.ts
  src/main/features/claimant-response/draft/draftClaimantResponse.ts
  src/main/features/claimant-response/form/models/states-paid/claimSettled.ts
  src/main/features/claimant-response/form/models/states-paid/partPaymentReceived.ts
  src/main/features/claimant-response/guards/claimantResponseGuard.ts
  src/main/features/claimant-response/helpers/statesPaidHelper.ts
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/claimant-response/index.ts
  src/main/features/claimant-response/paths.ts
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/routes/confirmation.ts
  src/main/features/claimant-response/routes/defendants-response.ts
  src/main/features/claimant-response/routes/part-payment-received.ts
  src/main/features/claimant-response/routes/rejection-reason.ts
  src/main/features/claimant-response/routes/settle-claim.ts
  src/main/features/claimant-response/tasks/states-paid/claimSettledTask.ts
  src/main/features/claimant-response/tasks/states-paid/partPaymentReceivedTask.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/claimant-response/views/part-payment-received.njk
  src/main/features/claimant-response/views/rejection-reason.njk
  src/main/features/claimant-response/views/settle-claim.njk
  src/main/features/dashboard/routes/directions-questionnaire.ts
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/response/guards/responseGuard.ts
  src/main/modules/nunjucks/filters/yesNoFilter.ts
  src/main/modules/nunjucks/index.ts
  src/test/a11y/mocks.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/data/entity/responseData.ts
  src/test/features/claimant-response/draft/draftClaimantResponse.ts
  src/test/features/claimant-response/form/models/claimSettled.ts
  src/test/features/claimant-response/form/models/partPaymentAccepted.ts
  src/test/features/claimant-response/guards/claimantResponseGuard.ts
  src/test/features/claimant-response/helpers/statesPaidHelper.ts
  src/test/features/claimant-response/helpers/taskListBuilder.ts
  src/test/features/claimant-response/routes/part-payment-received.ts
  src/test/features/claimant-response/routes/settle-claim.ts
  src/test/features/claimant-response/tasks/claimSettledTask.ts
  src/test/features/claimant-response/tasks/partPaymentReceivedTask.ts
  src/test/features/dashboard/routes/directions-questionnaire.ts
  src/test/modules/nunjucks/filters/yesNoFilter.ts
Labels: merged to demo, ns:cmc-citizen-frontend-pr-849

#913 ROC-4265 Alternate payment plan start date
  src/main/app/common/calculate-month-increment/calculateMonthIncrement.ts
  src/main/common/components/payment-intention/payment-plan.njk
  src/main/common/components/payment-intention/payment-plan.ts
  src/main/features/ccj/routes/repayment-plan.ts
  src/main/features/ccj/views/repayment-plan.njk
  src/main/features/claimant-response/helpers/paydateHelper.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/main/modules/nunjucks/filters/dateFilter.ts
  src/main/modules/nunjucks/index.ts
  src/test/app/common/calculate-month-increment/calculate-month-increment.ts
  src/test/data/entity/responseData.ts
  src/test/features/claimant-response/helpers/paydateHelper.ts
  src/test/modules/nunjucks/filters/dateFilter.ts
Labels: ns:cmc-citizen-frontend-pr-913

#1155 ROC 4682 login issues on production
  src/main/app/idam/idamClient.ts
  src/main/routes/receiver.ts
Labels: ns:cmc-citizen-frontend-pr-1155

#1156 Update @types/node
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1156

#1150 Added line about timeline to defendant journey
  src/main/features/response/views/your-defence.njk
Labels: ns:cmc-citizen-frontend-pr-1150

#1158 Update Sinon Chai
  package.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1158

#1064 Add codecov config file
  codecov.yml
  package.json
Labels: ns:cmc-citizen-frontend-pr-1064

#1144 ROC-4567: dashboard status after claimant rejection
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/app/claims/models/claimantResponse.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimantResponse.njk
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1144

#1153 ROC-4724: Handle negative disposable income to create payment intention of max future date
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/common/court-calculations/courtDecision.ts
  src/main/app/common/court-calculations/courtOrder.ts
  src/main/common/helpers/paymentPlanHelper.ts
  src/main/common/momentFactory.ts
  src/main/features/claimant-response/routes/payment-option.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/app/common/court-calculations/courtDecision.ts
  src/test/app/common/court-calculations/courtOrder.ts
Labels: ns:cmc-citizen-frontend-pr-1153

#1160 Bugfix: To fix dashboard error on claimant response
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
Labels: ns:cmc-citizen-frontend-pr-1160

#1163 ROC-4634 CCJ confirmation page content
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/main/features/claimant-response/views/confirmation.njk
Labels: ns:cmc-citizen-frontend-pr-1163

#1164 ROC-4639: use correct decimal places for income expense calculation
  src/main/public/js/income-expense-calculation.js
  src/main/views/income-expense-scripts.njk
Labels: ns:cmc-citizen-frontend-pr-1164

#1161 ROC-4399 Dashboards for CCJ by determination
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/ccj/routes/repayment-plan-summary.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
  src/main/views/macro/internalLink.njk
  src/test/app/claims/models/claim.ts
  src/test/data/entity/claimantResponseData.ts
Labels: ns:cmc-citizen-frontend-pr-1161

#1168 ROC-4779: Show payment plan for all payment option in repayment plan summary
  src/main/app/claims/models/claim.ts
  src/main/features/ccj/routes/redetermination.ts
  src/main/features/ccj/routes/repayment-plan-summary.ts
  src/main/features/ccj/views/redetermination.njk
  src/main/features/ccj/views/repayment-plan-summary.njk
  src/test/a11y/mocks.ts
  src/test/features/ccj/routes/ccjGuard.ts
  src/test/features/ccj/routes/reDetermination.ts
  src/test/features/ccj/routes/repayment-plan-summary.ts
Labels: ns:cmc-citizen-frontend-pr-1168

#1174 Disable cache in demo and prod
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:cmc-citizen-frontend-pr-1174

#1170 ROC-4399 Refer to judge dashboard statuses
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedDefendant.njk
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1170

#1169 ROC-4646 Disallow court instalment plans of less than £1 per week
  src/main/common/helpers/paymentPlanHelper.ts
  src/test/common/helpers/paymentPlanHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1169

#1175 ROC-4399 reject part admit dashboards
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1175

#1179 iOS12 cookie bug
  src/main/app/idam/authorizationMiddleware.ts
  src/main/app/idam/oAuthHelper.ts
  src/main/features/eligibility/store.ts
  src/main/features/first-contact/routes/claim-summary.ts
  src/main/modules/csrf/index.ts
  src/main/routes/logout.ts
  src/main/routes/receiver.ts
  src/test/routes/expectations.ts
Labels: ns:cmc-citizen-frontend-pr-1179

#1177 ROC-4399 - remove £ sign
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1177

#1188 changes to stop 500 errors
  src/main/routes/receiver.ts
Labels: ns:cmc-citizen-frontend-pr-1188

#1191 ROC-4805 Directions questionnaire deadline after reject part admit
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1191

#1184 ROC-4718 claimant response repayment plan accepted - content change for more clarity
  src/main/features/claimant-response/routes/payment-plan.ts
  src/main/features/claimant-response/views/counter-offer-accepted.njk
  src/main/features/claimant-response/views/payment-plan.njk
  src/test/features/claimant-response/routes/counter-offer-accepted.ts
Labels: ns:cmc-citizen-frontend-pr-1184

#1189 ROC-4836 Display correct deadline for directions questionnaire after full defence
  src/main/features/dashboard/routes/directions-questionnaire.ts
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/features/dashboard/routes/directions-questionnaire.ts
Labels: ns:cmc-citizen-frontend-pr-1189

#1194 ROC-4322:Court-Determination-bug fix
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/test/common/helpers/paymentIntentionHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1194

#1199 CPRC content change
  src/main/features/claimant-response/views/confirmation/accepted-payment-plan.njk
Labels: ns:cmc-citizen-frontend-pr-1199

#1200 Use correct apostrophe
  src/main/features/claimant-response/views/confirmation/accepted-payment-plan.njk
Labels: ns:cmc-citizen-frontend-pr-1200

#1201 Update Types/Node
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1201
