Repository hmcts/cmc-citizen-frontend, pull requests merged in 2018-04, with the labels that each got.

#503 ROC-3483: Fix validation message for interest rate reason
  src/main/app/forms/validation/validationErrors.ts
  src/main/features/claim/form/models/interestRate.ts
  src/main/features/claim/form/models/interestStartDate.ts
  src/test/features/claim/form/models/interestRate.ts
  src/test/features/claim/form/models/interestStartDate.ts
Labels: pull-request: approved, tested locally

#504 ROC-3487: Remove internal start page
  src/integration-test/tests/citizen/claim/enterDetails_test.ts
  src/integration-test/tests/citizen/claim/pages/claimant-start-claim.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/integration-test/tests/citizen/claim/steps/eligibility.ts
  src/integration-test/tests/citizen/home/steps/user.ts
  src/main/features/claim/index.ts
  src/main/features/claim/paths.ts
  src/main/features/claim/routes/start.ts
  src/main/features/claim/views/start.njk
  src/main/features/dashboard/helpers/dashboardUrlHelper.ts
  src/main/features/dashboard/paths.ts
  src/main/features/dashboard/routes/claimant.ts
  src/main/features/dashboard/routes/index.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/defendant.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/routes/receiver.ts
  src/test/features/claim/routes/start.ts
  src/test/features/dashboard/helpers/dashboardUrlHelper.ts
  src/test/routes/receiver.ts
Labels: pull-request: approved, tested locally

#508 ROC-3458: no cache added
  src/main/modules/helmet/index.ts
Labels: pull-request: approved

#506 ROC-3482: For no daily interest selected, details of daily interest should not be listed
  src/main/features/ccj/views/paid-amount-summary.njk
  src/main/views/macro/amountBreakdown.njk
  src/main/views/macro/interestSnippet.njk
Labels: pull-request: approved, tested locally

#515 ROC-3511: Fix for download claim link
  src/main/features/dashboard/views/claimant.njk
Labels: tested locally

#501 ROC-3484 Fix template to show evidence type listed even if no description
  src/main/features/response/views/evidence.njk
Labels: tested locally

#485 ROC-3407: Remove residual task list links after handoff pages
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/features/response/draft/responseDraft.ts
  src/main/features/response/helpers/taskListBuilder.ts
  src/main/features/response/tasks/oweMoneyTask.ts
  src/main/features/response/views/check-and-send.njk
  src/test/features/response/draft/responseDraft.ts
  src/test/features/response/helpers/taskListBuilder.ts
  src/test/features/response/tasks/oweMoneyTask.ts
Labels: pull-request: approved

#518 ROC-3511: Add undefined or null check in evaluateuri
  src/main/common/router/routablePath.ts
  src/test/common/router/routablePath.ts
Labels: pull-request: approved

#524 Replace sprintf
  src/main/features/ccj/views/confirmation.njk
  src/main/features/ccj/views/paid-amount.njk
  src/main/features/first-contact/views/claimant-has-requested-ccj.njk
  src/main/features/offer/views/settle-out-of-court.njk
  src/main/features/response/views/how-much-owed.njk
  src/main/features/response/views/how-much-paid.njk
  src/main/features/response/views/impact-of-dispute.njk
  src/main/features/response/views/statement-of-means/start.njk
  src/main/features/response/views/task-list.njk
  src/main/features/response/views/your-defence.njk
  src/main/views/govukTemplate.njk
  src/main/views/includes/phase_banner_beta.njk
  src/main/views/macro/statementOfTruth.njk
Labels: pull-request: approved, tested

#521 ROC-3480: Add robots.txt
  src/main/public/robots.txt
Labels: pull-request: approved

#527 ROC-2874: Create Claim Draft - Bug fix
  src/main/app/drafts/draft-data/claimDraft.ts
  src/main/features/testing-support/routes/create-claim-draft.ts
  src/test/features/testing-support/create-claim-draft.ts
Labels: tested

#479 ROC-3334 States paid status content changes
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/defendant.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/response/index.ts
  src/main/public/stylesheets/components/_dashboard.scss
  src/test/app/claims/models/claim.ts
Labels: pull-request: approved, tested locally

#525 Remove partial and full admission pages as they are not used
  src/main/features/response/index.ts
  src/main/features/response/paths.ts
  src/main/features/response/routes/check-and-send.ts
  src/main/features/response/routes/full-admission.ts
  src/main/features/response/routes/partial-admission.ts
  src/main/features/response/views/full-admission.njk
  src/main/features/response/views/partial-admission.njk
  src/test/features/response/routes/check-and-send.ts
  src/test/features/response/routes/full-admission.ts
  src/test/features/response/routes/partial-admission.ts
Labels: pull-request: approved, tested locally

#528 ROC-3502 Add contact us page
  src/main/app/paths.ts
  src/main/routes/contact-us.ts
  src/main/views/contact-us.njk
  src/main/views/includes/support-links.njk
  src/test/routes/contact-us.ts
Labels: pull-request: approved

#534 ROC-3379: Restore payment options selection in CCJ on page reload
  src/main/features/ccj/views/payment-options.njk
Labels: pull-request: approved, tested locally

#530 ROC-3379: Show amount already paid on CCJ check and send page
  src/integration-test/tests/citizen/ccj/pages/ccj-check-and-send.ts
  src/main/features/ccj/views/check-and-send.njk
Labels: pull-request: approved, tested locally

#522 ROC-3510: Submit shows in dashboard for all digitally supported scenarios
  src/main/features/response/draft/responseDraft.ts
  src/main/features/response/helpers/taskListBuilder.ts
  src/main/features/response/routes/task-list.ts
  src/test/features/response/draft/responseDraft.ts
  src/test/features/response/helpers/taskListBuilder.ts
Labels: pull-request: approved, tested locally

#543 ROC-3544: Require mobile number when defendant is an individual
  src/main/app/forms/models/companyDetails.ts
  src/main/app/forms/models/organisationDetails.ts
  src/main/features/response/tasks/yourDetails.ts
  src/test/app/forms/models/organisationDetails.ts
  src/test/features/response/tasks/yourDetails.ts
Labels: tested locally

#537 ROC-3489: Dashboard and status detail
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/endToEnd/endToend_test.ts
  src/integration-test/tests/citizen/endToEnd/steps/helper.ts
  src/integration-test/tests/citizen/offers/offers_test.ts
  src/integration-test/tests/citizen/offers/steps/offer.ts
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/helpers/dashboardUrlHelper.ts
  src/main/features/dashboard/routes/claimant.ts
  src/main/features/dashboard/routes/defendant.ts
  src/main/features/dashboard/routes/index.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/defendant.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjEligible.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/moreTimeRequested.njk
  src/main/features/dashboard/views/macro/claimStatus/noReponse.njk
  src/main/features/dashboard/views/macro/claimStatus/offerAccepted.njk
  src/main/features/dashboard/views/macro/claimStatus/offerRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/offerSettlement.njk
  src/main/features/dashboard/views/macro/claimStatus/offerSubmitted.njk
  src/main/features/response/routes/task-list.ts
  src/main/features/response/views/task-list.njk
  src/main/modules/nunjucks/index.ts
  src/test/app/claims/models/claim.ts
  src/test/features/dashboard/helpers/dashboardUrlHelper.ts
  src/test/features/dashboard/routes/claimant.ts
Labels: tested locally

#539 ROC-3329: Eligibility interstital mcol page
  package.json
  src/main/features/eligibility/paths.ts
  src/main/features/eligibility/routes/index.ts
  src/main/features/eligibility/routes/mcol-eligibility.ts
  src/main/features/eligibility/views/index.njk
  src/main/features/eligibility/views/mcol-eligibility.njk
  src/main/views/macro/externalLink.njk
  src/main/views/macro/support.njk
  src/test/features/eligibility/routes/mcol-eligibility.ts
  yarn.lock
Labels: tested, tested locally

#549 ROC-3632: Fix view claim link after CCJ requested
  src/main/features/response/index.ts
  src/test/features/response/routes/claim-details.ts
Labels: pull-request: approved, tested locally
