Repository hmcts/cmc-citizen-frontend, pull requests merged in 2018-10, with the labels that each got.

#1016 ROC-4029 Small content change
  src/main/features/claim/views/new-features-consent.njk
Labels: ns:cmc-citizen-frontend-pr-1016

#999 ROC-4451: Completion date and payment length
  src/main/app/claims/models/response/core/paymentIntention.ts
  src/main/app/claims/responseModelConverter.ts
  src/main/app/forms/models/localDate.ts
  src/main/common/components/payment-intention/model/paymentPlan.ts
  src/test/app/claims/models/repaymentPlan.ts
  src/test/app/claims/responseModelConverter.ts
  src/test/app/forms/models/localDate.ts
  src/test/common/components/payment-intention/model/paymentPlan.ts
  src/test/data/draft/responseDraft.ts
  src/test/data/entity/responseData.ts
Labels: ns:cmc-citizen-frontend-pr-999

#1007 ROC-4494 Store additional information dring court determination
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/claims/models/response/core/courtDetermination.ts
  src/main/app/claims/models/response/core/responseAcceptance.ts
  src/main/app/claims/models/response/core/responseRejection.ts
  src/main/app/common/court-calculations/courtDetermination.ts
  src/main/features/claimant-response/draft/draftClaimantResponse.ts
  src/main/features/claimant-response/routes/court-offered-set-date.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/app/common/court-calculations/courtDetermination.ts
Labels: ns:cmc-citizen-frontend-pr-1007

#1020 ROC-4451: Simplify completion date and payment length code
  src/main/features/claimant-response/routes/accept-payment-method.ts
  src/main/features/claimant-response/routes/defendants-response.ts
  src/main/features/claimant-response/views/accept-payment-method.njk
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/claimant-response/views/macro/repaymentPlanBlock.njk
Labels: ns:cmc-citizen-frontend-pr-1020

#1014 ROC-4403 - Add new pages and update task list ready for e2e for claimant respons…
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-accept-payment-method.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-choose-how-to-proceed.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-confirmation.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-sign-settlement-agreement.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-task-list.ts
Labels: ns:cmc-citizen-frontend-pr-1014

#1002 ROC-4415: part admit pay immediately
  package.json
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/features/claimant-response/views/counter-offer-accepted.njk
  src/main/features/claimant-response/views/court-offer.njk
  src/main/features/claimant-response/views/macro/paymentPlanTable.njk
  src/main/features/claimant-response/views/macro/repaymentPlanBlock.njk
  src/test/app/claims/converters/claimantResponseConverter.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1002

#1021 ROC-4494 Set default ccj to be of type DEFAULT'
  src/main/app/claims/ccjModelConverter.ts
  src/main/app/claims/models/countyCourtJudgment.ts
  src/test/app/claims/CCJModelConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1021

#1015 ROC-4470 additional AKS documentation
  README.md
  src/kubernetes/README.md
Labels: ns:cmc-citizen-frontend-pr-1015

#901 ROC-4306 Incorrect name showing on widget when claimant is also defendant
  src/main/features/claim/index.ts
  src/main/features/claim/paths.ts
  src/main/features/claim/routes/claimant-details.ts
  src/main/features/claim/views/claimant-details.njk
  src/main/features/claim/views/macro/about-claim-widget.njk
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/contact-them.njk
  src/main/features/dashboard/views/defendant.njk
Labels: ns:cmc-citizen-frontend-pr-901

#998 Changes to 'Briefly explain your claim'
  src/main/features/claim/views/reason.njk
Labels: ns:cmc-citizen-frontend-pr-998

#1022 ROC-4451:Simplified creating payment plan logic
  src/main/app/claims/models/response/core/paymentIntention.ts
  src/main/common/components/payment-intention/model/paymentIntention.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/main/features/claimant-response/views/counter-offer-accepted.njk
  src/main/features/claimant-response/views/court-offer.njk
  src/test/app/claims/models/response/core/paymentIntention.ts
  src/test/common/components/payment-intention/model/paymentIntention.ts
  src/test/data/draft/paymentIntentionDraft.ts
Labels: ns:cmc-citizen-frontend-pr-1022

#1026 ROC-4197: enable mocha-parallel plugin for travis tests
  .travis.yml
  package.json
Labels: ns:cmc-citizen-frontend-pr-1026

#1028 ROC-4539: Fix typo in contents
  src/main/common/components/free-mediation/free-mediation.njk
Labels: ns:cmc-citizen-frontend-pr-1028, tested

#996 Minor edits on five different pages
  src/main/features/claimant-response/views/confirmation/court-suggested-payment-plan.njk
  src/main/features/claimant-response/views/court-offer.njk
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/response/views/confirmation/full-admission.njk
  src/main/features/response/views/confirmation/part-admission.njk
Labels: ns:cmc-citizen-frontend-pr-996

#1036 stop sandbox aks deployments
  Jenkinsfile_pipeline_test
Labels: ns:cmc-citizen-frontend-pr-1036

#1030 Feature/add court determination to draft
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/common/court-calculations/courtDecision.ts
  src/main/common/components/payment-intention/model/paymentIntention.ts
  src/main/common/helpers/CourtDecisionHelper.ts
  src/main/features/claimant-response/draft/courtDecision.ts
  src/main/features/claimant-response/draft/courtDetermination.ts
  src/main/features/claimant-response/draft/draftClaimantResponse.ts
  src/main/features/claimant-response/routes/court-offered-set-date.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/main/features/response/draft/responseDraft.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/app/common/court-calculations/courtDecision.ts
  src/test/common/components/payment-intention/model/paymentIntention.ts
  src/test/features/claimant-response/draft/courtDetermination.ts
  src/test/features/claimant-response/draft/draftClaimantResponse.ts
  src/test/features/claimant-response/routes/court-offered-set-date.ts
Labels: ns:cmc-citizen-frontend-pr-1030

#1043 ROC-4055: Fix settlement offer table
  src/main/features/claimant-response/routes/sign-settlement-agreement.ts
  src/main/features/claimant-response/views/macro/termsOfAgreementTable.njk
  src/main/features/claimant-response/views/sign-settlement-agreement.njk
Labels: ns:cmc-citizen-frontend-pr-1043

#1042 ROC-4049:Content changed since story developed
  src/main/common/components/payment-intention/model/paymentOption.ts
Labels: ns:cmc-citizen-frontend-pr-1042

#1049 ROC-4593 bug fix for non-positive determination of means
  src/main/features/claimant-response/routes/payment-plan.ts
Labels: ns:cmc-citizen-frontend-pr-1049

#1050 ROC-4593 Fix claimant response pay by set date when no disposable income
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/features/claimant-response/routes/payment-date.ts
Labels: ns:cmc-citizen-frontend-pr-1050

#1051 ROC-4368 - Fixed review comments.
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1051

#1031 ROC 4295 added automated tests to 'payment plan length calculation'
  src/test/app/common/payment-plan/paymentPlan.ts
Labels: ns:cmc-citizen-frontend-pr-1031

#1035 ROC-4485
  src/main/features/claimant-response/views/choose-how-to-proceed.njk
Labels: ns:cmc-citizen-frontend-pr-1035

#1053 ROC-4593 Allow missing court's plan when decision is CLAIMANT_IN_FAVOUR_OF_DEFENDANT
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1053

#1060 ROC-4593 Treat no disposable income as out of scope
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/common/helpers/paymentPlanHelper.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1060

#1063 ROC-4396 correct name of dependant category
  src/main/resources/meansAllowance.json
  src/test/data/draft/responseDraft.ts
  src/test/data/entity/responseData.ts
Labels: ns:cmc-citizen-frontend-pr-1063

#1066 Changes to make prod match FTTB
  src/main/features/claimant-response/form/models/formaliseRepaymentPlanOption.ts
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/claimant-response/views/accept-payment-method.njk
  src/main/features/claimant-response/views/court-offer.njk
  src/test/features/claimant-response/helpers/taskListBuilder.ts
  src/test/features/claimant-response/routes/accept-payment-method.ts
Labels: ns:cmc-citizen-frontend-pr-1066

#1040 ROC-4310: Confirmation page and claim store api call for paid in full
  src/integration-test/tests/citizen/paidInFull/steps/paidInFull.ts
  src/main/app/claims/claimStoreClient.ts
  src/main/features/paid-in-full/paths.ts
  src/main/features/paid-in-full/routes/confirmation.ts
  src/main/features/paid-in-full/routes/date-paid.ts
  src/main/features/paid-in-full/views/confirmation.njk
  src/test/features/paid-in-full/routes/confirmation.ts
Labels: ns:cmc-citizen-frontend-pr-1040

#1025 ROC-4420: remove their finances totals section
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/claimant-response/views/payment-plan.njk
  src/main/views/macro/financialDetails.njk
  src/test/app/claims/models/details/theirs/theirDetails.ts
Labels: ns:cmc-citizen-frontend-pr-1025

#1069 ROC-4406 Correct priority debt categories' capitalisation to match prototype
  src/main/features/response/form/models/statement-of-means/priorityDebtType.ts
  src/main/features/response/views/statement-of-means/priority-debts.njk
Labels: ns:cmc-citizen-frontend-pr-1069

#1067 ROC-4569 / Users not able to download PDFs
  src/main/features/response/views/eligibility/send-your-response-by-email.njk
Labels: ns:cmc-citizen-frontend-pr-1067

#1065 ROC-4624 content changes
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-task-list.ts
  src/integration-test/tests/citizen/defence/pages/statement-of-means/start.ts
  src/main/common/components/ccj/paid-amount.njk
  src/main/common/components/payment-intention/payment-option.njk
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/views/macro/paymentPlanTable.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmitted.njk
  src/main/features/response/form/models/statement-of-means/monthlyIncomeType.ts
  src/main/features/response/routes/more-time-request.ts
  src/main/features/response/views/check-and-send.njk
  src/main/features/response/views/confirmation/full-admission.njk
  src/main/features/response/views/confirmation/part-admission.njk
  src/main/features/response/views/more-time-request.njk
  src/main/features/response/views/statement-of-means/check-and-send.njk
  src/main/features/response/views/statement-of-means/intro.njk
  src/main/features/response/views/statement-of-means/monthly-expenses.njk
  src/main/features/response/views/statement-of-means/other-dependants.njk
  src/main/features/response/views/statement-of-means/priority-debts.njk
  src/test/features/claimant-response/helpers/taskListBuilder.ts
  src/test/features/claimant-response/routes/payment-date.ts
  src/test/features/response/routes/statement-of-means/intro.ts
  src/test/features/response/routes/statement-of-means/monthly-income.ts
Labels: ns:cmc-citizen-frontend-pr-1065

#1076 ROC-4412: Request re-determination by claimant
  src/main/app/claims/ccjClient.ts
  src/main/app/claims/ccjModelConverter.ts
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/countyCourtJudgment.ts
  src/main/app/claims/models/countyCourtJudgmentType.ts
  src/main/app/claims/models/repaymentPlan.ts
  src/main/features/ccj/form/models/reDetermination.ts
  src/main/features/ccj/index.ts
  src/main/features/ccj/paths.ts
  src/main/features/ccj/routes/confirmation.ts
  src/main/features/ccj/routes/redetermination.ts
  src/main/features/ccj/routes/repayment-plan-summary.ts
  src/main/features/ccj/views/confirmation.njk
  src/main/features/ccj/views/redetermination.njk
  src/main/features/ccj/views/repayment-plan-summary.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJClaimant.njk
  src/main/modules/nunjucks/index.ts
  src/main/views/macro/paymentPlanTable.njk
  src/main/views/macro/repaymentPlanBlock.njk
  src/test/a11y/mocks.ts
  src/test/app/claims/CCJModelConverter.ts
  src/test/app/claims/models/claim.ts
  src/test/features/ccj/routes/ccjGuard.ts
  src/test/features/ccj/routes/confirmation.ts
  src/test/features/ccj/routes/reDetermination.ts
  src/test/features/ccj/routes/repayment-plan-summary.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1076

#1054 ROC-4318:Immediately
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/common/components/payment-intention/payment-option.ts
  src/main/common/helpers/CourtDecisionHelper.ts
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-option.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/macro/termsOfAgreementTable.njk
  src/main/features/claimant-response/views/sign-settlement-agreement.njk
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/common/helpers/courtDecisionHelper.ts
  src/test/common/helpers/paymentIntentionHelper.ts
  src/test/common/helpers/paymentPlanHelper.ts
  src/test/data/entity/responseData.ts
  src/test/features/claimant-response/routes/payment-option.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1054

#1083 run only non-admissions e2e tests
  docker-compose.functional-tests.yml
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/defence/full_admission_test.ts
  src/integration-test/tests/citizen/defence/part_admission_test.ts
Labels: ns:cmc-citizen-frontend-pr-1083
