Repository hmcts/cmc-citizen-frontend, pull requests merged in 2018-12, with the labels that each got.

#1204 Rename courtOfferPage to courtOfferedInstalmentsPage
  src/main/features/claimant-response/paths.ts
  src/main/features/claimant-response/routes/court-offered-instalments.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-option.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/main/features/claimant-response/views/court-offered-instalments.njk
  src/test/features/claimant-response/routes/court-offered-instalments.ts
  src/test/features/claimant-response/routes/payment-option.ts
Labels: ns:cmc-citizen-frontend-pr-1204

#1202 ROC-4783:Update court calculations - claimant immediately scenario
  src/main/features/claimant-response/routes/payment-option.ts
  src/main/features/claimant-response/views/court-offered-instalments.njk
  src/test/common/helpers/paymentIntentionHelper.ts
  src/test/features/claimant-response/routes/court-offered-instalments.ts
  src/test/features/claimant-response/routes/payment-option.ts
Labels: ns:cmc-citizen-frontend-pr-1202

#1206 change Math.round to Lodash round in court determination files
  src/main/features/claimant-response/routes/payment-option.ts
  src/main/features/claimant-response/routes/payment-plan.ts
Labels: ns:cmc-citizen-frontend-pr-1206

#1212 ROC-4859: increase logging on demo and prod
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:cmc-citizen-frontend-pr-1212

#1205 ROC-4568 remove blue box of evidence listed from defendant view when submitted
  src/main/features/response/views/evidence.njk
Labels: ns:cmc-citizen-frontend-pr-1205

#1207 ROC-4637 Refactor to allow defendants to request redetermination
  src/main/features/ccj/index.ts
  src/main/features/ccj/paths.ts
  src/main/features/ccj/routes/check-and-send.ts
  src/main/features/ccj/routes/confirmation-ccj.ts
  src/main/features/ccj/routes/confirmation-redetermination.ts
  src/main/features/ccj/routes/redetermination.ts
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/ccj/views/confirmation-redetermination.njk
  src/main/features/ccj/views/confirmation.njk
  src/test/a11y/mocks.ts
  src/test/features/ccj/routes/ccjGuard.ts
  src/test/features/ccj/routes/check-and-send.ts
  src/test/features/ccj/routes/confirmation-ccj.ts
  src/test/features/ccj/routes/confirmation-redetermination.ts
  src/test/features/ccj/routes/redetermination.ts
Labels: ns:cmc-citizen-frontend-pr-1207

#1215 ROC-4824 Sign a settlement agreement
  src/main/features/offer/routes/declaration.ts
  src/main/features/offer/views/declaration.njk
Labels: ns:cmc-citizen-frontend-pr-1215

#1214 Update dependencies that are failing on sonar
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1214

#1111 ROC-4301 Claimant submits paid in full flow
  src/integration-test/data/test-data.ts
  src/integration-test/tests/citizen/dashboard/dashboard_test.ts
  src/integration-test/tests/citizen/dashboard/pages/date-paid.ts
  src/integration-test/tests/citizen/dashboard/steps/paid-in-full.ts
  src/integration-test/tests/citizen/endToEnd/data/EndToEndTestData.ts
  src/integration-test/tests/citizen/paidInFull/steps/paidInFull.ts
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/paths.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/offerSettlement.njk
  src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
  src/main/features/paid-in-full/guards/paidInFullGuard.ts
  src/main/features/paid-in-full/index.ts
  src/test/app/claims/models/claim.ts
  src/test/features/claimant-response/routes/paid-in-full.ts
  types/integration-test-model.d.ts
Labels: ns:cmc-citizen-frontend-pr-1111

#1217 ROC-4865 declaration page has code that is not shown
  src/main/features/offer/views/declaration.njk
Labels: ns:cmc-citizen-frontend-pr-1217

#1218 ROC-4399 Part admit pay immediately statuses
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmissionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1218

#1220 ROC-4301 Turn paid in full on for AAT
  infrastructure/aat.tfvars
Labels: ns:cmc-citizen-frontend-pr-1220

#1159 ROC-4573 Reject Settlement Agreement [Defendant]
  src/main/app.ts
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/app/claims/models/settlement.ts
  src/main/app/claims/settlementAgreementClient.ts
  src/main/features/ccj/views/repayment-plan-summary.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/utilityMacros.njk
  src/main/features/settlement-agreement/form/models/defendantSettlementResponse.ts
  src/main/features/settlement-agreement/guards/settlementAgreementGuard.ts
  src/main/features/settlement-agreement/index.ts
  src/main/features/settlement-agreement/paths.ts
  src/main/features/settlement-agreement/routes/repayment-plan-summary.ts
  src/main/features/settlement-agreement/routes/settlement-agreement-confirmation.ts
  src/main/features/settlement-agreement/routes/sign-settlement-agreement.ts
  src/main/features/settlement-agreement/views/repayment-plan-summary.njk
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
  src/main/features/settlement-agreement/views/sign-settlement-agreement.njk
  src/main/modules/nunjucks/index.ts
  src/test/features/settlement-agreement/form/models/defendantSettlementResponse.ts
  src/test/features/settlement-agreement/routes/settlement-agreement-confirmation.ts
  src/test/features/settlement-agreement/routes/sign-settlement-agreement.ts
  src/test/http-mocks/settlement-agreement.ts
  tsconfig.json
Labels: ns:cmc-citizen-frontend-pr-1159

#1221 ROC-4401: part admission e2e
  src/integration-test/data/defence-type.ts
  src/integration-test/tests/citizen/claimantResponse/data/ClaimantResponseTestData.ts
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-check-and-send.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-court-offered-instalments.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-defendant-response.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-free-mediation.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-settle-admitted.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-task-list.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/defence/pages/statement-of-means/already-paid.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/integration-test/tests/citizen/endToEnd/data/EndToEndTestData.ts
  src/integration-test/tests/citizen/endToEnd/steps/helper.ts
  src/integration-test/tests/citizen/home/steps/defendant.ts
Labels: ns:cmc-citizen-frontend-pr-1221

#1216 ROC-4558 admission dashboard status for defendant company
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
  src/main/modules/nunjucks/index.ts
Labels: ns:cmc-citizen-frontend-pr-1216

#1223 ROC-4401: fixing broken e2e on master
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
Labels: ns:cmc-citizen-frontend-pr-1223

#1225 ROC-3887 Update content for confirmation page
  src/main/features/claim/views/confirmation.njk
Labels: ns:cmc-citizen-frontend-pr-1225

#1226 ROC-4736
  src/main/features/claim/views/total.njk
Labels: ns:cmc-citizen-frontend-pr-1226

#1228 ROC-4903 Fix reject part admit with mediation
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1228

#1231 Enable Paid In Full (PROD) and Admissions (AAT)
  infrastructure/aat.tfvars
  infrastructure/prod.tfvars
Labels: ns:cmc-citizen-frontend-pr-1231

#1222 ROC-4847 Accept Settlement Agreement [Defendant]
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/main/app/claims/settlementAgreementClient.ts
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/claimant-response/views/confirmation/accepted-payment-plan.njk
  src/main/features/claimant-response/views/confirmation/proposed-alternate-payment-plan.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
  src/main/features/settlement-agreement/routes/sign-settlement-agreement.ts
  src/main/features/settlement-agreement/views/macro/settlement-agreement.njk
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
  src/test/features/settlement-agreement/routes/sign-settlement-agreement.ts
  src/test/http-mocks/settlement-agreement.ts
Labels: ns:cmc-citizen-frontend-pr-1222

#1238 rm -rf idam www from /health
  src/main/routes/health.ts
Labels: ns:cmc-citizen-frontend-pr-1238

#1229 ROC-3384 prevent url dashboard manipulation
  src/main/features/dashboard/routes/claimant.ts
  src/main/features/dashboard/routes/defendant.ts
  src/test/features/dashboard/routes/claimant.ts
  src/test/features/dashboard/routes/defendant.ts
Labels: ns:cmc-citizen-frontend-pr-1229

#1237 ROC-4893: Adding court decision on check-and-send page
  src/main/features/claimant-response/views/check-and-send.njk
  src/test/features/claimant-response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1237

#1234 Changes made after review session
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
  src/main/features/response/views/statement-of-means/dependants.njk
  src/main/features/response/views/statement-of-means/dependants/education.njk
  src/main/features/response/views/statement-of-means/other-dependants.njk
  src/main/features/response/views/statement-of-means/unemployment.njk
Labels: ns:cmc-citizen-frontend-pr-1234

#1240 ROC-4930 Tell claimants details will be shared
  src/main/features/claim/views/claimant-company-details.njk
  src/main/features/claim/views/claimant-individual-details.njk
  src/main/features/claim/views/claimant-organisation-details.njk
  src/main/features/claim/views/claimant-sole-trader-details.njk
  src/test/features/claim/routes/claimant-company-details.ts
  src/test/features/claim/routes/claimant-individual-details.ts
  src/test/features/claim/routes/claimant-organisation-details.ts
  src/test/features/claim/routes/claimant-soleTrader-details.ts
Labels: ns:cmc-citizen-frontend-pr-1240

#1250 ROC-4950 Non grey hint text
  package.json
  src/main/features/claimant-response/views/choose-how-to-proceed.njk
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1250

#1257 ROC-4967 Tell claimant they will get a copy of the CCJ
  src/main/features/claimant-response/routes/confirmation.ts
  src/main/features/claimant-response/views/confirmation.njk
Labels: ns:cmc-citizen-frontend-pr-1257

#1259 ROC-4668 Check and send hide unused rows
  src/main/features/response/views/statement-of-means/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1259

#1262 Part admit should not include claim fee for settlement agreement
  src/main/features/claimant-response/helpers/amountHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1262

#1263 ROC-4964: Update first payment date
  src/main/features/claimant-response/routes/payment-plan.ts
  src/test/common/helpers/paymentIntentionHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1263

#1252 ROC-4976 Update content on check and send page
  src/main/features/response/views/macro/check-and-send/admission.njk
  src/main/features/response/views/statement-of-means/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1252

#1233 ROC-4941 Invalidate negative turnover
  src/main/features/response/form/models/statement-of-means/selfEmployment.ts
  src/test/features/response/form/models/statement-of-means/selfEmployment.ts
Labels: ns:cmc-citizen-frontend-pr-1233

#1243 ROC-4947 "Go to your account" button on settlement confirmation page
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
Labels: ns:cmc-citizen-frontend-pr-1243

#1254 ROC-4955 Change link to button
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1254

#1268 ROC:4957 - Consistent use of free mediation model
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/claims/models/claimant-response/rejectionClaimantResponse.ts
  src/main/app/claims/models/response/core/responseRejection.ts
  src/main/app/claims/responseModelConverter.ts
  src/main/common/utils/freeMediationUtil.ts
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/app/claims/models/claimant-response/rejectionClaimantResponse.ts
  src/test/app/claims/models/claimantResponse.ts
  src/test/common/utils/freeMediationUtil.ts
  src/test/data/entity/claimantResponseData.ts
Labels: ns:cmc-citizen-frontend-pr-1268

#1273 ROC-4952 Change content when claimant viewing financial details
  src/main/views/macro/financialDetails.njk
Labels: ns:cmc-citizen-frontend-pr-1273

#1210 ROC-4831 - production bug fix for check and send error
  src/main/features/response/helpers/taskListBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-1210

#1275 Update @types/node
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1275

#1272 ROC-4640: Claimant response journey bugs
  Jenkinsfile_CNP
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/routes/payment-option.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/test/common/helpers/paymentIntentionHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1272

#1244 ROC-4948 Make rejected settlement view same as the prototype
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1244
