Repository hmcts/cmc-citizen-frontend, pull requests merged in 2018-05, with the labels that each got.

#538 ROC-3527: Validate postcode format
  package.json
  src/integration-test/data/test-data.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/app/forms/models/address.ts
  src/main/app/forms/models/claimReference.ts
  src/main/app/forms/models/correspondenceAddress.ts
  src/main/app/forms/models/name.ts
  src/main/app/forms/models/partyDetails.ts
  src/main/app/forms/models/qualifiedStatementOfTruth.ts
  src/main/app/forms/models/timelineRow.ts
  src/main/app/forms/validation/validators/isBlank.ts
  src/main/features/ccj/form/models/qualifiedDeclaration.ts
  src/main/features/claim/form/models/claimAmountRow.ts
  src/main/features/claim/form/models/interestRate.ts
  src/main/features/claim/form/models/interestStartDate.ts
  src/main/features/claim/form/models/interestTotal.ts
  src/main/features/claim/form/models/reason.ts
  src/main/features/offer/form/models/offer.ts
  src/main/features/response/form/models/defence.ts
  src/main/features/response/form/models/defendantPaymentPlan.ts
  src/main/features/response/form/models/howMuchOwed.ts
  src/main/features/response/form/models/howMuchPaid.ts
  src/main/features/response/form/models/pay-by-set-date/explanation.ts
  src/main/features/response/form/models/qualifiedStatementOfTruth.ts
  src/main/features/response/form/models/statement-of-means/amountDescriptionRow.ts
  src/main/features/response/form/models/statement-of-means/courtOrderRow.ts
  src/main/features/response/form/models/statement-of-means/debtRow.ts
  src/main/features/response/form/models/statement-of-means/employerRow.ts
  src/main/features/response/form/models/statement-of-means/numberOfPeople.ts
  src/main/features/response/form/models/statement-of-means/otherDetails.ts
  src/main/features/response/form/models/statement-of-means/residence.ts
  src/main/features/response/form/models/statement-of-means/selfEmployed.ts
  src/main/features/response/form/models/whenDidYouPay.ts
  src/main/features/testing-support/models/updateResponseDeadlineRequest.ts
  src/test/app/drafts/models/address.ts
  src/test/app/forms/models/address.ts
  src/test/app/forms/models/companyDetails.ts
  src/test/app/forms/models/individualDetails.ts
  src/test/app/forms/models/organisationDetails.ts
  src/test/app/forms/models/partyDetails.ts
  src/test/app/forms/models/soleTraderDetails.ts
  src/test/app/forms/validation/validators/isNotBlankConstraint.ts
  src/test/features/response/tasks/yourDetails.ts
  src/test/http-mocks/draft-store.ts
  yarn.lock
Labels: po-review, pull-request: approved

#568 Update content security policy to include new inline js
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
Labels: pull-request: approved

#565 ROC-3629: rename isDefendantInCaseGuard -> onlyDefendantLinkedToClaimCanDoIt
  src/main/app/guards/onlyClaimantLinkedToClaimCanDoIt.ts
  src/main/app/guards/onlyDefendantLinkedToClaimCanDoIt.ts
  src/main/features/ccj/index.ts
  src/main/features/claim/routes/sealed-claim.ts
  src/main/features/response/index.ts
Labels: pull-request: approved, tested

#564 Simplify PDF downloads
  src/main/app/client/request.ts
  src/main/app/documents/documentsClient.ts
  src/main/app/utils/downloadUtils.ts
  src/main/features/claim/routes/receipt.ts
  src/main/features/offer/routes/agreement.ts
  src/main/features/response/routes/receipt.ts
  src/main/services/claimIssueReceiptPdfGenerator.ts
  src/main/services/sealedClaimPdfGenerator.ts
  src/test/http-mocks/claim-store.ts
Labels: pull-request: approved, tested

#575 ROC-3550: Update demo on changes to master
  Jenkinsfile_CNP
Labels: pull-request: approved

#569 ROC-3671: Move front-end validators in common repo
  package.json
  src/main/app/forms/models/companyDetails.ts
  src/main/app/forms/models/email.ts
  src/main/app/forms/models/evidenceRow.ts
  src/main/app/forms/models/organisationDetails.ts
  src/main/app/forms/models/qualifiedStatementOfTruth.ts
  src/main/app/forms/models/statementOfTruth.ts
  src/main/app/forms/models/timelineRow.ts
  src/main/app/forms/validation/validators/fractions.ts
  src/main/app/forms/validation/validators/isBooleanTrue.ts
  src/main/app/forms/validation/validators/isEmail.ts
  src/main/app/forms/validation/validators/isLessThan.ts
  src/main/app/forms/validation/validators/isLessThanOrEqualTo.ts
  src/main/app/forms/validation/validators/isLessThanOrEqualToSumOf.ts
  src/main/app/forms/validation/validators/maxLengthValidator.ts
  src/main/app/forms/validation/validators/min.ts
  src/main/app/forms/validation/validators/minTotal.ts
  src/main/app/forms/validation/validators/mobilePhone.ts
  src/main/features/ccj/form/models/declaration.ts
  src/main/features/ccj/form/models/paidAmount.ts
  src/main/features/ccj/form/models/qualifiedDeclaration.ts
  src/main/features/ccj/form/models/repaymentPlan.ts
  src/main/features/claim/form/models/claimAmountBreakdown.ts
  src/main/features/claim/form/models/claimAmountRow.ts
  src/main/features/claim/form/models/interestHowMuch.ts
  src/main/features/claim/form/models/interestTotal.ts
  src/main/features/offer/form/models/declaration.ts
  src/main/features/response/form/models/defendantPaymentPlan.ts
  src/main/features/response/form/models/howMuchOwed.ts
  src/main/features/response/form/models/howMuchPaid.ts
  src/main/features/response/form/models/impactOfDispute.ts
  src/main/features/response/form/models/qualifiedStatementOfTruth.ts
  src/main/features/response/form/models/statement-of-means/amountDescriptionRow.ts
  src/main/features/response/form/models/statement-of-means/bankAccountRow.ts
  src/main/features/response/form/models/statement-of-means/courtOrderRow.ts
  src/main/features/response/form/models/statement-of-means/debtRow.ts
  src/main/features/response/form/models/statement-of-means/education.ts
  src/main/features/response/form/models/statement-of-means/employerRow.ts
  src/main/features/response/form/models/statement-of-means/employment.ts
  src/main/features/response/form/models/statement-of-means/monthlyExpenses.ts
  src/main/features/response/form/models/statement-of-means/monthlyIncome.ts
  src/main/features/response/form/models/statement-of-means/numberOfPeople.ts
  src/main/features/response/form/models/statement-of-means/otherDetails.ts
  src/main/features/response/form/models/statement-of-means/selfEmployed.ts
  src/main/features/response/form/models/statementOfTruth.ts
  src/test/app/forms/validation/formValidator.ts
  src/test/app/forms/validation/validators/IsLessThanOrEqualToSumOf.ts
  src/test/app/forms/validation/validators/fractionsConstraint.ts
  src/test/app/forms/validation/validators/isBooleanConstraint.ts
  src/test/app/forms/validation/validators/isEmailConstraint.ts
  src/test/app/forms/validation/validators/isLessThan.ts
  src/test/app/forms/validation/validators/isLessThanOrEqualTo.ts
  src/test/app/forms/validation/validators/maxLength.ts
  src/test/app/forms/validation/validators/min.ts
  src/test/app/forms/validation/validators/minTotal.ts
  src/test/app/forms/validation/validators/mobileNumberConstraint.ts
  yarn.lock
Labels: pull-request: approved, tested

#573 Allow more rows for non-javascript users
  src/main/app/forms/models/multiRowForm.ts
  src/main/features/claim/form/models/claimAmountBreakdown.ts
Labels: pull-request: approved
