Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-10, with the labels that each got.

#1881 Added new acessibility statement page under footer lins
  src/test/routes/accessibility-statement.ts
Labels: ns:cmc-citizen-frontend-pr-1881

#1884 ROC-6058: Update Task list content and style
  src/main/features/claim/helpers/taskListBuilder.ts
  src/main/features/claim/views/task-list.njk
  src/main/features/claimant-response/views/task-list.njk
  src/main/features/response/views/task-list.njk
  src/main/public/stylesheets/components/_task-list.scss
  src/test/features/response/helpers/taskListBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-1884

#1887 ROC-6601 Mediation showing when it should not
  src/main/features/response/routes/check-and-send.ts
  src/main/features/response/views/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1887

#1886 ROC-6462
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/main/common/components/free-mediation/howFreeMediationWorks.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-reject-with-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-reject-with-mediation.njk
  src/main/features/response/views/confirmation/part-admission-steps.njk
  src/test/features/dashboard/routes/claimStatus/part-admission.ts
  src/test/features/dashboard/routes/dashboard/full-defence.ts
  src/test/features/dashboard/routes/dashboard/part-admission.ts
  src/test/features/dashboard/routes/dashboard/states-paid.ts
  src/test/features/response/routes/confirmation.ts
Labels: ns:cmc-citizen-frontend-pr-1886

#1846 Setup web chat
  .gitignore
  charts/cmc-citizen-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  gulpfile.js
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  package.json
  src/main/app.ts
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/ccj/views/confirmation-redetermination.njk
  src/main/features/claim/views/confirmation.njk
  src/main/features/claim/views/task-list.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/claimant-response/views/task-list.njk
  src/main/features/dashboard/views/directions-questionnaire.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/eligibility/views/mcol-eligibility.njk
  src/main/features/first-contact/views/start.njk
  src/main/features/offer/views/accepted.njk
  src/main/features/offer/views/offer-confirmation.njk
  src/main/features/offer/views/rejected.njk
  src/main/features/offer/views/settled.njk
  src/main/features/orders/views/confirmation.njk
  src/main/features/paid-in-full/views/confirmation.njk
  src/main/features/response/views/confirmation.njk
  src/main/features/response/views/counter-claim.njk
  src/main/features/response/views/eligibility/send-your-response-by-email.njk
  src/main/features/response/views/eligibility/under-18.njk
  src/main/features/response/views/task-list.njk
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
  src/main/modules/nunjucks/index.ts
  src/main/public/stylesheets/application.scss
  src/main/public/stylesheets/components/_offer-table.scss
  src/main/public/stylesheets/components/_web-chat.scss
  src/main/public/webchat/javascript/webchart-init.js
  src/main/routes/webchat.ts
  src/main/views/contact-us.njk
  src/main/views/govukTemplate.njk
  src/main/views/includes/contact-us-for-help.njk
  src/main/views/includes/scripts.njk
  src/main/views/macro/support.njk
  src/main/views/privacy-policy.njk
  src/main/views/terms-and-conditions.njk
  src/test/a11y/a11y.ts
  src/test/features/response/routes/full-admission/payment-date.ts
  src/test/features/response/routes/partial-admission/payment-date.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1846

#1892 Revert "ROC-6341 Setup web chat (#1846)"
  .gitignore
  charts/cmc-citizen-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  gulpfile.js
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  package.json
  src/main/app.ts
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/ccj/views/confirmation-redetermination.njk
  src/main/features/claim/views/confirmation.njk
  src/main/features/claim/views/task-list.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/claimant-response/views/task-list.njk
  src/main/features/dashboard/views/directions-questionnaire.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/eligibility/views/mcol-eligibility.njk
  src/main/features/first-contact/views/start.njk
  src/main/features/offer/views/accepted.njk
  src/main/features/offer/views/offer-confirmation.njk
  src/main/features/offer/views/rejected.njk
  src/main/features/offer/views/settled.njk
  src/main/features/orders/views/confirmation.njk
  src/main/features/paid-in-full/views/confirmation.njk
  src/main/features/response/views/confirmation.njk
  src/main/features/response/views/counter-claim.njk
  src/main/features/response/views/eligibility/send-your-response-by-email.njk
  src/main/features/response/views/eligibility/under-18.njk
  src/main/features/response/views/task-list.njk
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
  src/main/modules/nunjucks/index.ts
  src/main/public/stylesheets/application.scss
  src/main/public/stylesheets/components/_web-chat.scss
  src/main/public/stylesheets/components/offer-table.scss
  src/main/public/webchat/javascript/webchart-init.js
  src/main/routes/webchat.ts
  src/main/views/contact-us.njk
  src/main/views/govukTemplate.njk
  src/main/views/includes/contact-us-for-help.njk
  src/main/views/includes/scripts.njk
  src/main/views/macro/support.njk
  src/main/views/privacy-policy.njk
  src/main/views/terms-and-conditions.njk
  src/test/a11y/a11y.ts
  src/test/features/response/routes/full-admission/payment-date.ts
  src/test/features/response/routes/partial-admission/payment-date.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1892

#1802 ROC 6258: Update Confirmation screen with information on filing DQs
  src/main/features/response/views/confirmation/full-defence-steps.njk
  src/test/features/response/routes/confirmation.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1802

#1891 ROC-6458 Changing check-and-send page logic
  src/main/features/claimant-response/views/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1891

#1873 ROC-4043-Save claimant provided defendant phone number
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/main/app/claims/claimModelConverter.ts
  src/main/app/claims/models/details/theirs/company.ts
  src/main/app/claims/models/details/theirs/individual.ts
  src/main/app/claims/models/details/theirs/organisation.ts
  src/main/app/claims/models/details/theirs/soleTrader.ts
  src/main/app/claims/models/details/theirs/theirDetails.ts
  src/main/features/claim/paths.ts
  src/main/features/claim/routes/defendant-email.ts
  src/main/features/claim/routes/defendant-mobile.ts
  src/main/features/claim/views/check-and-send.njk
  src/main/features/claim/views/defendant-mobile.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/test/app/claims/claimModelConverter.ts
  src/test/data/draft/claimDraft.ts
  src/test/features/claim/routes/defendant-email.ts
  src/test/features/claim/routes/defendant-phone.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1873

#1896 Integrate web chat in citizen frontend
  .gitignore
  charts/cmc-citizen-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  gulpfile.js
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
  package.json
  src/main/app.ts
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/ccj/views/confirmation-redetermination.njk
  src/main/features/claim/views/confirmation.njk
  src/main/features/claim/views/task-list.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/claimant-response/views/task-list.njk
  src/main/features/dashboard/views/directions-questionnaire.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/eligibility/views/mcol-eligibility.njk
  src/main/features/first-contact/views/start.njk
  src/main/features/offer/views/accepted.njk
  src/main/features/offer/views/offer-confirmation.njk
  src/main/features/offer/views/rejected.njk
  src/main/features/offer/views/settled.njk
  src/main/features/orders/views/confirmation.njk
  src/main/features/paid-in-full/views/confirmation.njk
  src/main/features/response/views/confirmation.njk
  src/main/features/response/views/counter-claim.njk
  src/main/features/response/views/eligibility/send-your-response-by-email.njk
  src/main/features/response/views/eligibility/under-18.njk
  src/main/features/response/views/task-list.njk
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
  src/main/modules/nunjucks/index.ts
  src/main/public/stylesheets/application.scss
  src/main/public/stylesheets/components/_offer-table.scss
  src/main/public/stylesheets/components/_web-chat.scss
  src/main/public/webchat/javascript/webchart-init.js
  src/main/routes/webchat.ts
  src/main/views/contact-us.njk
  src/main/views/govukTemplate.njk
  src/main/views/includes/contact-us-for-help.njk
  src/main/views/includes/scripts.njk
  src/main/views/macro/support.njk
  src/main/views/privacy-policy.njk
  src/main/views/terms-and-conditions.njk
  src/test/a11y/a11y.ts
  src/test/features/response/routes/full-admission/payment-date.ts
  src/test/features/response/routes/partial-admission/payment-date.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1896

#1897 ROC-4043-Fix -Draft failure for the mobile phone of Defendant
  src/main/app/drafts/draft-data/claimDraft.ts
Labels: ns:cmc-citizen-frontend-pr-1897

#1901 ROC-6643 Dashboard after intention to proceed deadline has passed
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/intentionToProceed.njk
  src/main/features/dashboard/views/macro/claimStatus/utilityMacros.njk
  src/test/app/claims/models/claim.ts
  src/test/data/entity/fullDefenceData.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/dashboard/full-defence.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1901

#1875 ROC-5459 check-and-send page for defendant as company with contact person
  src/main/views/macro/party/details.njk
  src/test/common/helpers/courtDecisionHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1875

#1907 ROC-6701 Only delete the draft claim when claim is submitted successfully
  src/main/app/logging/customEventTracker.ts
  src/main/features/claim/routes/pay.ts
  src/test/features/claim/routes/pay.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1907

#1880 ROC-6480 Upgraded to node 10.6.0
  .nvmrc
  .travis.yml
  Dockerfile
  Jenkinsfile_CNP
  README.md
  charts/cmc-citizen-frontend/values.yaml
  integration-tests.Dockerfile
  package.json
  src/main/app/client/request.ts
  src/main/features/claim/helpers/feesTableViewHelper.ts
  src/main/features/claimant-response/routes/counter-offer-accepted.ts
  src/main/features/claimant-response/routes/pay-by-set-date-accepted.ts
  src/main/features/response/draft/responseDraft.ts
  src/main/modules/nunjucks/index.ts
  src/test/common/helpers/courtDecisionHelper.ts
  src/test/http-mocks/claim-store.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1880

#1906 ROC-6700 Old defences have wrong dashboard
  src/main/app/claims/models/claim.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1906

#1905 ROC-4043 claimant provide defendant phone
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/main/app/claims/claimModelConverter.ts
  src/main/app/claims/models/details/theirs/company.ts
  src/main/app/claims/models/details/theirs/individual.ts
  src/main/app/claims/models/details/theirs/organisation.ts
  src/main/app/claims/models/details/theirs/soleTrader.ts
  src/main/app/claims/models/details/theirs/theirDetails.ts
  src/main/features/claim/paths.ts
  src/main/features/claim/routes/defendant-email.ts
  src/main/features/claim/routes/defendant-mobile.ts
  src/main/features/claim/views/check-and-send.njk
  src/main/features/claim/views/defendant-mobile.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/test/app/claims/claimModelConverter.ts
  src/test/data/draft/claimDraft.ts
  src/test/features/claim/routes/defendant-email.ts
  src/test/features/claim/routes/defendant-phone.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1905

#1908 ROC-6000 Let user type in commas according to currency format
  src/main/public/js/calculate-amount-total.js
Labels: ns:cmc-citizen-frontend-pr-1908

#1916 Fix typo in status
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/features/dashboard/routes/dashboard/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1916

#1903 GitHub actions trial
  .github/workflows/push.yml
  .travis.yml
  Jenkinsfile_CNP
  README.md
  package.json
Labels: ns:cmc-citizen-frontend-pr-1903

#1904 Resolve spacing in contact us links
  src/main/features/dashboard/views/index.njk
  src/main/public/stylesheets/components/_web-chat.scss
  src/main/views/macro/support.njk
Labels: ns:cmc-citizen-frontend-pr-1904

#1917 ROC-6742 Incorrect deadline
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
Labels: ns:cmc-citizen-frontend-pr-1917

#1923 ROC-6744 Intention to proceed incorrect dashboard
  src/main/app/claims/models/claim.ts
  src/test/app/claims/models/claim.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1923

#1894 ROC 6536 store response to dq expert response question
  src/main/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts
  src/test/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts
  src/test/app/claims/responseModelConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1894

#1936 Fix sonar issue
  .github/workflows/push.yml
  Jenkinsfile_CNP
  package.json
Labels: ns:cmc-citizen-frontend-pr-1936

#1930 ROC-6763: Add hearing court name in direction order
  src/main/app/claims/models/directionOrder.ts
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/main/views/macro/addressFragment.njk
  src/test/app/claims/models/claim.ts
  src/test/features/dashboard/routes/claimStatus/orders.ts
  src/test/features/dashboard/routes/dashboard/orders.ts
Labels: ns:cmc-citizen-frontend-pr-1930

#1937 ROC-6511: IOC Feature flag for cmc-citizen-frontend
  charts/cmc-citizen-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/dockertests.json
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/variables.tf
Labels: ns:cmc-citizen-frontend-pr-1937

#1890 ROC-5421 Defendant phone number by defendant
  src/main/app/forms/models/partyDetails.ts
  src/main/features/claim/views/check-and-send.njk
  src/main/features/response/routes/your-details.ts
  src/main/features/response/routes/your-dob.ts
  src/main/features/response/views/check-and-send.njk
  src/main/features/response/views/your-details.njk
  src/main/views/macro/form.njk
  src/main/views/macro/party/details.njk
  src/test/data/entity/party.ts
  src/test/features/claim/routes/check-and-send.ts
  src/test/features/response/routes/your-details.ts
  src/test/features/response/routes/your-dob.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1890

#1888 ROC-5193 Capture defendant's full name - Defendant Journey
  src/main/app/claims/models/details/theirs/theirDetails.ts
  src/main/app/claims/models/details/yours/individual.ts
  src/main/app/claims/models/details/yours/party.ts
  src/main/app/claims/responseModelConverter.ts
  src/main/app/forms/models/splitNamedPartyDetails.ts
  src/main/features/response/index.ts
  src/main/features/response/routes/your-details.ts
  src/main/features/response/views/your-details.njk
  src/main/public/stylesheets/components/_form.scss
  src/main/views/macro/form.njk
  src/main/views/macro/party/details.njk
  src/test/app/claims/models/details/theirs/theirDetails.ts
  src/test/app/claims/models/details/yours/party.ts
  src/test/app/claims/responseModelConverter.ts
  src/test/app/forms/models/individualDetails.ts
  src/test/app/forms/models/soleTraderDetails.ts
  src/test/data/draft/partyDetails.ts
  src/test/features/response/routes/your-details.ts
Labels: ns:cmc-citizen-frontend-pr-1888

#1951 Confirmation page content fix
  src/main/features/claimant-response/views/confirmation.njk
Labels: ns:cmc-citizen-frontend-pr-1951
