Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-01, with the labels that each got.

#1270 ROC-4993 PO Review session bugs
  src/main/common/components/ccj/paid-amount-summary.njk
  src/main/common/components/ccj/paid-amount.njk
  src/main/common/components/payment-intention/payment-plan.njk
  src/main/common/components/payment-intention/payment-plan.ts
  src/main/features/claimant-response/views/accept-payment-method.njk
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/claimant-response/views/macro/evidenceTable.njk
  src/main/features/claimant-response/views/macro/timelineTable.njk
  src/main/features/claimant-response/views/settle-admitted.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
  src/main/features/response/views/confirmation/full-admission-steps.njk
  src/main/features/response/views/confirmation/part-admission-steps.njk
  src/test/features/claimant-response/routes/accept-payment-method.ts
Labels: ns:cmc-citizen-frontend-pr-1270

#1292 ROC-4950: pin codacy-coverage to latest supported version
  Dockerfile
  package.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1292

#1293 ROC-4988 Update content for paid in full section
  src/main/common/components/payment-intention/payment-plan.njk
  src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1293

#1274 ROC-4953 settlement agreement content
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/macro/termsOfAgreementTable.njk
Labels: ns:cmc-citizen-frontend-pr-1274

#1298 Set admissions to false
  infrastructure/aat.tfvars
Labels: ns:cmc-citizen-frontend-pr-1298

#1219 ROC-4301: Paid in full for admissions
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmissionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/paidInFullDefendant.njk
  src/test/app/claims/models/claim.ts
  src/test/features/claimant-response/routes/paid-in-full.ts
Labels: ns:cmc-citizen-frontend-pr-1219

#1278 ROC-4994 Their financial details not showing monthly amounts
  src/main/features/claimant-response/filters/monthly-amount-view-filter.ts
  src/main/features/claimant-response/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/views/macro/financialDetails.njk
  src/test/modules/nunjucks/filters/monthlyAmountViewFilter.ts
Labels: ns:cmc-citizen-frontend-pr-1278

#1304 Turn admissions on for AAT
  infrastructure/aat.tfvars
Labels: ns:cmc-citizen-frontend-pr-1304

#1303 ROC-4991 Adjust width of content
  package.json
  src/main/features/claimant-response/views/choose-how-to-proceed.njk
  src/main/public/stylesheets/components/_layout.scss
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1303

#1309 ROC-4301: Paid in full for admissions, adding CCJ certificate link
  src/main/features/dashboard/views/macro/claimStatus/paidInFullDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1309

#1314 ROC-5020: Use correct claim amount which should include fee for full admission
  src/main/common/helpers/paymentPlanHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1314

#1311 ROC-5025 Hide evidence section if none provided
  src/main/features/claimant-response/views/defendants-response.njk
Labels: ns:cmc-citizen-frontend-pr-1311

#1318 ROC-4567: Claim details page Bug fix which got introduced by other story
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1318

#1316 Turn admissions on in Prod
  infrastructure/prod.tfvars
Labels: ns:cmc-citizen-frontend-pr-1316

#1333 ROC-5057 Paid in full not appearing
  src/main/features/dashboard/views/macro/caseHistory.njk
Labels: ns:cmc-citizen-frontend-pr-1333

#1323 ROC-5041: Bug fix def's dashboard and claim details as comp/org
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1323

#1331 ROC-5038: Remove heading when there is no statement of means reason
  src/main/features/claimant-response/views/defendants-response.njk
Labels: ns:cmc-citizen-frontend-pr-1331

#1324 ROC-4861 How free mediation works
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/dockertests.json
  config/mocha.json
  infrastructure/main.tf
  infrastructure/variables.tf
  src/main/app.ts
  src/main/features/mediation/draft/draftMediation.ts
  src/main/features/mediation/index.ts
  src/main/features/mediation/paths.ts
  src/main/features/mediation/routes/how-mediation-works.ts
  src/main/features/mediation/views/how-mediation-works.njk
  src/test/features/mediation/draft/draft.ts
  src/test/features/mediation/routes/how-mediation-works.ts
  tsconfig.json
Labels: ns:cmc-citizen-frontend-pr-1324

#1344 ROC-5061 Request CCJ after settlement rejected
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1344

#1327 ROC - 5042 claimant dashboard update for company part admit rejection
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1327

#1310 ROC-4990 - Company/Sole Trader details are missing in claim PDF
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/app/claims/models/details/theirs/theirDetails.ts
  src/main/app/forms/models/partyDetails.ts
  src/main/features/claim/routes/check-and-send.ts
  src/main/features/claim/views/check-and-send.njk
  src/main/features/response/routes/check-and-send.ts
  src/test/app/claims/models/details/theirs/theirDetails.ts
Labels: ns:cmc-citizen-frontend-pr-1310

#1338 ROC-5083 Limit character limit to 20 for address lines
  package.json
  src/main/app/forms/models/address.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1338

#1352 ROC-5095 - Change button text
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/eligibility/views/claim-is-for-tenancy-deposit.njk
  src/main/features/eligibility/views/claim-type.njk
  src/main/features/eligibility/views/claim-value.njk
  src/main/features/eligibility/views/claimant-address.njk
  src/main/features/eligibility/views/defendant-address.njk
  src/main/features/eligibility/views/defendant-age.njk
  src/main/features/eligibility/views/government-department.njk
  src/main/features/eligibility/views/help-with-fees.njk
  src/main/features/eligibility/views/over-18.njk
  src/main/features/eligibility/views/single-defendant.njk
  src/main/features/first-contact/views/claim-reference.njk
  src/main/features/mediation/views/how-mediation-works.njk
  src/main/features/offer/views/response.njk
  src/main/features/response/views/more-time-confirmation.njk
  src/main/features/response/views/send-company-financial-details.njk
  src/main/features/response/views/statement-of-means/intro.njk
  src/main/views/enter-claim-number.njk
  src/main/views/no-claim-number.njk
Labels: ns:cmc-citizen-frontend-pr-1352

#1359 ROC-5111: disable healthcheck on pay service when using mockPay=true
  src/main/routes/health.ts
Labels: ns:cmc-citizen-frontend-pr-1359

#1340 ROC-4986 Change content to match prototype
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1340

#1317 Optimise docker image build layers
  Dockerfile
Labels: ns:cmc-citizen-frontend-pr-1317

#1345 ROC-5071: Interlocutory statutes work
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedDefendant.njk
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1345

#1360 ROC 5005 investigation when claim generation fails after successful payment
  src/main/app/logging/customEventTracker.ts
  src/main/features/claim/routes/pay.ts
Labels: ns:cmc-citizen-frontend-pr-1360

#1341 ROC-5036 Update to use support email address
  src/main/features/claimant-response/views/confirmation/proposed-alternate-payment-plan-to-business-defendant.njk
Labels: ns:cmc-citizen-frontend-pr-1341

#1343 Update @types/lodash
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1343

#1370 ROC-5123 Wrong content
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1370

#1353 ROC-5069 claim status part admit by set date shows full amount paid
  src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1353
