Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-07, with the labels that each got.

#1699 ROC-5896 Enable mediation task when responding when an already paid dispute
  src/integration-test/tests/citizen/claimantResponse/steps/defendant.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/features/response/helpers/taskListBuilder.ts
  src/main/features/response/views/check-and-send.njk
  src/test/features/response/helpers/taskListBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-1699

#1702 ROC-5903 graceless login receiver failure
  src/main/app/idam/idamClient.ts
  src/test/http-mocks/idam.ts
  src/test/routes/receiver.ts
Labels: ns:cmc-citizen-frontend-pr-1702

#1680 ROC-5750:See this courts facilities
  src/main/app/court-finder/courtDetails.ts
  src/main/app/court-finder/courtDetailsResponse.ts
  src/main/app/court-finder/courtFinderClient.ts
  src/main/app/court-finder/facilities.ts
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/forms/models/hearingLocation.ts
  src/main/features/directions-questionnaire/routes/hearing-location.ts
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/test/a11y/mocks.ts
  src/test/app/court-finder/courtFinderClient.ts
  src/test/features/directions-questionnaire/routes/hearing-location.ts
  src/test/http-mocks/court-finder-client.ts
Labels: ns:cmc-citizen-frontend-pr-1680

#1712 Update helm dependencies
  Jenkinsfile_CNP
  charts/cmc-citizen-frontend/Chart.yaml
Labels: ns:cmc-citizen-frontend-pr-1712

#1710 ROC-5861 - Part Admission - Pay immediately, claimant not able to request CCJ after deadline
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/ccj/routes/check-and-send.ts
  src/main/features/ccj/routes/paid-amount-summary.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmissionClaimant.njk
  src/test/app/claims/models/claim.ts
  src/test/features/ccj/routes/check-and-send.ts
  src/test/features/ccj/routes/paid-amount-summary.ts
Labels: ns:cmc-citizen-frontend-pr-1710

#1713 RO-5736: Allow response receipt for defendant on ccj request
  src/main/features/response/index.ts
  src/test/features/response/routes/response-receipt.ts
Labels: ns:cmc-citizen-frontend-pr-1713

#1670 ROC-5568 CCJ dashboard route tests
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/routes/claimant.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/breachOfPaymentDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedDefendant.njk
  src/test/app/claims/models/claim.ts
  src/test/data/entity/ccjData.ts
  src/test/data/entity/courtDeterminationData.ts
  src/test/data/entity/responseData.ts
  src/test/features/dashboard/routes/claimStatus/ccj.ts
  src/test/features/dashboard/routes/dashboard/ccj.ts
  src/test/features/dashboard/routes/index.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1670

#1716 ROC-5971 Claimant response confirmation page
  src/main/features/claimant-response/views/confirmation.njk
  src/main/modules/nunjucks/index.ts
Labels: ns:cmc-citizen-frontend-pr-1716

#1675 ROC-5753 fix states paid rejected dashboard
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/utilityMacros.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1675, pinned

#1730 ROC 6032 App Insights to track dashboard failures
  src/main/features/dashboard/index.ts
Labels: ns:cmc-citizen-frontend-pr-1730

#1732 Update Helm chart to use hmctspublic
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
Labels: ns:cmc-citizen-frontend-pr-1732

#1706 ROC-5899 States paid what happens next fix
  src/main/features/response/views/confirmation/part-admission-steps.njk
  src/test/data/entity/responseData.ts
  src/test/features/response/routes/confirmation.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1706

#1734 Merge ITHC to master
  infrastructure/ithc.tfvars
Labels: ns:cmc-citizen-frontend-pr-1734

#1718 ROC-5902:Mediation corrections in check and send
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/response/views/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1718

#1715 ROC-5952 Mediation showing on full admission
  src/main/features/response/views/check-and-send.njk
  src/main/features/response/views/statement-of-means/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1715

#1742 ROC-5387 Added missing response converter test file
  src/main/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts
  src/main/app/claims/models/response/fullDefenceResponse.ts
  src/main/app/claims/models/response/partialAdmissionResponse.ts
  src/test/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts
  src/test/app/claims/responseModelConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1742

#1738 ROC-6059 Part admission incorrect dashboard
  src/main/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1738

#1744 ROC-5373 Mediation smaller PR
  config/default.json
  src/main/common/components/free-mediation/freeMediationTask.ts
  src/main/features/claim/routes/pay.ts
  src/main/features/claimant-response/index.ts
  src/main/features/claimant-response/routes/intention-to-proceed.ts
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/modules/nunjucks/index.ts
  src/test/features/claimant-response/routes/intention-to-proceed.ts
Labels: ns:cmc-citizen-frontend-pr-1744

#1736 ROC-6029 Claimant response confirmation mediation not showing
  src/main/features/claimant-response/views/confirmation.njk
Labels: ns:cmc-citizen-frontend-pr-1736

#1741 ROC-5873 Remove link to CCJ on claimant's offer accepted claim status page
  src/main/features/dashboard/views/macro/claimStatus/offerAccepted.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1741

#1735 ROC-6026 Wrong amount on states paid claim details
  src/main/features/dashboard/views/macro/claimStatus/statesPaidAccepted.njk
Labels: ns:cmc-citizen-frontend-pr-1735

#1737 ROC-6038 Claimant response dashboard wrong content
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1737

#1752 Revert timeout change - increase for PR only
  charts/cmc-citizen-frontend/values.preview.template.yaml
  config/default.json
Labels: ns:cmc-citizen-frontend-pr-1752

#1753 Add http_timeout for aat functional testing on master
  infrastructure/aat.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:cmc-citizen-frontend-pr-1753

#1739 ROC-6062 Part admit confirmation page
  src/main/features/response/views/confirmation/part-admission-steps.njk
  src/main/features/response/views/confirmation/part-admission.njk
Labels: ns:cmc-citizen-frontend-pr-1739

#1754 ROC-6097 View defendants response
  src/main/features/claimant-response/routes/defendants-response.ts
  src/main/features/claimant-response/views/defendants-response.njk
Labels: ns:cmc-citizen-frontend-pr-1754

#1731 ROC-6036 Reject claim because I paid what i owe confirmation
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/main/features/response/views/confirmation/full-defence-steps.njk
  src/main/features/response/views/confirmation/full-defence.njk
  src/test/features/response/routes/confirmation.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1731

#1756 ROC-6105 Allow zero declared income amount
  src/main/features/claimant-response/filters/monthly-amount-view-filter.ts
  src/test/features/claimant-response/filters/monthly-amount-view-filter.ts
Labels: ns:cmc-citizen-frontend-pr-1756

#1757 Build integration tests image in hmctspublic
  .dockerignore
  acb.tpl.yaml
  docker-compose.functional-tests.yml
  docker-compose.nightly-functional-tests.yml
  docker-compose.smoke-tests.yml
  docker-compose.yml
  integration-tests.Dockerfile
Labels: ns:cmc-citizen-frontend-pr-1757
