Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-08, with the labels that each got.

#1746 ROC-6082 States paid dashboard issue for defendant
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/test/data/entity/fullDefenceData.ts
  src/test/data/entity/responseData.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
  src/test/features/dashboard/routes/dashboard/states-paid.ts
Labels: ns:cmc-citizen-frontend-pr-1746

#1762 RonanContentChange
  src/main/features/claim/views/new-features-consent.njk
  src/test/features/claim/routes/new-features-consent.ts
Labels: ns:cmc-citizen-frontend-pr-1762

#1747 ROC-6028 Wrong details showing on contact them page
  src/main/features/dashboard/views/contact-them.njk
Labels: ns:cmc-citizen-frontend-pr-1747

#1775 ROC-6171 Fix pay-date test (for 20 years)
  src/test/features/claimant-response/routes/payment-date.ts
Labels: ns:cmc-citizen-frontend-pr-1775

#1771 ROC-6155 - Self witness content change
  src/main/features/directions-questionnaire/views/self-witness.njk
Labels: ns:cmc-citizen-frontend-pr-1771

#1759 ROC-6008 - Fix duplication of claim fee on part admission CCJ request
  src/main/common/components/ccj/paid-amount-summary.njk
  src/main/common/components/ccj/paid-amount-summary.ts
  src/main/common/helpers/ccjHelper.ts
  src/main/features/ccj/form/models/paidAmount.ts
  src/main/features/ccj/routes/check-and-send.ts
  src/main/features/ccj/routes/paid-amount-summary.ts
  src/main/features/ccj/routes/paid-amount.ts
  src/main/features/claimant-response/routes/paid-amount-summary.ts
  src/test/features/ccj/routes/check-and-send.ts
  src/test/features/ccj/routes/paid-amount-summary.ts
Labels: ns:cmc-citizen-frontend-pr-1759

#1772 ROC-5945 - Expert guidance content change
  src/main/features/directions-questionnaire/views/expert-guidance.njk
Labels: ns:cmc-citizen-frontend-pr-1772

#1773 ROC-6161 - Permission to use an expert content change
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/directions-questionnaire/views/permission-for-expert.njk
  src/main/features/response/views/check-and-send.njk
  src/test/features/directions-questionnaire/routes/permission-for-expert.ts
  src/test/features/response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1773

#1701 ROC-5818 Why do you disagree with the order page
  src/main/app.ts
  src/main/features/orders/draft/ordersDraft.ts
  src/main/features/orders/form/models/disagreeReason.ts
  src/main/features/orders/index.ts
  src/main/features/orders/paths.ts
  src/main/features/orders/routes/disagree-with-order.ts
  src/main/features/orders/views/disagree-with-order.njk
  src/test/a11y/a11y.ts
  src/test/features/orders/draft/ordersDraft.ts
  src/test/features/orders/form/models/disagreeReason.ts
  src/test/features/orders/routes/disagree-with-order.ts
  src/test/http-mocks/draft-store.ts
  tsconfig.json
Labels: ns:cmc-citizen-frontend-pr-1701

#1768 Move madeBy from form models to claim models
  src/main/app/claims/ccjClient.ts
  src/main/app/claims/models/claimant-response/reDetermination.ts
  src/main/app/claims/models/madeBy.ts
  src/main/app/claims/models/settlement.ts
  src/main/features/ccj/routes/confirmation-redetermination.ts
  src/main/features/ccj/routes/redetermination.ts
  src/main/features/claimant-response/helpers/settlementHelper.ts
  src/main/features/directions-questionnaire/helpers/directionsQuestionnaireHelper.ts
  src/main/features/directions-questionnaire/routes/hearing-dates.ts
  src/main/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/main/features/directions-questionnaire/routes/hearing-location.ts
  src/main/features/settlement-agreement/routes/repayment-plan-summary.ts
  src/main/modules/nunjucks/index.ts
  src/test/a11y/a11y.ts
  src/test/app/claims/CCJModelConverter.ts
  src/test/app/claims/models/claim.ts
  src/test/app/claims/models/settlement.ts
  src/test/data/entity/offer.ts
  src/test/features/ccj/routes/ccjGuard.ts
  src/test/features/ccj/routes/confirmation-redetermination.ts
  src/test/features/ccj/routes/redetermination.ts
  src/test/features/ccj/routes/repayment-plan-summary.ts
  src/test/features/claimant-response/helpers/settlementHelper.ts
  src/test/features/directions-questionnaire/helpers/directionsQuestionnaireHelper.ts
  src/test/features/directions-questionnaire/routes/hearing-dates-picker.ts
  src/test/features/directions-questionnaire/routes/hearing-dates.ts
  src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/test/features/directions-questionnaire/routes/hearing-location.ts
  src/test/features/directions-questionnaire/routes/helper/dqRouteHelper.ts
  src/test/features/offer/routes/declaration.ts
  src/test/http-mocks/claim-store.ts
  src/test/http-mocks/settlement-agreement.ts
Labels: ns:cmc-citizen-frontend-pr-1768

#1774 ROC-6153 - Mediation content change
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/main/features/response/views/confirmation/full-defence-steps.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
  src/test/features/response/routes/confirmation.ts
Labels: ns:cmc-citizen-frontend-pr-1774

#1779 ROC-6180: Fix DQ unit tests and route tests in master
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/app/claims/models/claim.ts
  src/test/features/claimant-response/helpers/directionsQuestionnaireHelper.ts
  src/test/features/claimant-response/routes/check-and-send.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/directions-questionnaire/routes/expert-evidence.ts
  src/test/features/directions-questionnaire/routes/expert-guidance.ts
  src/test/features/directions-questionnaire/routes/expert-reports.ts
  src/test/features/directions-questionnaire/routes/expert.ts
  src/test/features/directions-questionnaire/routes/hearing-dates-picker.ts
  src/test/features/directions-questionnaire/routes/hearing-dates.ts
  src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/test/features/directions-questionnaire/routes/hearing-location.ts
  src/test/features/directions-questionnaire/routes/other-witnesses.ts
  src/test/features/directions-questionnaire/routes/permission-for-expert.ts
  src/test/features/directions-questionnaire/routes/self-witness.ts
  src/test/features/directions-questionnaire/routes/support-required.ts
  src/test/features/directions-questionnaire/routes/why-expert-is-needed.ts
  src/test/features/orders/routes/disagree-with-order.ts
  src/test/features/response/helpers/taskListBuilder.ts
  src/test/features/response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1779

#1743 ROC-5811:Use next working day api
  src/main/app/claims/calendarClient.ts
  src/main/app/claims/models/claim.ts
  src/main/features/claimant-response/routes/confirmation.ts
  src/main/features/claimant-response/views/confirmation/accepted-payment-plan.njk
  src/main/features/claimant-response/views/confirmation/proposed-alternate-payment-plan.njk
  src/main/features/dashboard/routes/claimant.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/a11y/mocks.ts
  src/test/app/claims/calendarClient.ts
  src/test/app/claims/models/claim.ts
  src/test/features/claimant-response/routes/confirmation.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/settlement.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1743

#1778 ROC-6154 Intention to proceed confirmation content
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/routes/intention-to-proceed.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/response/views/confirmation/full-defence-steps.njk
  src/test/features/response/routes/confirmation.ts
Labels: ns:cmc-citizen-frontend-pr-1778

#1777 ROC-6166 Re-order list of support items
  src/main/features/directions-questionnaire/views/support-required.njk
  src/main/public/stylesheets/components/_income-expense-source.scss
Labels: ns:cmc-citizen-frontend-pr-1777

#1781 bump version to fetch feature-toggle api from hmctspublic
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
Labels: ns:cmc-citizen-frontend-pr-1781

#1780 ROC-6175: Fix DQ validation issue
  src/main/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts
  src/main/features/directions-questionnaire/forms/models/expertReports.ts
  src/test/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts
  src/test/features/directions-questionnaire/form/models/expertReports.ts
Labels: ns:cmc-citizen-frontend-pr-1780

#1765 ROC-6138 Allow counterproposal of pay by set date against sole trader defendant
  src/main/features/claimant-response/routes/payment-date.ts
  src/main/features/claimant-response/views/court-offered-set-date.njk
Labels: ns:cmc-citizen-frontend-pr-1765

#1770 ROC-6086 Add content to claimant's timeline page
  src/main/features/claim/views/timeline.njk
  src/test/features/claim/routes/timeline.ts
Labels: ns:cmc-citizen-frontend-pr-1770

#1784 disable auto merge to demo
  Jenkinsfile_CNP
Labels: ns:cmc-citizen-frontend-pr-1784

#1788 enable auto merge
  Jenkinsfile_CNP
Labels: ns:cmc-citizen-frontend-pr-1788

#1767 ROC-6031 Update claimant settlement pages
  src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
  src/main/features/paid-in-full/views/date-paid.njk
  src/test/features/claimant-response/routes/paid-in-full.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
  src/test/features/paid-in-full/routes/date-paid.ts
Labels: ns:cmc-citizen-frontend-pr-1767

#1787 ROC-5373: Bug Bash
  src/main/common/components/free-mediation/freeMediationCheckAndSendBlock.njk
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/response/views/check-and-send.njk
  src/main/features/response/views/confirmation/full-defence-steps.njk
  src/test/features/response/routes/confirmation.ts
Labels: ns:cmc-citizen-frontend-pr-1787

#1786 ROC 6200 check and send court name must not be null
  src/main/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/test/features/claimant-response/helpers/taskListBuilder.ts
  src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
Labels: ns:cmc-citizen-frontend-pr-1786

#1789 ROC-6177-Fixed statement of truth for the business defendant
  src/main/app/common/signatureType.ts
  src/main/features/response/form/models/qualifiedStatementOfTruth.ts
  src/main/features/response/routes/check-and-send.ts
  src/main/views/macro/statementOfTruth.njk
Labels: ns:cmc-citizen-frontend-pr-1789

#1795 ROC-5823: Confirmation screen and converter
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/models/reviewOrder.ts
  src/main/app/claims/ordersConverter.ts
  src/main/app/documents/documentsClient.ts
  src/main/features/orders/index.ts
  src/main/features/orders/paths.ts
  src/main/features/orders/routes/confirmation.ts
  src/main/features/orders/routes/disagree-with-order.ts
  src/main/features/orders/routes/review-order-receipt.ts
  src/main/features/orders/views/confirmation.njk
  src/test/a11y/a11y.ts
  src/test/app/claims/claimStoreClient.ts
  src/test/app/claims/models/reviewOrder.ts
  src/test/app/claims/ordersConverter.ts
  src/test/features/orders/routes/confirmation.ts
  src/test/features/orders/routes/disagree-with-order.ts
  src/test/features/orders/routes/review-order-receipt.ts
  src/test/http-mocks/claim-store.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1795

#1791 ROC-6140 Claimant response check and send
  src/main/features/claimant-response/views/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1791

#1763 ROC-6047 claimant hearing pdf download
  src/main/app/documents/documentsClient.ts
  src/main/features/claimant-response/index.ts
  src/main/features/claimant-response/paths.ts
  src/main/features/claimant-response/routes/claimant-hearing-receipt.ts
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/response/views/confirmation.njk
  src/test/a11y/a11y.ts
  src/test/data/entity/claimantResponseData.ts
  src/test/features/claimant-response/routes/claimant-hearing-receipt.ts
  src/test/features/claimant-response/routes/confirmation.ts
Labels: ns:cmc-citizen-frontend-pr-1763

#1782 ROC-6182 defendant response link claimant dashboard
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/features/claimant-response/routes/defendants-response.ts
Labels: ns:cmc-citizen-frontend-pr-1782

#1798 ROC-5422 Part admission mediation confirmation screen
  src/main/features/response/views/confirmation/part-admission-steps.njk
  src/main/features/response/views/confirmation/part-admission.njk
  src/test/data/entity/responseData.ts
  src/test/features/response/routes/confirmation.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1798

#1794 ROC-5768 request review of directions order reconsideration
  src/main/app/claims/models/Direction.ts
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/directionOrder.ts
  src/main/app/claims/models/directionType.ts
  src/main/app/claims/models/hearingCourtType.ts
  src/main/app/claims/models/hearingDurationType.ts
  src/main/app/documents/documentsClient.ts
  src/main/features/dashboard/routes/claimant.ts
  src/main/features/dashboard/routes/defendant.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/contact-them.njk
  src/main/features/dashboard/views/defendant.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/main/features/orders/paths.ts
  src/main/features/orders/routes/receipt.ts
  src/main/modules/nunjucks/index.ts
  src/main/views/macro/addressFragment.njk
  src/test/a11y/a11y.ts
  src/test/features/dashboard/routes/claimStatus/orders.ts
  src/test/features/dashboard/routes/dashboard/orders.ts
Labels: ns:cmc-citizen-frontend-pr-1794

#1799 ROC-6201 Fix for exceptional circumstance only when YES
  src/main/features/directions-questionnaire/forms/models/exceptionalCircumstances.ts
  src/test/features/directions-questionnaire/form/models/exceptionalCircumstances.ts
  src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
Labels: ns:cmc-citizen-frontend-pr-1799

#1783 ROC-5373 Mediation claimant response bugs
  src/main/common/components/free-mediation/freeMediationCheckAndSendBlock.njk
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/response/form/models/qualifiedStatementOfTruth.ts
  src/main/features/response/form/models/statementOfTruth.ts
  src/test/features/response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1783

#1796 ROC-5989 Reconsideration dashboard
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/app/documents/documentsClient.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/main/features/orders/paths.ts
  src/test/features/dashboard/routes/claimStatus/orders.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1796

#1805 Content - phone line should be direct
  src/main/features/mediation/views/can-we-use.njk
Labels: ns:cmc-citizen-frontend-pr-1805

#1776 ROC-6170 Error when viewing repayment plan page
  src/main/common/helpers/ccjHelper.ts
  src/main/features/ccj/routes/repayment-plan-summary.ts
  src/main/features/ccj/views/repayment-plan-summary.njk
  src/test/features/ccj/routes/repayment-plan-summary.ts
Labels: ns:cmc-citizen-frontend-pr-1776

#1785 ROC-5850 DQ confirmation page
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/common/components/free-mediation/freeMediationTask.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/test/app/claims/models/claim.ts
  src/test/common/components/free-mediation/freeMediationTask.ts
  src/test/features/dashboard/routes/claimStatus/part-admission.ts
  src/test/features/dashboard/routes/dashboard/part-admission.ts
  src/test/features/dashboard/routes/dashboard/states-paid.ts
  src/test/features/dashboard/routes/index.ts
Labels: ns:cmc-citizen-frontend-pr-1785

#1814 ROC:6307: Fix review order converter bug
  src/main/app/claims/models/reviewOrder.ts
  src/main/app/claims/ordersConverter.ts
  src/test/app/claims/ordersConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1814

#1792 ROC-6221 - Claimant response task list error
  src/main/features/claimant-response/helpers/taskListBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-1792

#1810 ROC-5768 reconsideration content not showing
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/app/claims/models/directionOrder.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/test/app/claims/models/claim.ts
  src/test/features/dashboard/routes/claimStatus/orders.ts
Labels: ns:cmc-citizen-frontend-pr-1810

#1817 ROC-6311 Mediation not showing on states paid
  src/main/common/components/free-mediation/freeMediationTask.ts
  src/main/features/claimant-response/views/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1817

#1793 ROC-6235 Mediation incomplete when saying no to pilot
  src/main/common/components/free-mediation/freeMediationTask.ts
  src/main/features/mediation/routes/how-mediation-works.ts
  src/test/common/components/free-mediation/freeMediationTask.ts
Labels: ns:cmc-citizen-frontend-pr-1793

#1807 ROC-6239 Date selector white box
  src/main/public/stylesheets/components/_date-picker.scss
Labels: ns:cmc-citizen-frontend-pr-1807

#1801 Removed the word home from court select page
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/test/features/directions-questionnaire/routes/hearing-location.ts
Labels: ns:cmc-citizen-frontend-pr-1801

#1806 Content-intentiontoproceed
  src/main/features/claimant-response/views/defendants-response.njk
Labels: ns:cmc-citizen-frontend-pr-1806

#1809 ROC-6222 Objecting to chosen court
  src/main/app/court-finder/court.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/directions-questionnaire/forms/models/exceptionalCircumstances.ts
  src/main/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/main/features/directions-questionnaire/routes/hearing-location.ts
  src/main/features/directions-questionnaire/views/hearing-exceptional-circumstances.njk
  src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
Labels: ns:cmc-citizen-frontend-pr-1809

#1815 ROC-6266: Remove erroneous text under court name text box
  src/main/features/directions-questionnaire/views/hearing-location.njk
Labels: ns:cmc-citizen-frontend-pr-1815

#1816 ROC-6183 Reconsideration dashboard deadline
  src/main/app/claims/models/directionOrder.ts
  src/test/features/dashboard/routes/dashboard/orders.ts
Labels: ns:cmc-citizen-frontend-pr-1816

#1818 ROC-6256 Underline court facilities link
  src/main/features/directions-questionnaire/views/hearing-location.njk
Labels: ns:cmc-citizen-frontend-pr-1818

#1808 ROC-6238 Expert guidance content
  src/main/features/directions-questionnaire/routes/expert-guidance.ts
  src/main/features/directions-questionnaire/views/expert-guidance.njk
Labels: ns:cmc-citizen-frontend-pr-1808

#1820 ROC-6240 Statement of truth content change
  src/main/features/claim/views/check-and-send.njk
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/response/routes/check-and-send.ts
  src/main/views/macro/statementOfTruth.njk
Labels: ns:cmc-citizen-frontend-pr-1820

#1829 Fix nightly's
  Jenkinsfile_nightly
Labels: ns:cmc-citizen-frontend-pr-1829

#1819 [WIP] - ROC-6304-Hearing-Location-Serialization-Issue
  src/main/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts
  src/test/app/claims/models/directions-questionnaire/directionsQuestionnaire.ts
Labels: ns:cmc-citizen-frontend-pr-1819

#1803 ROC-6242 Claimant response try mediation
  src/main/features/mediation/routes/will-you-try-mediation.ts
  src/main/features/mediation/views/will-you-try-mediation.njk
Labels: ns:cmc-citizen-frontend-pr-1803

#1830 ROC-6303: Resolve postcode failure for dqs
  src/main/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/main/features/directions-questionnaire/views/hearing-exceptional-circumstances.njk
Labels: ns:cmc-citizen-frontend-pr-1830

#1828 ROC-6311 - States paid less than the amount mediation not showing
  src/main/features/claimant-response/views/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1828

#1833 Enable mediation pilot in demo
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/variables.tf
Labels: ns:cmc-citizen-frontend-pr-1833
