Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-09, with the labels that each got.

#1835 ROC-6359 - Review requested dashboard status
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/test/features/dashboard/routes/dashboard/orders.ts
Labels: ns:cmc-citizen-frontend-pr-1835

#1834 ROC-6249 Add timeline and evidence to defendant response check and send page
  src/main/features/response/routes/check-and-send.ts
  src/main/features/response/views/check-and-send.njk
  src/test/features/response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1834

#1836 ROC-6373 Review order respond date
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/routes/claimant.ts
  src/main/features/dashboard/routes/defendant.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/defendant.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/test/features/dashboard/routes/claimStatus/orders.ts
  src/test/features/dashboard/routes/dashboard/orders.ts
Labels: ns:cmc-citizen-frontend-pr-1836

#1800 ROC 6039 - dashboard status for parties that claim transferred to mediation service
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/claimantResponse.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-reject-with-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-reject-with-mediation.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
  src/test/features/dashboard/routes/dashboard/states-paid.ts
Labels: ns:cmc-citizen-frontend-pr-1800

#1842 ROC-6386 Keep the reason when declaring exceptional circumstances
  src/main/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
Labels: ns:cmc-citizen-frontend-pr-1842

#1840 ROC-6367: Restrict disagree reason to match backend
  src/main/app/forms/validation/validationConstraints.ts
  src/main/features/orders/form/models/disagreeReason.ts
  src/test/features/orders/form/models/disagreeReason.ts
Labels: ns:cmc-citizen-frontend-pr-1840

#1843 Enable mediation and dq in aat
  infrastructure/aat.tfvars
Labels: ns:cmc-citizen-frontend-pr-1843

#1844 Retries changed to scenario level
  src/integration-test/tests/citizen/ccj/ccj_test.ts
  src/integration-test/tests/citizen/claim/enterDetails_test.ts
  src/integration-test/tests/citizen/claim/fees_test.ts
  src/integration-test/tests/citizen/claim/payment_test.ts
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_defendant_is_business_test.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/integration-test/tests/citizen/dashboard/dashboard_test.ts
  src/integration-test/tests/citizen/defence/defence_claim_details_test.ts
  src/integration-test/tests/citizen/defence/defence_handoff_test.ts
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/defence/full_admission_test.ts
  src/integration-test/tests/citizen/defence/part_admission_test.ts
  src/integration-test/tests/citizen/endToEnd/endToend_test.ts
  src/integration-test/tests/citizen/govukAccessRoutes/respondToClaim_test.ts
  src/integration-test/tests/citizen/govukAccessRoutes/returnToClaim_test.ts
  src/integration-test/tests/citizen/offers/offers_test.ts
  src/integration-test/tests/citizen/testingSupport/testingSupport_test.ts
  types/steps-override.d.ts
Labels: ns:cmc-citizen-frontend-pr-1844

#1812 ROC-6267 Update content on check and send page
  src/main/features/response/views/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1812

#1811 ROC-6269 confirmation content
  src/main/features/response/views/confirmation/full-defence-steps.njk
  src/test/features/response/routes/confirmation.ts
Labels: ns:cmc-citizen-frontend-pr-1811

#1832 ROC-6337-claimant response error on submission
  src/main/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
Labels: ns:cmc-citizen-frontend-pr-1832

#1823 ROC-6136: DQ e2e tests
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  config/dockertests.json
  default.conf.js
  docker-compose.functional-tests.yml
  docker-compose.nightly-functional-tests.yml
  docker-compose.smoke-tests.yml
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  package.json
  src/integration-test/bootstrap/bootstrap.ts
  src/integration-test/helpers/claimStoreHelper.ts
  src/integration-test/tests/citizen/ccj/ccj_test.ts
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-check-and-send.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-task-list.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_defendant_is_business_test.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/integration-test/tests/citizen/claimantResponse/steps/defendant.ts
  src/integration-test/tests/citizen/defence/defence_claim_details_test.ts
  src/integration-test/tests/citizen/defence/defence_test.ts
  src/integration-test/tests/citizen/defence/full_admission_test.ts
  src/integration-test/tests/citizen/defence/pages/defendant-check-and-send.ts
  src/integration-test/tests/citizen/defence/pages/defendant-task-list.ts
  src/integration-test/tests/citizen/defence/part_admission_test.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/expert-reports.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/hearing-dates.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/hearing-exceptional-circumstances.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/hearing-location.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/other-wtiness.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/self-witness.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/support-required.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/using-expert.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/steps/directionsQuestionnaireSteps.ts
  src/integration-test/tests/citizen/endToEnd/data/EndToEndTestData.ts
  src/integration-test/tests/citizen/govukAccessRoutes/respondToClaim_test.ts
  src/integration-test/tests/citizen/govukAccessRoutes/returnToClaim_test.ts
  src/integration-test/tests/citizen/home/steps/defendant.ts
  src/integration-test/tests/citizen/offers/offers_test.ts
  src/integration-test/tests/citizen/testingSupport/testingSupport_test.ts
Labels: ns:cmc-citizen-frontend-pr-1823

#1821 ROC-6252 Add day to display date formater
  src/main/app/utils/momentFormatter.ts
  src/main/features/directions-questionnaire/views/components/date-list.njk
  src/main/modules/nunjucks/filters/dateFilter.ts
  src/main/modules/nunjucks/index.ts
  src/test/modules/nunjucks/filters/dateFilter.ts
Labels: ns:cmc-citizen-frontend-pr-1821

#1849 ROC-6413 Tidy date-picker integration code, for IE11 and Edge compatibility
  src/main/public/js/date-picker.js
Labels: ns:cmc-citizen-frontend-pr-1849

#1853 ROC-6413 date-picker compatibility with IE11 and Edge
  src/main/public/js/date-picker.js
Labels: ns:cmc-citizen-frontend-pr-1853

#1847 ROC-6404: Incorrect claimant dashboard status
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
Labels: ns:cmc-citizen-frontend-pr-1847

#1855 ROC-6403 Dashboard content
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
Labels: ns:cmc-citizen-frontend-pr-1855

#1851 ROC-6399 Hearing location content
  src/main/features/directions-questionnaire/views/hearing-location.njk
Labels: ns:cmc-citizen-frontend-pr-1851

#1813 ROC-6223: Update claimant dashboard as per prototype
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
Labels: ns:cmc-citizen-frontend-pr-1813

#1837 ROC-6340: Reconsideration confirmation screen
  src/main/features/orders/views/confirmation.njk
Labels: ns:cmc-citizen-frontend-pr-1837

#1852 ROC-6370 Defendant dashboard
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
Labels: ns:cmc-citizen-frontend-pr-1852

#1857 Removed ECMAScript syntactic sugar not supported in IE11
  src/main/public/js/date-picker.js
Labels: ns:cmc-citizen-frontend-pr-1857

#1856 ROC-6418 DQ offline dashboard and claim details
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
Labels: ns:cmc-citizen-frontend-pr-1856

#1860 ROC-6431 Check and send not showing mediation
  src/main/features/response/routes/response-type.ts
  src/main/features/response/views/check-and-send.njk
  src/test/features/response/routes/response-type.ts
Labels: ns:cmc-citizen-frontend-pr-1860

#1848 Release 5.0.0 in PROD
  config/dockertests.json
  infrastructure/prod.tfvars
Labels: ns:cmc-citizen-frontend-pr-1848

#1864 ROC-6412 Claimant mediation as business
  src/main/features/mediation/routes/mediation-agreement.ts
Labels: ns:cmc-citizen-frontend-pr-1864

#1861 ROC-6136 nightly DQ tests
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-check-and-send.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_defendant_is_business_test.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/pages/hearing-location.ts
  src/integration-test/tests/citizen/directionsQuestionnaire/steps/directionsQuestionnaireSteps.ts
Labels: ns:cmc-citizen-frontend-pr-1861

#1766 ROC-6037 Update address model to use max 35 character limit
  package.json
  src/main/app/forms/models/address.ts
  src/main/features/first-contact/views/claim-summary.njk
  src/main/views/macro/address.njk
  src/main/views/macro/form.njk
  src/main/views/macro/party/details.njk
  src/main/views/macro/remainingTasksFragment.njk
  src/main/views/macro/table.njk
  src/main/views/macro/task-list.njk
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1766

#1721 ROC-5077: Remove paid in full feature toggle
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/dockertests.json
  config/mocha.json
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/prod.tfvars
  src/main/app.ts
  src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1721, pinned

#1866 ROC-6452 Only show intention to proceed to new claims
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/data/entity/fullDefenceData.ts
  src/test/data/entity/settlement.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1866

#1870 ROC-6452 Hide intention to proceed for older claims
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
Labels: ns:cmc-citizen-frontend-pr-1870

#1694 ROC-5845 Increase bodyparser payload limit to 10MB
  src/main/app.ts
  src/main/app/forms/models/timeline.ts
  src/main/public/js/append-row.js
  src/test/app/forms/models/timeline.ts
Labels: ns:cmc-citizen-frontend-pr-1694

#1871 ROC-6453 Mediation status for over £300
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/features/dashboard/routes/dashboard/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1871

#1872 ROC-6454 Part admit mediation dashboard
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/test/features/dashboard/routes/dashboard/part-admission.ts
Labels: ns:cmc-citizen-frontend-pr-1872

#1839 ROC-6249: Show timeline and evidence sections even when empty (defendant response)
  src/main/features/response/views/check-and-send.njk
  src/test/features/response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1839

#1874 ROC 6387 claim status page h2 incorrect size
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/admissionByCCJDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/breachOfPaymentDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjEligible.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmissionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/claimantResponse.njk
  src/main/features/dashboard/views/macro/claimStatus/moreTimeRequested.njk
  src/main/features/dashboard/views/macro/claimStatus/noReponse.njk
  src/main/features/dashboard/views/macro/claimStatus/offerAccepted.njk
  src/main/features/dashboard/views/macro/claimStatus/offerRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/offerSettlement.njk
  src/main/features/dashboard/views/macro/claimStatus/offerSubmitted.njk
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
Labels: ns:cmc-citizen-frontend-pr-1874

#1863 ROC-6410: Remove word default from CCJ line
  src/main/features/claim/views/confirmation.njk
  src/main/features/dashboard/views/macro/claimStatus/moreTimeRequested.njk
  src/main/features/dashboard/views/macro/claimStatus/noReponse.njk
  src/main/features/dashboard/views/status/claimant/claim_issued.njk
  src/main/features/dashboard/views/status/claimant/no-response.njk
  src/test/features/dashboard/routes/claimStatus/claim-issue.ts
  src/test/features/dashboard/routes/dashboard/claim-issue.ts
  src/test/features/dashboard/routes/index.ts
Labels: ns:cmc-citizen-frontend-pr-1863

#1877 update dashboard check to correct text
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
Labels: ns:cmc-citizen-frontend-pr-1877

#1868 ROC-6458 - Mediation check-and-send claimant response
  src/main/features/claimant-response/views/check-and-send.njk
Labels: ns:cmc-citizen-frontend-pr-1868

#1708 ROC-5858 Change to new survey links
  infrastructure/main.tf
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/ccj/views/confirmation-redetermination.njk
  src/main/features/claim/views/confirmation.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/offer/views/accepted.njk
  src/main/features/offer/views/offer-confirmation.njk
  src/main/features/offer/views/rejected.njk
  src/main/features/offer/views/settled.njk
  src/main/features/paid-in-full/views/confirmation.njk
  src/main/features/response/views/confirmation.njk
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
  src/main/views/includes/service-survey-link-claimant.njk
  src/main/views/includes/service-survey-link-defendant.njk
Labels: ns:cmc-citizen-frontend-pr-1708

#1838 ROC 6081 Remove title and add total claim amount text
  src/main/features/claim/views/total.njk
  src/test/features/claim/routes/total.ts
Labels: ns:cmc-citizen-frontend-pr-1838, stale

#1850 ROC-6254: Update submit button text for eligibility journey
  src/main/features/eligibility/views/claim-is-for-tenancy-deposit.njk
  src/main/features/eligibility/views/claim-type.njk
  src/main/features/eligibility/views/claim-value.njk
  src/main/features/eligibility/views/claimant-address.njk
  src/main/features/eligibility/views/defendant-address.njk
  src/main/features/eligibility/views/defendant-age.njk
  src/main/features/eligibility/views/government-department.njk
  src/main/features/eligibility/views/help-with-fees.njk
  src/main/features/eligibility/views/over-18.njk
  src/main/features/eligibility/views/single-defendant.njk
Labels: ns:cmc-citizen-frontend-pr-1850, stale

#1831 ROC-6268: Update defendant details pages
  src/main/features/claim/views/defendant-individual-details.njk
  src/main/features/claim/views/defendant-sole-trader-details.njk
Labels: ns:cmc-citizen-frontend-pr-1831, stale

#1865 ROC-6443 Contact person length
  src/main/app/forms/models/companyDetails.ts
  src/main/app/forms/models/organisationDetails.ts
  src/test/app/forms/models/companyDetails.ts
  src/test/app/forms/models/organisationDetails.ts
Labels: ns:cmc-citizen-frontend-pr-1865

#1869 update infrastructure module
  infrastructure/main.tf
Labels: ns:cmc-citizen-frontend-pr-1869

#1859 ROC-6270 Can we use radio buttons inline
  src/main/features/mediation/views/can-we-use.njk
Labels: ns:cmc-citizen-frontend-pr-1859

#1882 Revert content and design of the 'New Features' page
  src/main/features/claim/views/new-features-consent.njk
  src/test/features/claim/routes/new-features-consent.ts
Labels: ns:cmc-citizen-frontend-pr-1882
