Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-03, with the labels that each got.

#1455 ROC-5033: Add court determination Instalments/Instalments scenario
  Jenkinsfile_nightly
  bin/run-nightly-tests.sh
  docker-compose.nightly-functional-tests.yml
  package.json
  src/integration-test/tests/citizen/claimantResponse/data/ClaimantResponseTestData.ts
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-court-offered-instalments.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/integration-test/tests/citizen/defence/full_admission_test.ts
  src/integration-test/tests/citizen/defence/pages/statement-of-means/monthlyIncome.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/integration-test/tests/citizen/defence/steps/statementOfMeans.ts
  src/integration-test/tests/citizen/endToEnd/steps/helper.ts
Labels: ns:cmc-citizen-frontend-pr-1455

#1443 ROC - 5176: ccj repaymentplan not showing
  src/main/views/macro/paymentPlanTable.njk
Labels: ns:cmc-citizen-frontend-pr-1443

#1460 ROC-5033:Nightly pipeline
  Jenkinsfile_nightly
  docker-compose.functional-tests.yml
  docker-compose.nightly-functional-tests.yml
Labels: ns:cmc-citizen-frontend-pr-1460

#1464 Remove trailing slash from nightly test_url
  Jenkinsfile_nightly
Labels: ns:cmc-citizen-frontend-pr-1464

#1466 Change nightly to run everything
  docker-compose.functional-tests.yml
  docker-compose.nightly-functional-tests.yml
  docker-compose.smoke-tests.yml
  src/integration-test/tests/citizen/claim/enterDetails_test.ts
Labels: ns:cmc-citizen-frontend-pr-1466

#1473 Update afterCheckout statement in jenkinsfile
  Jenkinsfile_CNP
Labels: ns:cmc-citizen-frontend-pr-1473

#1476 Increase nightly run timeout
  Jenkinsfile_nightly
Labels: ns:cmc-citizen-frontend-pr-1476

#1428 ROC 5230 sole trader statement of truth undo position changes
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/app/claims/models/details/theirs/theirDetails.ts
  src/main/app/forms/models/partyDetails.ts
  src/main/features/claim/routes/check-and-send.ts
  src/main/features/claim/views/check-and-send.njk
  src/main/features/response/routes/check-and-send.ts
  src/test/app/claims/models/details/theirs/theirDetails.ts
  src/test/features/claim/routes/check-and-send.ts
  src/test/features/response/routes/check-and-send.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1428

#1475 Update @types/lodash
  package.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1475

#1251 ROC-4889 e2e Full admission with Repayment plan - claimant suggest counter repayment plan & settles
  src/integration-test/tests/citizen/claimantResponse/data/ClaimantResponseTestData.ts
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/pages/claimant-settle-claim.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
Labels: ns:cmc-citizen-frontend-pr-1251

#1468 ROC-4699-Route Test with possible combination of Claimant | Defendant
  src/test/data/draft/partyDetails.ts
  src/test/data/entity/party.ts
  src/test/features/claim/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1468

#1484 Update dependancy @Types/jsonwebtoken
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1484

#1483 Preparing for new AKS AAT environment
  Jenkinsfile_CNP
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.aat.template.yaml
  charts/cmc-citizen-frontend/values.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1483

#1465 Fix aseName to not use remote state
  infrastructure/main.tf
  infrastructure/state.tf
Labels: ns:cmc-citizen-frontend-pr-1465

#1454 ROC-5133 Under-18 defendant hand-off page
  src/main/features/response/paths.ts
  src/main/features/response/routes/eligibility/under-18.ts
  src/main/features/response/routes/your-dob.ts
  src/main/features/response/views/eligibility/under-18.njk
  src/main/views/macro/support.njk
  src/test/features/response/routes/eligibility/under-18.ts
  src/test/features/response/routes/your-dob.ts
Labels: ns:cmc-citizen-frontend-pr-1454

#1496 Update nodejs-healthcheck
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1496

#1500 ROC-5133 Do not redirect to under 18 page
  src/main/features/response/routes/your-dob.ts
  src/test/features/response/routes/your-dob.ts
Labels: ns:cmc-citizen-frontend-pr-1500

#1469 ROC-5351: £10k claim should redirect to eligibility page
  src/main/features/claim/paths.ts
  src/main/features/claim/views/amount-exceeded.njk
  src/test/features/claim/routes/amount-exceeded.ts
Labels: ns:cmc-citizen-frontend-pr-1469

#1413 ROC-4300 Allow defendants to declare they paid more than the claim amount
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/app/claims/models/paymentDeclaration.ts
  src/main/app/claims/responseModelConverter.ts
  src/main/features/claimant-response/views/defendants-response.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmissionStatesPaidAccepted.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidAccepted.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/main/features/response/routes/full-rejection/how-much-have-you-paid.ts
  src/test/app/claims/models/claim.ts
  src/test/data/entity/responseData.ts
  src/test/features/claimant-response/routes/defendants-response.ts
  src/test/features/response/routes/full-rejection/how-much-have-you-paid.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1413

#1485 ROC-5002 filter tests
  src/test/features/claimant-response/filters/age-group-type-view-filter.ts
  src/test/features/claimant-response/filters/bank-account-type-view-filter.ts
  src/test/features/claimant-response/filters/expense-type-view-filter.ts
  src/test/features/claimant-response/filters/frequency-view-filter.ts
  src/test/features/claimant-response/filters/income-type-view-filter.ts
  src/test/features/claimant-response/filters/monthly-amount-view-filter.ts
  src/test/features/claimant-response/filters/payment-schedule-type-view-filter.ts
  src/test/features/claimant-response/filters/priority-debt-type-view-filter.ts
  src/test/features/claimant-response/filters/renderFormaliseRepaymentPlanOption.ts
  src/test/features/claimant-response/filters/residence-type-view-filter.ts
  src/test/features/claimant-response/filters/yes-no-view-filter.ts
  src/test/modules/nunjucks/filters/monthlyAmountViewFilter.ts
  src/test/modules/nunjucks/filters/priorityDebtsTypeViewFilter.ts
Labels: ns:cmc-citizen-frontend-pr-1485

#1503 ROC 4889 overnight e2e test fix
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
Labels: ns:cmc-citizen-frontend-pr-1503

#1459 ROC-4696 Replace anchor links with macros
  src/main/common/components/ccj/paid-amount-summary.njk
  src/main/features/claim/views/confirmation.njk
  src/main/features/claim/views/macro/about-claim-widget.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjEligible.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/moreTimeRequested.njk
  src/main/features/dashboard/views/macro/claimStatus/noReponse.njk
  src/main/features/dashboard/views/macro/claimStatus/offerSubmitted.njk
  src/main/features/dashboard/views/macro/claimStatus/utilityMacros.njk
  src/main/features/eligibility/views/eligible.njk
  src/main/features/eligibility/views/index.njk
  src/main/features/eligibility/views/mcol-eligibility.njk
  src/main/features/first-contact/views/access-denied.njk
  src/main/features/first-contact/views/claim-summary.njk
  src/main/features/first-contact/views/start.njk
  src/main/features/offer/views/accepted.njk
  src/main/features/offer/views/countersign-agreement.njk
  src/main/features/offer/views/make-agreement.njk
  src/main/features/offer/views/offer-confirmation.njk
  src/main/features/offer/views/rejected.njk
  src/main/features/offer/views/settle-out-of-court.njk
  src/main/features/offer/views/settled.njk
  src/main/features/paid-in-full/views/confirmation.njk
  src/main/features/response/views/claim-details.njk
  src/main/features/response/views/confirmation.njk
  src/main/features/response/views/confirmation/full-defence-steps.njk
  src/main/features/response/views/task-list.njk
  src/main/features/testing-support/views/index.njk
  src/main/modules/nunjucks/index.ts
  src/main/views/forbidden.njk
  src/main/views/govukTemplate.njk
  src/main/views/includes/language-link.njk
  src/main/views/includes/propositional_navigation.njk
  src/main/views/includes/report_problem_link.njk
  src/main/views/includes/support-links.njk
  src/main/views/macro/internalLink.njk
  src/main/views/not-found.njk
Labels: ns:cmc-citizen-frontend-pr-1459

#1507 ROC-5625 Add route tests for claim issued and admissions, and fix UI bug
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
  src/test/data/entity/responseData.ts
  src/test/features/dashboard/routes/index.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1507

#1501 ROC-5133 Redirect to hand off page if under 18
  src/main/features/response/routes/your-dob.ts
  src/test/features/response/routes/your-dob.ts
Labels: ns:cmc-citizen-frontend-pr-1501

#1482 ROC-5241 Defendant Hearing - Choose a hearing location - postcode lookup
  src/main/app/court-finder/address.ts
  src/main/app/court-finder/court.ts
  src/main/app/court-finder/courtFinderClient.ts
  src/main/app/court-finder/courtFinderResponse.ts
  src/main/app/court-finder/spoe.ts
  src/test/app/court-finder/courtFinderClient.ts
  tsconfig.json
Labels: ns:cmc-citizen-frontend-pr-1482

#1481 ROC-5258 Refactor claim issue dashboard
  package.json
  src/main/features/dashboard/helpers/claimStatusFlow.ts
  src/main/features/dashboard/index.ts
  src/main/features/dashboard/views/index.njk
  src/main/features/dashboard/views/status/claimant/claim_issued.njk
  src/main/features/dashboard/views/status/defendant/claim_issued.njk
  src/test/features/dashboard/helpers/claimStatusFlow.ts
  tslint.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1481

#1491 ROC-5170 company contact
  src/main/features/mediation/views/can-we-use-company.njk
  src/main/features/mediation/views/can-we-use.njk
Labels: ns:cmc-citizen-frontend-pr-1491

#1514 Update jenkinsfiles with new secrets format
  Jenkinsfile_nightly
  Jenkinsfile_parameterized
Labels: ns:cmc-citizen-frontend-pr-1514

#1517 Content - fixed typo
  src/main/features/claim/views/total.njk
Labels: ns:cmc-citizen-frontend-pr-1517

#1508 Feature/add liveness check
  charts/cmc-citizen-frontend/requirements.yaml
  package.json
  src/main/routes/health.ts
  src/test/routes/health-checks.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1508

#1518 ROC-5368: fix helm tag typo
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/values.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1518

#1522 Fix nightly cross-browser test
  package.json
Labels: ns:cmc-citizen-frontend-pr-1522

#1477 ROC-5260 - Error when defendant opens repayment plan
  src/main/app/claims/ccjModelConverter.ts
  src/main/app/claims/models/settlement.ts
Labels: ns:cmc-citizen-frontend-pr-1477

#1512 ROC-5425 Paper response content update
  src/main/features/response/views/eligibility/send-your-response-by-email.njk
Labels: ns:cmc-citizen-frontend-pr-1512

#1492 ROC 5240 directions questionnaire feature toggle and dashboard
  charts/cmc-citizen-frontend/values.template.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/dockertests.json
  config/mocha.json
  infrastructure/main.tf
  infrastructure/variables.tf
  src/main/app.ts
  src/main/app/utils/claimFeatureToggles.ts
  src/main/common/clients/featureTogglesClient.ts
  src/main/features/claim/routes/pay.ts
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/claimant-response/routes/task-list.ts
  src/main/features/claimant-response/tasks/detailsInCaseOfHearingTask.ts
  src/main/features/claimant-response/views/task-list.njk
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/guard/directionsQuestionnaireGuard.ts
  src/main/features/directions-questionnaire/index.ts
  src/main/features/directions-questionnaire/paths.ts
  src/main/features/directions-questionnaire/routes/hearing-location.ts
  src/main/features/response/guards/partialAdmissionGuard.ts
  src/main/features/response/helpers/statementOfMeansFeature.ts
  src/main/features/response/helpers/taskListBuilder.ts
  src/main/features/response/routes/check-and-send.ts
  src/main/features/response/routes/evidence.ts
  src/main/features/response/routes/free-mediation.ts
  src/main/features/response/routes/full-rejection/how-much-have-you-paid.ts
  src/main/features/response/routes/task-list.ts
  src/main/features/response/routes/timeline.ts
  src/main/features/response/tasks/detailsInCaseOfHearingTask.ts
  src/main/features/response/views/task-list.njk
  src/test/common/clients/featureTogglesClient.ts
  src/test/features/claimant-response/helpers/taskListBuilder.ts
  src/test/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/test/features/response/helpers/taskListBuilder.ts
  tsconfig.json
Labels: ns:cmc-citizen-frontend-pr-1492

#1393 ROC-5078: Dashboard unit tests
  src/test/data/entity/responseData.ts
  src/test/features/dashboard/routes/index.ts
  src/test/features/response/routes/more-time-request.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1393

#1433 ROC 4838 update court calculation with 2019 2020 allowances
  src/main/app/common/allowances/allowance.ts
  src/main/app/common/allowances/allowanceRepository.ts
  src/main/resources/meansAllowance.json
  src/test/app/common/statement-of-means/statementOfMeansCalculations.ts
  src/test/data/entity/sampleAllowanceData.json
Labels: ns:cmc-citizen-frontend-pr-1433

#1470 ROC-5345: Fixing bug for repayment plan showing up for claimant
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/test/features/claimant-response/routes/check-and-send.ts
  src/test/features/claimant-response/routes/payment-date.ts
  src/test/http-mocks/claim-store.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1470

#1523 ROC-5349: Defendant loop when part admit claim is rejected
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/test/app/claims/models/claim.ts
  src/test/data/entity/responseData.ts
  src/test/features/dashboard/routes/index.ts
Labels: ns:cmc-citizen-frontend-pr-1523

#1533 Fix dashboard route tests
  src/test/features/dashboard/routes/index.ts
Labels: ns:cmc-citizen-frontend-pr-1533

#1493 ROC-5059: Add mediationPhoneNumber to defendant response converter
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/models/response/responseCommon.ts
  src/main/app/claims/responseModelConverter.ts
  src/main/features/response/routes/check-and-send.ts
  src/test/app/claims/responseModelConverter.ts
  src/test/data/entity/responseData.ts
  src/test/features/mediation/routes/can-we-use-company.ts
  src/test/features/mediation/routes/can-we-use.ts
  src/test/features/mediation/routes/mediation-agreement.ts
  src/test/features/mediation/routes/will-you-try-mediation.ts
  src/test/features/response/routes/check-and-send.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1493

#1536 Fix pipeline with SIDAM
  Jenkinsfile_CNP
Labels: ns:cmc-citizen-frontend-pr-1536

#1495 ROC-5243 - Defendant Hearing - Do you want witnesses to give evidence?
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/forms/models/otherWitnesses.ts
  src/main/features/directions-questionnaire/forms/models/selfWitness.ts
  src/main/features/directions-questionnaire/paths.ts
  src/main/features/directions-questionnaire/routes/other-witnesses.ts
  src/main/features/directions-questionnaire/routes/self-witness.ts
  src/main/features/directions-questionnaire/views/other-witnesses.njk
  src/main/features/directions-questionnaire/views/self-witness.njk
  src/test/features/directions-questionnaire/form/models/otherWitnesses.ts
  src/test/features/directions-questionnaire/form/models/selfWitness.ts
  src/test/features/directions-questionnaire/routes/otherWitnesses.ts
  src/test/features/directions-questionnaire/routes/selfWitness.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1495

#1527 ROC-5437 Extract date from claim response
  src/main/features/dashboard/index.ts
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1527

#1526 Feature/ROC-5382 update ccj confirmation page
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjEligible.njk
Labels: ns:cmc-citizen-frontend-pr-1526

#1531 ROC-4944 - Task List - make the blank not-completed status a call to action
  package.json
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1531

#1524 ROC-5316: Hearing - Individual Choose a hearing location
  src/main/app/drafts/draft-data/claimDraft.ts
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/forms/models/exceptionalCircumstances.ts
  src/main/features/directions-questionnaire/forms/models/hearingLocation.ts
  src/main/features/directions-questionnaire/guard/exceptionalCircumstancesGuard.ts
  src/main/features/directions-questionnaire/helpers/directionsQuestionnaireHelper.ts
  src/main/features/directions-questionnaire/index.ts
  src/main/features/directions-questionnaire/paths.ts
  src/main/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/main/features/directions-questionnaire/routes/hearing-location.ts
  src/main/features/directions-questionnaire/views/hearing-exceptional-circumstances.njk
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/main/features/response/helpers/taskListBuilder.ts
  src/test/features/directions-questionnaire/form/models/exceptionalCircumstances.ts
  src/test/features/directions-questionnaire/form/models/hearingLocation.ts
  src/test/features/directions-questionnaire/helpers/directionsQuestionnaireHelper.ts
  src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/test/features/directions-questionnaire/routes/hearing-location.ts
  src/test/features/directions-questionnaire/routes/helper/dqRouteHelper.ts
  src/test/features/directions-questionnaire/routes/otherWitnesses.ts
  src/test/features/directions-questionnaire/routes/selfWitness.ts
  src/test/http-mocks/court-finder-client.ts
Labels: ns:cmc-citizen-frontend-pr-1524

#1547 Bug - Fix route test date mishap and unblock pipeline
  src/test/features/claim/routes/claimant-dob.ts
Labels: ns:cmc-citizen-frontend-pr-1547
