Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-05, with the labels that each got.

#1585 ROC-5436: Tell us you've been paid button
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1585

#1610 Remove explicit Azure Provider version
  infrastructure/main.tf
Labels: ns:cmc-citizen-frontend-pr-1610

#1612 ROC-4116 Cross browser test fix
  saucelabs.conf.js
  src/integration-test/helpers/saucelabsReporter.js
Labels: ns:cmc-citizen-frontend-pr-1612

#1589 ROC-5581: update config ready for SIDAM images in local env
  config/default.json
Labels: ns:cmc-citizen-frontend-pr-1589

#1616 Update saucelabsReporter.js
  src/integration-test/helpers/saucelabsReporter.js
Labels: ns:cmc-citizen-frontend-pr-1616

#1581 ROC-5355 mediation content changes for pilot
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/dockertests.json
  config/mocha.json
  src/main/features/mediation/routes/free-mediation.ts
  src/main/features/mediation/routes/how-mediation-works.ts
  src/main/features/mediation/views/free-mediation.njk
  src/main/features/mediation/views/how-mediation-works.njk
  src/test/features/mediation/routes/free-mediation.ts
  src/test/features/mediation/routes/how-mediation-works.ts
  src/test/features/mediation/routes/mediation-agreement.ts
Labels: ns:cmc-citizen-frontend-pr-1581

#1378 Update request-promise-native
  config/mocha.json
  src/integration-test/bootstrap/bootstrap.ts
  src/integration-test/helpers/claimStoreHelper.ts
  src/integration-test/helpers/clients/claimStoreClient.ts
  src/integration-test/helpers/clients/idamClient.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/offerClient.ts
  src/main/app/claims/settlementAgreementClient.ts
  src/main/app/documents/documentsClient.ts
  src/main/app/fees/feesClient.ts
  src/main/app/idam/idamClient.ts
  src/main/app/pay/payClient.ts
  src/main/features/testing-support/routes/update-response-deadline.ts
  src/test/common/errorHandling.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1378

#1621 Merge req native promise into ithc
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/dockertests.json
  config/mocha.json
  infrastructure/main.tf
  package.json
  saucelabs.conf.js
  src/integration-test/bootstrap/bootstrap.ts
  src/integration-test/helpers/claimStoreHelper.ts
  src/integration-test/helpers/clients/claimStoreClient.ts
  src/integration-test/helpers/clients/idamClient.ts
  src/integration-test/helpers/saucelabsReporter.js
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/offerClient.ts
  src/main/app/claims/settlementAgreementClient.ts
  src/main/app/documents/documentsClient.ts
  src/main/app/fees/feesClient.ts
  src/main/app/idam/idamClient.ts
  src/main/app/pay/payClient.ts
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
  src/main/features/mediation/routes/free-mediation.ts
  src/main/features/mediation/routes/how-mediation-works.ts
  src/main/features/mediation/views/free-mediation.njk
  src/main/features/mediation/views/how-mediation-works.njk
  src/main/features/testing-support/routes/update-response-deadline.ts
  src/test/common/errorHandling.ts
  src/test/features/mediation/routes/free-mediation.ts
  src/test/features/mediation/routes/how-mediation-works.ts
  src/test/features/mediation/routes/mediation-agreement.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1621

#1622 Update saucelabsReporter.js
  Jenkinsfile_nightly
Labels: ns:cmc-citizen-frontend-pr-1622

#1623 SPROD prep for performance testing
  infrastructure/sprod.tfvars
Labels: ns:cmc-citizen-frontend-pr-1623

#1629 ROC-5530 defendant part admission dashboard
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/test/data/entity/claimantResponseData.ts
  src/test/features/dashboard/routes/index.ts
Labels: ns:cmc-citizen-frontend-pr-1629

#1633 ROC-5628 GA event not triggering
  src/main/views/macro/internalLink.njk
Labels: ns:cmc-citizen-frontend-pr-1633

#1635 ROC-5634 claimant claim details wrong for rejected settlement agreement
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
Labels: ns:cmc-citizen-frontend-pr-1635

#1558 ROC-5504 refactor full defence dashboard
  charts/cmc-citizen-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/development.json
  config/dockertests.json
  config/mocha.json
  infrastructure/main.tf
  infrastructure/variables.tf
  package.json
  src/main/app/claims/models/claim-states/actor-type.ts
  src/main/app/claims/models/claim-states/full-defence-states.ts
  src/main/app/claims/models/claim-states/initial-states.ts
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimTemplate.ts
  src/main/features/dashboard/claims-state-machine/claim-state.ts
  src/main/features/dashboard/claims-state-machine/full-defence-transitions.ts
  src/main/features/dashboard/claims-state-machine/initial-transitions.ts
  src/main/features/dashboard/routes/index.ts
  src/main/features/dashboard/views/index.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-already-paid-accept.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-already-paid-reject.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-already-paid.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-made-agreement-with-mediation.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-made-agreement-without-mediation.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-reject-with-mediation.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-reject-without-mediation.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-settled-with-agreement.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-settlement-offer-reject-with-mediation.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-settlement-offer-reject-without-mediation.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-settlement-offer-with-mediation.njk
  src/main/features/dashboard/views/status/claimant/full-defence/fd-settlement-offer-without-mediation.njk
  src/main/features/dashboard/views/status/claimant/init.njk
  src/main/features/dashboard/views/status/claimant/no-response-past-deadline.njk
  src/main/features/dashboard/views/status/claimant/no-response.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-already-paid-accept.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-already-paid-reject.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-already-paid.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-made-agreement-with-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-made-agreement-without-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-reject-with-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-reject-without-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-settled-with-agreement.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-settlement-offer-reject-with-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-settlement-offer-reject-without-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-settlement-offer-with-mediation.njk
  src/main/features/dashboard/views/status/defendant/full-defence/fd-settlement-offer-without-mediation.njk
  src/main/features/dashboard/views/status/defendant/init.njk
  src/main/features/dashboard/views/status/defendant/no-response-past-deadline.njk
  src/main/features/dashboard/views/status/defendant/no-response.njk
  src/main/features/mediation/routes/mediation-agreement.ts
  src/test/features/dashboard/claims-state-machine/full-defence-transitions.ts
  src/test/features/dashboard/claims-state-machine/initial-transitions.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1558

#1646 ROC-5615 remove CCJ document download code
  src/main/app/documents/documentsClient.ts
  src/main/features/claimant-response/routes/receipt.ts
Labels: ns:cmc-citizen-frontend-pr-1646

#1606 ROC-5567 settlement dashboard tests
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/claimStatus/offerAccepted.njk
  src/test/app/claims/models/claim.ts
  src/test/data/entity/settlement.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/settlement.ts
  src/test/features/dashboard/routes/dashboard/settlement.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1606

#1627 ROC-5242 Expert required page
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/forms/models/expertRequired.ts
  src/main/features/directions-questionnaire/routes/expert.ts
  src/main/features/directions-questionnaire/views/expert.njk
  src/main/features/directions-questionnaire/views/hearing-exceptional-circumstances.njk
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/main/features/directions-questionnaire/views/other-witnesses.njk
  src/main/features/directions-questionnaire/views/self-witness.njk
  src/test/a11y/a11y.ts
  src/test/a11y/mocks.ts
  src/test/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/test/features/directions-questionnaire/form/models/expertRequired.ts
  src/test/features/directions-questionnaire/routes/expert.ts
Labels: ns:cmc-citizen-frontend-pr-1627

#1647 ROC-4116 jink
  Jenkinsfile_nightly
  package.json
  saucelabs.conf.js
  src/integration-test/helpers/saucelabsReporter.js
Labels: ns:cmc-citizen-frontend-pr-1647

#1641 ROC 5572 ask court permission to hire expert
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/forms/models/permissionForExpert.ts
  src/main/features/directions-questionnaire/paths.ts
  src/main/features/directions-questionnaire/routes/expert-guidance.ts
  src/main/features/directions-questionnaire/routes/permission-for-expert.ts
  src/main/features/directions-questionnaire/views/permission-for-expert.njk
  src/test/features/directions-questionnaire/form/models/permissionForExpert.ts
  src/test/features/directions-questionnaire/routes/expert-guidance.ts
  src/test/features/directions-questionnaire/routes/permission-for-expert.ts
Labels: ns:cmc-citizen-frontend-pr-1641

#1652 use default CPU requests
  charts/cmc-citizen-frontend/values.yaml
Labels: ns:cmc-citizen-frontend-pr-1652

#1640 ROC-5648 states paid dashboard issue
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1640

#1655 Use correct variable name for nightlys - as specified in docker-compose files
  Jenkinsfile_nightly
Labels: ns:cmc-citizen-frontend-pr-1655

#1662 Add another missing env var for nightly
  Jenkinsfile_nightly
Labels: ns:cmc-citizen-frontend-pr-1662

#1660 ROC-5701 Claimant accepts business admission
  src/main/app/claims/models/claim.ts
  src/main/features/ccj/guards/ccjGuard.ts
  src/main/features/ccj/routes/check-and-send.ts
  src/main/features/ccj/routes/paid-amount-summary.ts
  src/main/features/ccj/views/check-and-send.njk
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
  src/test/features/ccj/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1660

#1430 ROC-5168 Updating case number on PayHub
  codecov.yml
  package.json
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/models/claim.ts
  src/main/app/mocks/mockPayClient.ts
  src/main/app/pay/payClient.ts
  src/main/features/claim/routes/pay.ts
  src/test/features/claim/routes/pay.ts
  src/test/http-mocks/claim-store.ts
  src/test/http-mocks/pay.ts
  tsconfig.json
Labels: ns:cmc-citizen-frontend-pr-1430
