Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-04, with the labels that each got.

#1546 Fix e2e picking up 'INCOMPLETE' task as 'COMPLETE'
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
Labels: ns:cmc-citizen-frontend-pr-1546

#1545 Helm chart changes: feature-toggle-importer
  Jenkinsfile_CNP
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1545

#1525 ROC-5245 - Hearing - any support required for hearing?
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/forms/models/supportRequired.ts
  src/main/features/directions-questionnaire/helpers/directionsQuestionnaireHelper.ts
  src/main/features/directions-questionnaire/paths.ts
  src/main/features/directions-questionnaire/routes/support-required.ts
  src/main/features/directions-questionnaire/views/other-witnesses.njk
  src/main/features/directions-questionnaire/views/support-required.njk
  src/main/features/response/views/statement-of-means/monthly-expenses.njk
  src/main/features/response/views/statement-of-means/monthly-income.njk
  src/main/features/response/views/statement-of-means/priority-debts.njk
  src/main/views/expandable-checkbox-option-scripts.njk
  src/main/views/includes/scripts.njk
  src/main/views/macro/expandableCheckboxOption.njk
  src/test/features/directions-questionnaire/form/models/supportRequired.ts
  src/test/features/directions-questionnaire/routes/support-required.ts
Labels: ns:cmc-citizen-frontend-pr-1525

#1553 ROC-5347 track non javascript
  src/main/public/img/misc/noJS.png
  src/main/views/includes/scripts.njk
Labels: ns:cmc-citizen-frontend-pr-1553

#1554 ROC-5373 Set up e2e page objects and steps
  src/integration-test/tests/citizen/mediation/pages/can-we-use-company.ts
  src/integration-test/tests/citizen/mediation/pages/can-we-use.ts
  src/integration-test/tests/citizen/mediation/pages/free-mediation.ts
  src/integration-test/tests/citizen/mediation/pages/how-mediation-works.ts
  src/integration-test/tests/citizen/mediation/pages/mediation-agreement.ts
  src/integration-test/tests/citizen/mediation/pages/will-you-try-mediation.ts
  src/integration-test/tests/citizen/mediation/steps/mediation.ts
Labels: ns:cmc-citizen-frontend-pr-1554

#1538 ROC-4855: part admit already paid (duplicate)
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmissionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/test/features/dashboard/routes/index.ts
Labels: ns:cmc-citizen-frontend-pr-1538

#1556 ROC-5373 - Intention to proceed page
  src/main/features/claimant-response/draft/draftClaimantResponse.ts
  src/main/features/claimant-response/form/models/intentionToProceed.ts
  src/main/features/claimant-response/paths.ts
  src/main/features/claimant-response/routes/intention-to-proceed.ts
  src/main/features/claimant-response/tasks/intentionToProceedTask.ts
  src/main/features/claimant-response/views/intention-to-proceed.njk
  src/test/features/claimant-response/form/models/intentionToProceed.ts
  src/test/features/claimant-response/routes/intention-to-proceed.ts
  src/test/features/claimant-response/tasks/intentionToProceedTask.ts
Labels: ns:cmc-citizen-frontend-pr-1556

#1513 ROC-4699 Claim check-and-send route tests
  src/test/data/draft/partyDetails.ts
  src/test/data/entity/party.ts
  src/test/features/claim/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1513

#1552 ROC-5325 error when primary debt contains two week or four week reference
  src/main/app/common/frequency/frequency.ts
  src/test/app/common/frequency/frequency.ts
  src/test/app/common/payment-plan/paymentPlan.ts
  src/test/features/claimant-response/filters/frequency-view-filter.ts
Labels: ns:cmc-citizen-frontend-pr-1552

#1564 ROC-5373 Claimant response mediation
  src/main/common/components/free-mediation/freeMediationCheckAndSendBlock.njk
  src/main/common/components/free-mediation/freeMediationTask.ts
  src/main/features/mediation/form/models/CanWeUseCompany.ts
  src/main/features/mediation/routes/free-mediation.ts
  src/main/features/mediation/routes/will-you-try-mediation.ts
  src/main/features/mediation/views/can-we-use.njk
  src/main/features/mediation/views/free-mediation.njk
  src/main/features/mediation/views/will-you-try-mediation.njk
  src/test/common/components/free-mediation/freeMediationTask.ts
Labels: ns:cmc-citizen-frontend-pr-1564

#1543 ROC-5244 Declare dates you can't attend a hearing
  gulpfile.js
  package.json
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/claimant-response/tasks/detailsInCaseOfHearingTask.ts
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/forms/models/availability.ts
  src/main/features/directions-questionnaire/forms/validators/availabilityDatesValidator.ts
  src/main/features/directions-questionnaire/paths.ts
  src/main/features/directions-questionnaire/routes/hearing-dates-picker.ts
  src/main/features/directions-questionnaire/routes/hearing-dates.ts
  src/main/features/directions-questionnaire/routes/other-witnesses.ts
  src/main/features/directions-questionnaire/views/components/date-list.njk
  src/main/features/directions-questionnaire/views/hearing-dates.njk
  src/main/features/testing-support/views/delete-drafts.njk
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
  src/main/modules/nunjucks/index.ts
  src/main/public/img/date-picker/date_disabled.png
  src/main/public/img/date-picker/next_arrow.png
  src/main/public/img/date-picker/prev_arrow.png
  src/main/public/js/date-picker.js
  src/main/public/stylesheets/application.scss
  src/main/public/stylesheets/components/_colours.scss
  src/main/public/stylesheets/components/_date-picker.scss
  src/main/views/govukTemplate.njk
  src/main/views/includes/scripts.njk
  src/test/features/directions-questionnaire/form/models/availability.ts
  src/test/features/directions-questionnaire/routes/hearing-dates-picker.ts
  src/test/features/directions-questionnaire/routes/hearing-dates.ts
  src/test/features/directions-questionnaire/routes/otherWitnesses.ts
  src/test/features/offer/routes/settle-out-of-court.ts
  src/test/http-mocks/draft-store.ts
  src/test/localDateUtils.ts
  src/test/routes/expectations.ts
  types/expectations.d.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1543

#1572 Update helm charts to add postgresql
  charts/cmc-citizen-frontend/values.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1572

#1571 ROC-5329 Remove comments causing security alerts
  src/main/public/js/analytics-custom-event-sender.js
Labels: ns:cmc-citizen-frontend-pr-1571

#1567 Use IDAM PR Helm chart for whitelisting urls
  Jenkinsfile_CNP
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1567

#1569 Fix nightly crossbrowser tests
  Jenkinsfile_nightly
Labels: ns:cmc-citizen-frontend-pr-1569

#1559 ROC-5381 Change content for defendant CCJ requested claim details page
  src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
Labels: ns:cmc-citizen-frontend-pr-1559

#1539 ROC-5160 Split Full Name for Their Details (individuals and sole traders)
  src/integration-test/data/test-data.ts
  src/integration-test/tests/citizen/ccj/ccj_test.ts
  src/integration-test/tests/citizen/ccj/pages/ccj-check-and-send.ts
  src/integration-test/tests/citizen/ccj/steps/ccj.ts
  src/integration-test/tests/citizen/claim/pages/claimant-check-and-send.ts
  src/integration-test/tests/citizen/claim/pages/individual-details.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/integration-test/tests/citizen/dashboard/dashboard_test.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/integration-test/tests/citizen/endToEnd/data/EndToEndTestData.ts
  src/main/app/claims/claimModelConverter.ts
  src/main/app/claims/converters/defendantDetails.ts
  src/main/app/claims/models/details/theirs/individual.ts
  src/main/app/claims/models/details/theirs/soleTrader.ts
  src/main/app/claims/responseModelConverter.ts
  src/main/app/drafts/draft-data/claimDraft.ts
  src/main/app/forms/models/individualDetails.ts
  src/main/app/forms/models/partyDetails.ts
  src/main/app/forms/models/soleTraderDetails.ts
  src/main/app/forms/models/splitNamedPartyDetails.ts
  src/main/app/pdf/mappers/defendantMapper.ts
  src/main/app/pdf/mappers/partyDetailsMapper.ts
  src/main/app/pdf/mappers/theirDetailsMapper.ts
  src/main/app/utils/nameFormatter.ts
  src/main/features/claim/views/defendant-individual-details.njk
  src/main/features/claim/views/defendant-sole-trader-details.njk
  src/test/app/claims/claimModelConverter.ts
  src/test/app/drafts/models/defendant.ts
  src/test/app/drafts/tasks/theirDetails.ts
  src/test/app/forms/models/companyDetails.ts
  src/test/app/forms/models/individualDetails.ts
  src/test/app/forms/models/organisationDetails.ts
  src/test/app/forms/models/soleTraderDetails.ts
  src/test/app/forms/models/validationUtils.ts
  src/test/app/utils/nameFormatter.ts
  src/test/data/draft/claimDraft.ts
  src/test/data/draft/partyDetails.ts
  src/test/data/entity/party.ts
  src/test/features/claim/routes/check-and-send.ts
  src/test/features/claim/routes/defendant-individual-details.ts
  src/test/features/claim/routes/defendant-sole-trader-details.ts
  src/test/http-mocks/draft-store.ts
  types/integration-test-model.d.ts
Labels: ns:cmc-citizen-frontend-pr-1539

#1575 ROC 2648 ff4j toggle for mediation pilot for claims less than 300
  charts/cmc-citizen-frontend/values.template.yaml
  src/main/features/claim/routes/pay.ts
Labels: ns:cmc-citizen-frontend-pr-1575

#1555 Point to SIDAM (demo/saat/sprod)
  charts/cmc-citizen-frontend/Chart.yaml
  infrastructure/demo.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
Labels: ns:cmc-citizen-frontend-pr-1555, pinned

#1562 ROC-5326: Company Details Page Defendant Contact person name missing
  src/main/features/claim/views/check-and-send.njk
  src/main/features/claim/views/defendant-company-details.njk
Labels: ns:cmc-citizen-frontend-pr-1562

#1584 ROC-5577 PA dashboard showing as FA
  src/main/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1584

#1576 ROC-5543 Fix check-and-send of part admit acceptation
  src/main/features/claimant-response/routes/check-and-send.ts
  src/test/features/claimant-response/routes/check-and-send.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1576

#1578 ROC-5456 Only enable the hearing details task for full defence and part admit
  src/main/features/response/helpers/taskListBuilder.ts
  src/test/features/response/helpers/taskListBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-1578

#1588 Revert codecept upgrade
  package.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1588

#1579 ROC-5450 refactor dashboard
  src/test/features/dashboard/routes/index.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1579

#1563 ROC-5418: Helm config changes
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/values.aat.template.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  charts/cmc-citizen-frontend/values.yaml
Labels: ns:cmc-citizen-frontend-pr-1563

#1544 ROC-4340: Settlement PDF content change
  src/main/features/claimant-response/views/macro/termsOfAgreementTable.njk
Labels: ns:cmc-citizen-frontend-pr-1544

#1570 ROC-5499: Task list inconsistencies
  src/main/features/claim/views/task-list.njk
  src/main/features/claimant-response/views/task-list.njk
  src/main/features/response/views/task-list.njk
  src/main/public/stylesheets/components/_task-list.scss
  src/test/features/response/routes/task-list.ts
Labels: ns:cmc-citizen-frontend-pr-1570

#1557 ROC-5433-Remove-unnecessary-fetch-call-before-save
  src/main/features/claim/routes/pay.ts
  src/test/features/claim/routes/pay.ts
Labels: ns:cmc-citizen-frontend-pr-1557

#1593 ROC-5564 Full defence dashboard and claim details route tests
  src/test/data/entity/fullDefenceData.ts
  src/test/data/entity/responseData.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/dashboard/full-defence.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1593

#1592 RPE-1043 Launchdarkly integration
  charts/cmc-citizen-frontend/values.yaml
  config/custom-environment-variables.json
  config/default.json
  config/mocha.json
  infrastructure/ithc.tfvars
  infrastructure/main.tf
  package.json
  src/integration-test/helpers/clients/claimStoreClient.ts
  src/main/common/clients/launchDarklyClient.ts
  src/main/features/claim/routes/pay.ts
  src/test/common/errorHandling.ts
  src/test/features/claim/routes/pay.ts
  src/test/routes/hooks.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1592
