Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-11, with the labels that each got.

#1949 Revert upgrades to fix builds
  package.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1949

#1948 update fees & pay default values
  infrastructure/variables.tf
Labels: ns:cmc-citizen-frontend-pr-1948

#1740 ROC-6020 Wrong payment date showing on check and send
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/test/features/claimant-response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1740

#1960 ROC-5265 - Part admission route tests
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimPartAdmittedDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/settlementAgreementDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/utilityMacros.njk
  src/main/features/response/views/confirmation.njk
  src/test/data/entity/partAdmitData.ts
  src/test/data/entity/responseData.ts
  src/test/features/dashboard/routes/claimStatus/part-admission.ts
  src/test/features/dashboard/routes/dashboard/part-admission.ts
Labels: ns:cmc-citizen-frontend-pr-1960

#1958 Add role for creating IDAM user
  src/integration-test/bootstrap/bootstrap.ts
  src/integration-test/helpers/clients/idamClient.ts
  src/integration-test/helpers/idamHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1958

#1942 ROC-6126: Citizen initiate the payment for claim
  src/main/app/claims/claimModelConverter.ts
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimState.ts
  src/main/features/claim/paths.ts
  src/main/features/claim/routes/check-and-send.ts
  src/main/features/claim/routes/initiate-payment.ts
  src/test/a11y/a11y.ts
  src/test/app/claims/claimStoreClient.ts
  src/test/features/claim/routes/check-and-send.ts
  src/test/features/claim/routes/initiate-payment.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1942

#1966 ROC-5565 full admission dashboard and claim details
  src/integration-test/tests/citizen/claimantResponse/full_admission_test.ts
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
  src/test/data/entity/fullAdmission.ts
  src/test/features/dashboard/routes/claimStatus/full-admission.ts
  src/test/features/dashboard/routes/claimStatus/settlement.ts
  src/test/features/dashboard/routes/dashboard/ccj.ts
  src/test/features/dashboard/routes/dashboard/full-admission.ts
  src/test/features/dashboard/routes/index.ts
Labels: ns:cmc-citizen-frontend-pr-1966

#1931 ROC-6127 Add finish payment controller
  src/main/app/claims/claimStoreClient.ts
  src/main/app/claims/models/claim.ts
  src/main/features/claim/helpers/featuresBuilder.ts
  src/main/features/claim/paths.ts
  src/main/features/claim/routes/finish-payment.ts
  src/main/features/claim/routes/pay.ts
  src/test/a11y/a11y.ts
  src/test/app/claims/claimStoreClient.ts
  src/test/features/claim/helpers/featuresBuilder.ts
  src/test/features/claim/routes/finish-payment.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1931

#1972 ROC-6885 Bump cmc-draft-store-middleware version to 2.0.1
  package.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1972

#1973 ROC-6131: Protection for successful payment in drafts before IOC
  src/main/features/claim/routes/initiate-payment.ts
  src/test/features/claim/routes/initiate-payment.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:cmc-citizen-frontend-pr-1973

#1947 ROC-6783 Change claimant dashboard and details page after accepting full defense
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1947

#1959 ROC-6779 dashboard to display mediation related content for failed mediation
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/mediationOutcome.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/main/features/response/views/counter-claim.njk
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
  src/main/modules/nunjucks/index.ts
  src/test/app/claims/models/claim.ts
  src/test/data/entity/claimData.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/part-admission.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
  src/test/features/dashboard/routes/dashboard/full-defence.ts
  src/test/features/dashboard/routes/dashboard/part-admission.ts
  src/test/features/dashboard/routes/dashboard/states-paid.ts
Labels: ns:cmc-citizen-frontend-pr-1959

#1943 ROC-6791 Change defendant dashboard and claim details page after claim ends
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1943

#1980 ROC-6127 finish-payment bug fixes
  src/main/features/claim/index.ts
  src/main/features/claim/routes/finish-payment.ts
  src/test/features/claim/routes/finish-payment.ts
Labels: ns:cmc-citizen-frontend-pr-1980

#1984 Fix payment converter for ioc
  src/main/app/claims/claimModelConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1984

#1989 ROC-6904 Allow undefined timeline one the claim details page
  src/main/features/first-contact/views/claim-summary.njk
  src/main/features/response/views/claim-details.njk
Labels: ns:cmc-citizen-frontend-pr-1989

#1990 ROC-6827: Added amount to defendant settled dashboard
  src/main/features/dashboard/views/macro/claimStatus/paidInFullDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1990

#2002 update chart
  Jenkinsfile_CNP
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:cmc-citizen-frontend-pr-2002

#2006 Only delete drafts in non-prod
  src/integration-test/tests/citizen/claim/steps/claim.ts
Labels: ns:cmc-citizen-frontend-pr-2006

#2009 Update failing smoke test
  src/integration-test/tests/citizen/claim/enterDetails_test.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
Labels: ns:cmc-citizen-frontend-pr-2009

#1977 ROC-6836 Show claimant hearing requirements on defendant dashboard mediation fails
  src/main/features/claimant-response/index.ts
  src/main/features/claimant-response/paths.ts
  src/main/features/claimant-response/routes/claimant-hearing-receipt.ts
  src/main/features/claimant-response/routes/confirmation.ts
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/directions-questionnaire/paths.ts
  src/main/features/directions-questionnaire/routes/claimant-hearing-receipt.ts
  src/main/features/response/paths.ts
  src/test/a11y/a11y.ts
  src/test/features/claimant-response/routes/confirmation.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/part-admission.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
  src/test/features/directions-questionnaire/routes/claimant-hearing-receipt.ts
Labels: ns:cmc-citizen-frontend-pr-1977

#2010 ROC-6668 Add christmas day in help
  src/main/modules/nunjucks/index.ts
  src/main/views/macro/support.njk
Labels: ns:cmc-citizen-frontend-pr-2010
