Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-06, with the labels that each got.

#1669 Revert codeceptjs update and update WebDriver
  Jenkinsfile_nightly
  default.conf.js
  package.json
  saucelabs.conf.js
  src/integration-test/helpers/claimStoreHelper.ts
  src/integration-test/helpers/clients/claimStoreClient.ts
  src/integration-test/helpers/pageHelper.js
  src/integration-test/tests/citizen/claim/pages/govpay/payment-confirmation.ts
  src/integration-test/tests/citizen/claim/steps/payment.ts
  src/integration-test/tests/citizen/claimantResponse/reject_test.ts
  src/integration-test/tests/citizen/dashboard/dashboard_test.ts
  src/integration-test/tests/citizen/defence/pages/defendant-enter-claim-pin-number.ts
  src/integration-test/tests/citizen/defence/pages/defendant-register.ts
  types/steps-override.d.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1669

#1667 ROC-5680 Automatically update the claim total as it is entered
  src/integration-test/tests/citizen/claim/fees_test.ts
  src/integration-test/tests/citizen/claim/pages/claimant-claim-amount.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/main/features/claim/views/amount.njk
  src/main/public/js/calculate-amount-total.js
Labels: ns:cmc-citizen-frontend-pr-1667

#1681 ROC-5767
  src/main/features/claim/views/resolving-this-dispute.njk
Labels: ns:cmc-citizen-frontend-pr-1681

#1678 RPC-5387 DQ content changes
  src/main/features/claim/routes/pay.ts
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/directions-questionnaire/forms/models/reportRow.ts
  src/main/features/directions-questionnaire/views/expert-evidence.njk
  src/main/features/directions-questionnaire/views/expert-reports.njk
  src/main/features/directions-questionnaire/views/hearing-dates.njk
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/main/features/directions-questionnaire/views/other-witnesses.njk
  src/main/features/directions-questionnaire/views/self-witness.njk
  src/main/features/directions-questionnaire/views/support-required.njk
  src/main/features/directions-questionnaire/views/why-expert-is-needed.njk
  src/main/features/response/helpers/taskListBuilder.ts
  src/test/features/claimant-response/helpers/taskListBuilder.ts
  src/test/features/directions-questionnaire/routes/hearing-location.ts
  src/test/features/directions-questionnaire/routes/otherWitnesses.ts
  src/test/features/directions-questionnaire/routes/selfWitness.ts
  src/test/features/response/helpers/taskListBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-1678

#1671 ROC-5739 Show DQ link to full defence defendants
  src/main/features/response/views/confirmation/full-defence-steps.njk
  src/main/features/response/views/confirmation/part-admission-steps.njk
Labels: ns:cmc-citizen-frontend-pr-1671

#1654 ROC-5317: Hearing exceptional circumstances
  src/main/app/court-finder/court.ts
  src/main/app/court-finder/courtFinderClient.ts
  src/main/app/court-finder/spoe.ts
  src/main/features/directions-questionnaire/draft/directionsQuestionnaireDraft.ts
  src/main/features/directions-questionnaire/views/hearing-exceptional-circumstances.njk
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/test/a11y/mocks.ts
  src/test/app/court-finder/courtFinderClient.ts
  src/test/features/directions-questionnaire/routes/hearing-exceptional-circumstances.ts
  src/test/http-mocks/court-finder-client.ts
Labels: ns:cmc-citizen-frontend-pr-1654

#1692 Bump feature-toggle-api chart version
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1692

#1693 ROC-5842 - Part admit dashboard issue
  src/main/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1693

#1688 ROC-5819 Change content of button to continue
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/ccj/views/confirmation-redetermination.njk
  src/main/features/claim/views/confirmation.njk
  src/main/features/claimant-response/views/confirmation.njk
  src/main/features/offer/views/settled.njk
  src/main/features/paid-in-full/views/confirmation.njk
  src/main/features/response/views/confirmation.njk
  src/main/features/settlement-agreement/views/settlement-agreement-confirmation.njk
Labels: ns:cmc-citizen-frontend-pr-1688

#1679 ROC- 5409 response dq journey
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/directions-questionnaire/routes/hearing-dates.ts
  src/main/features/directions-questionnaire/routes/support-required.ts
  src/main/features/response/helpers/taskListBuilder.ts
  src/test/features/directions-questionnaire/routes/hearing-dates.ts
  src/test/features/directions-questionnaire/routes/support-required.ts
Labels: ns:cmc-citizen-frontend-pr-1679, pinned

#1696 Bump nodejs chart
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
Labels: ns:cmc-citizen-frontend-pr-1696

#1697 Fix feature-toggle api url
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1697

#1695 ROC-5810 fix for CCJ with payment date in the past
  src/main/app/claims/ccjModelConverter.ts
  src/main/app/claims/models/claim.ts
  src/main/features/ccj/routes/paid-amount-summary.ts
  src/main/features/ccj/views/check-and-send.njk
  src/main/features/dashboard/routes/claimant.ts
  src/test/app/claims/CCJModelConverter.ts
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1695

#1672 ROC-5373 mediation changes
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/common/components/free-mediation/howFreeMediationWorks.njk
  src/main/features/dashboard/paths.ts
  src/main/features/dashboard/routes/how-free-mediation-works.ts
  src/main/features/dashboard/views/how-free-mediation-works.njk
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/app/claims/models/claim.ts
  src/test/features/dashboard/routes/how-mediation-works.ts
Labels: ns:cmc-citizen-frontend-pr-1672

#1705 Bump idam-pr chart version
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1705
