Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-12, with the labels that each got.

#1994 ROC-5702 Dashboard change for ccj
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
  src/test/features/dashboard/routes/claimStatus/ccj.ts
  src/test/features/dashboard/routes/dashboard/ccj.ts
Labels: ns:cmc-citizen-frontend-pr-1994

#2019 disable auto merging to demo
  Jenkinsfile_CNP
Labels: ns:cmc-citizen-frontend-pr-2019

#2015 ROC-7023:Add legal advisor features
  src/main/features/claim/helpers/featuresBuilder.ts
  src/test/features/claim/helpers/featuresBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-2015

#2001 ROC:6823: Confirmation page content changes
  src/main/features/claimant-response/views/confirmation.njk
  src/test/features/claimant-response/routes/confirmation.ts
Labels: ns:cmc-citizen-frontend-pr-2001

#1885 ROC-6591 More time requested
  src/main/features/response/guards/allResponseTasksCompletedGuard.ts
  src/main/features/response/helpers/taskListBuilder.ts
  src/main/features/response/routes/task-list.ts
  src/test/features/response/helpers/taskListBuilder.ts
  src/test/features/response/routes/check-and-send.ts
  src/test/features/response/routes/task-list.ts
Labels: ns:cmc-citizen-frontend-pr-1885

#2029 Delete drafts before running the tests
  src/integration-test/tests/citizen/claim/enterDetails_test.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
Labels: ns:cmc-citizen-frontend-pr-2029

#2033 Don't retry request when set to zero
  src/main/app/client/request.ts
  src/main/features/claim/routes/finish-payment.ts
  src/main/features/claim/routes/initiate-payment.ts
Labels: ns:cmc-citizen-frontend-pr-2033

#2032 Revert change to e2e tests
  src/integration-test/tests/citizen/claim/enterDetails_test.ts
  src/integration-test/tests/citizen/dashboard/dashboard_test.ts
Labels: ns:cmc-citizen-frontend-pr-2032

#2005 ROC-6272 Updated defendant claim status after ccj has been requested
  src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
  src/test/features/dashboard/routes/claimStatus/ccj.ts
Labels: ns:cmc-citizen-frontend-pr-2005

#1999 ROC-6941 Updated content of ccj amount page
  src/main/common/components/ccj/paid-amount-summary.njk
Labels: ns:cmc-citizen-frontend-pr-1999

#1995 ROC-6814 Add claimant dqs to all relevant defendant dashboards
  src/main/features/claimant-response/routes/confirmation.ts
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmitRejectionDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/statesPaidRejected.njk
  src/main/features/dashboard/views/macro/claimStatus/utilityMacros.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/part-admission.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
Labels: ns:cmc-citizen-frontend-pr-1995

#2036 ROC-7142: Resume 404 frontend loop
  src/main/features/claim/routes/initiate-payment.ts
Labels: ns:cmc-citizen-frontend-pr-2036

#2016 ROC-6908: Increase DQ limit to 1000
  src/main/features/claim/helpers/featuresBuilder.ts
  src/test/features/claim/helpers/featuresBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-2016

#1998 ROC-6393 Optimise e2e tests
  default.conf.js
  docker-compose.functional-tests.yml
  docker-compose.nightly-functional-tests.yml
  src/integration-test/bootstrap/bootstrap.ts
  src/integration-test/bootstrap/teardown.ts
  src/integration-test/data/test-data.ts
  src/integration-test/helpers/claimStoreHelper.ts
  src/integration-test/helpers/clients/idamClient.ts
  src/integration-test/tests/citizen/ccj/ccj_test.ts
  src/integration-test/tests/citizen/ccj/steps/ccj.ts
  src/integration-test/tests/citizen/claim/enterDetails_test.ts
  src/integration-test/tests/citizen/claim/pages/individual-details.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/integration-test/tests/citizen/claim/steps/payment.ts
  src/integration-test/tests/citizen/claimantResponse/part_admission_test.ts
  src/integration-test/tests/citizen/claimantResponse/steps/defendant.ts
  src/integration-test/tests/citizen/dashboard/dashboard_test.ts
  src/integration-test/tests/citizen/defence/data/DefenceTest.ts
  src/integration-test/tests/citizen/defence/defence_handoff_test.ts
  src/integration-test/tests/citizen/defence/full_admission_test.ts
  src/integration-test/tests/citizen/defence/part_admission_test.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/integration-test/tests/citizen/endToEnd/data/EndToEndTestData.ts
  src/integration-test/tests/citizen/endToEnd/steps/helper.ts
  src/integration-test/tests/citizen/govukAccessRoutes/respondToClaim_test.ts
  src/integration-test/tests/citizen/govukAccessRoutes/returnToClaim_test.ts
  src/integration-test/tests/citizen/home/steps/user.ts
  src/integration-test/tests/citizen/offers/offers_test.ts
  src/integration-test/tests/citizen/testingSupport/testingSupport_test.ts
  types/steps-override.d.ts
Labels: ns:cmc-citizen-frontend-pr-1998

#2014 ROC-7043 AppInsights custom event for all rendering errors
  src/main/app.ts
  src/main/features/dashboard/index.ts
  src/main/modules/app-insights/index.ts
  src/main/modules/app-insights/telemetryProcessors.ts
  src/main/server.ts
  src/test/modules/app-insights/facade.ts
  src/test/modules/app-insights/telemetryProcessors.ts
  src/test/routes/errorHandling.ts
Labels: ns:cmc-citizen-frontend-pr-2014

#2004 ROC-7016 Update dashboard
  src/integration-test/tests/citizen/claim/enterDetails_test.ts
  src/integration-test/tests/citizen/dashboard/dashboard_test.ts
  src/integration-test/tests/citizen/endToEnd/defence_test.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/defendant.njk
  src/main/public/stylesheets/components/_dashboard.scss
Labels: ns:cmc-citizen-frontend-pr-2004

#2042 ROC-6492 Change label to 'A limited company'
  src/main/features/claim/views/claimant-party-type-selection.njk
  src/main/features/claim/views/defendant-party-type-selection.njk
Labels: ns:cmc-citizen-frontend-pr-2042

#2028 ROC-7052: Failed mediation dashboard changes
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/part-admission.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
Labels: ns:cmc-citizen-frontend-pr-2028

#2022 ROC-5947: Alert ordnance survey keys
  src/main/routes/postcode-lookup.ts
  src/test/routes/postcode-lookup.ts
Labels: ns:cmc-citizen-frontend-pr-2022

#2007 ROC-6924: CCJ breach of settlement
  src/main/app/claims/ccjModelConverter.ts
  src/test/app/claims/ccjModelConverter.ts
Labels: ns:cmc-citizen-frontend-pr-2007

#2049 enable ioc on aat
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
Labels: ns:cmc-citizen-frontend-pr-2049

#2051 Fix for failing e2e test
  src/integration-test/tests/citizen/dashboard/dashboard_test.ts
Labels: ns:cmc-citizen-frontend-pr-2051

#2041 ROC-7146 Change button text
  src/main/features/paid-in-full/views/date-paid.njk
Labels: ns:cmc-citizen-frontend-pr-2041

#2052 disable ioc on aat
  infrastructure/aat.tfvars
Labels: ns:cmc-citizen-frontend-pr-2052

#2045 ROC-7152 Update the mediation pilot limit
  src/main/features/claim/helpers/featuresBuilder.ts
  src/main/features/mediation/views/free-mediation.njk
  src/main/modules/nunjucks/index.ts
Labels: ns:cmc-citizen-frontend-pr-2045

#1932 ROC-5502 citizen dashboard status for paper response before default judgment
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/paperResponse.njk
  src/test/app/claims/models/claim.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/dashboard/full-defence.ts
Labels: ns:cmc-citizen-frontend-pr-1932

#2055 ROC-7181-Draft claims with payment record when IOC was off, then IOC turned on.
  src/main/features/claim/routes/initiate-payment.ts
  src/main/features/claim/views/confirmation.njk
  src/test/features/claim/routes/initiate-payment.ts
Labels: ns:cmc-citizen-frontend-pr-2055

#2061 enable ioc
  infrastructure/aat.tfvars
Labels: ns:cmc-citizen-frontend-pr-2061

#2062 disable ioc AAT
  infrastructure/aat.tfvars
Labels: ns:cmc-citizen-frontend-pr-2062

#2070 ROC-7027 Static page for WAF errors
  src/main/public/waf.html
Labels: ns:cmc-citizen-frontend-pr-2070
