Repository hmcts/cmc-citizen-frontend, pull requests merged in 2019-02, with the labels that each got.

#1322 ROC-5037: convert aks manifests to helm
  Jenkinsfile_CNP
  README.md
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.aat.template.yaml
  charts/cmc-citizen-frontend/values.template.yaml
  src/kubernetes/.lint.yml
  src/kubernetes/README.md
  src/kubernetes/config.aat.yaml
  src/kubernetes/deployment.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1322

#1366 Auto monitoring of stale PRs
  .github/stale.yml
Labels: ns:cmc-citizen-frontend-pr-1366

#1374 ROC-5142 Part admit pay immediately check-and-send page
  src/main/features/claimant-response/routes/check-and-send.ts
  src/main/features/claimant-response/routes/settle-admitted.ts
  src/main/features/claimant-response/views/settle-admitted.njk
Labels: ns:cmc-citizen-frontend-pr-1374

#1373 ROC-5128 Wrong content showing in widget
  src/main/features/claim/views/macro/about-claim-widget.njk
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/defendant.njk
Labels: ns:cmc-citizen-frontend-pr-1373

#1381 ROC-5033: Added payment date route tests - PR1
  src/test/features/claimant-response/routes/payment-date.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1381

#1385 update feature-toggle-api chart
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1385

#1371 ROC-5125 Wrong content
  src/main/features/dashboard/views/macro/claimStatus/claimFullAdmissionForDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1371

#1380 ROC-5152 refactor OS Places usage
  package.json
  src/main/app/forms/validation/validators/isCountrySupported.ts
  src/main/app/postcode-lookup/clientFactory.ts
  src/main/public/js/postcode-lookup.js
  src/main/routes/postcode-lookup.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1380

#1372 ROC-5139 Sole trader admission CCJ
  src/main/app/claims/ccjModelConverter.ts
  src/main/features/ccj/draft/draftCCJ.ts
Labels: ns:cmc-citizen-frontend-pr-1372

#1375 ROC-5110 Claimant accept states paid less than amount claim, answers not saved in DB
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/claims/models/claimant-response/claimantResponseCommon.ts
  src/main/app/claims/models/response/core/claimantResponse.ts
  src/main/app/claims/models/response/core/responseAcceptance.ts
  src/main/app/claims/models/response/core/responseRejection.ts
  src/main/features/settlement-agreement/guards/settlementAgreementGuard.ts
  src/test/app/claims/converters/claimantResponseConverter.ts
Labels: ns:cmc-citizen-frontend-pr-1375

#1390 ROC-5033: Added routes tests and test data for payment-plan page
  src/test/common/helpers/courtDecisionHelper.ts
  src/test/data/entity/responseData.ts
  src/test/features/claimant-response/routes/payment-plan.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1390

#1397 Update @types/node version
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1397

#1103 optimising travis builds
  .travis.yml
Labels: ns:cmc-citizen-frontend-pr-1103

#1328 ROC-4852: Defendant can submit first payment date in the past (payment plan scenario)
  src/main/features/response/tasks/decideHowYouWillPayTask.ts
  src/main/features/response/tasks/whenWillYouPayTask.ts
  src/main/features/response/tasks/yourRepaymentPlanTask.ts
  src/test/features/response/tasks/decideHowYouWillPayTask.ts
  src/test/features/response/tasks/whenWillYouPayTask.ts
  src/test/features/response/tasks/yourRepaymentPlanTask.ts
Labels: ns:cmc-citizen-frontend-pr-1328

#1391 Limit calls to new OS postcode lookup APIs in E2E tests
  src/integration-test/tests/citizen/claim/pages/claimant-check-and-send.ts
  src/integration-test/tests/citizen/claim/pages/company-details.ts
  src/integration-test/tests/citizen/claim/pages/individual-details.ts
  src/integration-test/tests/citizen/claim/pages/organisation-details.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/integration-test/tests/citizen/testingSupport/steps/testingSupport.ts
Labels: ns:cmc-citizen-frontend-pr-1391

#1396 ROC-4692 Bump cmc-validators dependency to 0.2.2
  package.json
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1396

#1392 Cross browser typescript fix
  saucelabs.conf.js
Labels: ns:cmc-citizen-frontend-pr-1392

#1408 Fix image to match integration tests
  docker-compose.yml
Labels: ns:cmc-citizen-frontend-pr-1408

#1402 Postcode E2E Changes for Prod
  Jenkinsfile_CNP
  docker-compose.functional-tests.yml
  docker-compose.smoke-tests.yml
  infrastructure/aat.tfvars
  infrastructure/demo.tfvars
  infrastructure/main.tf
  infrastructure/output.tf
  infrastructure/preview.tfvars
  infrastructure/saat.tfvars
  infrastructure/sprod.tfvars
  infrastructure/variables.tf
  src/integration-test/tests/citizen/claim/pages/individual-details.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1402

#1409 ROC-5152 address organisation population and IE11 support
  src/main/public/js/postcode-lookup.js
Labels: ns:cmc-citizen-frontend-pr-1409

#1403 ROC-5084: Part admission states paid statuses
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/paidInFullDefendant.njk
  src/main/features/dashboard/views/macro/claimStatus/partAdmissionStatesPaidAccepted.njk
  src/test/app/claims/models/claim.ts
  src/test/data/entity/claimantResponseData.ts
Labels: ns:cmc-citizen-frontend-pr-1403

#1415 ROC-5033:Added new route tests for immediately option
  src/test/data/entity/responseData.ts
  src/test/features/claimant-response/routes/payment-option.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1415

#1417 Lookup address in smoke test
  src/integration-test/tests/citizen/claim/pages/company-details.ts
  src/integration-test/tests/citizen/claim/pages/individual-details.ts
  src/integration-test/tests/citizen/claim/pages/organisation-details.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/integration-test/tests/citizen/testingSupport/steps/testingSupport.ts
Labels: ns:cmc-citizen-frontend-pr-1417

#1418 ROC-4699 - added scenario Should validate the hyperlink (Change) avai…
  src/test/features/claim/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-1418

#1401 ROC-5217 Decide how you'll pay is not showing as Completed only in instalments scenario
  src/main/features/response/tasks/decideHowYouWillPayTask.ts
  src/test/features/response/tasks/decideHowYouWillPayTask.ts
Labels: ns:cmc-citizen-frontend-pr-1401

#1424 ROC-5251: fix feature-toggle service port
  charts/cmc-citizen-frontend/values.template.yaml
Labels: ns:cmc-citizen-frontend-pr-1424

#1386 Activate ACR build, image multistaging and hmcts runtime user
  .gitignore
  Dockerfile
  acb.tpl.yaml
  package.json
Labels: docker-optimisation, ns:cmc-citizen-frontend-pr-1386

#1425 ROC-4864 Can we use phone number
  src/main/features/mediation/draft/mediationDraft.ts
  src/main/features/mediation/form/models/CanWeUse.ts
  src/main/features/mediation/index.ts
  src/main/features/mediation/paths.ts
  src/main/features/mediation/routes/can-we-use.ts
  src/main/features/mediation/routes/mediation-agreement.ts
  src/main/features/mediation/views/can-we-use.njk
  src/main/features/mediation/views/how-mediation-works.njk
  src/main/features/mediation/views/mediation-agreement.njk
  src/main/features/response/views/check-and-send.njk
  src/main/modules/nunjucks/index.ts
  src/test/features/mediation/routes/can-we-use.ts
  src/test/features/mediation/routes/free-mediation.ts
  src/test/features/mediation/routes/how-mediation-works.ts
  src/test/features/mediation/routes/mediation-agreement.ts
  src/test/features/mediation/routes/will-you-try-mediation.ts
  src/test/http-mocks/claim-store.ts
Labels: ns:cmc-citizen-frontend-pr-1425

#1427 Update dependancies
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1427

#1429 set up cmc citizen frontend security scan
  Jenkinsfile_nightly
  security.sh
Labels: ns:cmc-citizen-frontend-pr-1429

#1384 ROC-4928 defence task list - display INCOMPLETE status
  package.json
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
  src/integration-test/tests/citizen/claimantResponse/steps/defendant.ts
  src/integration-test/tests/citizen/defence/steps/defence.ts
  src/main/features/response/views/task-list.njk
  src/main/public/stylesheets/components/_task-list.scss
  src/test/features/claim/routes/task-list.ts
  src/test/features/response/routes/task-list.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1384

#1426 ROC-5231 Change content to remove amount from paid in full
  src/main/features/dashboard/views/macro/claimStatus/paidInFullClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/paidInFullDefendant.njk
Labels: ns:cmc-citizen-frontend-pr-1426

#1431 ROC-5151: Rejection reason and dashboard status fix & dashboard status
  src/main/app/claims/converters/claimantResponseConverter.ts
  src/main/app/claims/models/claim.ts
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedClaimant.njk
  src/main/features/dashboard/views/macro/claimStatus/redeterminationRequestedDefendant.njk
  src/test/app/claims/converters/claimantResponseConverter.ts
  src/test/app/claims/models/claim.ts
Labels: ns:cmc-citizen-frontend-pr-1431

#1435 Fix git push to demo
  Jenkinsfile_CNP
Labels: ns:cmc-citizen-frontend-pr-1435

#1436 Fix nightly Jenkins security scanning
  Jenkinsfile_nightly
Labels: ns:cmc-citizen-frontend-pr-1436

#1434 ROC-3850 Rearrange eligibility questions in descending order of drop-off rate
  src/integration-test/tests/citizen/claim/steps/eligibility.ts
  src/main/features/eligibility/routes/claim-is-for-tenancy-deposit.ts
  src/main/features/eligibility/routes/claim-type.ts
  src/main/features/eligibility/routes/claimant-address.ts
  src/main/features/eligibility/routes/defendant-address.ts
  src/main/features/eligibility/routes/defendant-age.ts
  src/main/features/eligibility/routes/government-department.ts
  src/main/features/eligibility/routes/help-with-fees.ts
  src/main/features/eligibility/routes/over-18.ts
  src/main/features/eligibility/routes/single-defendant.ts
  src/test/features/eligibility/model/eligibility.ts
  src/test/features/eligibility/routes/claim-is-for-tenancy-deposit.ts
  src/test/features/eligibility/routes/claim-type.ts
  src/test/features/eligibility/routes/claimant-address.ts
  src/test/features/eligibility/routes/defendant-address.ts
  src/test/features/eligibility/routes/defendant-age.ts
  src/test/features/eligibility/routes/government-department.ts
  src/test/features/eligibility/routes/help-with-fees.ts
  src/test/features/eligibility/routes/over-18.ts
  src/test/features/eligibility/routes/single-defendant.ts
Labels: ns:cmc-citizen-frontend-pr-1434

#1442 Fix user permission on docker build step
  Dockerfile
Labels: ns:cmc-citizen-frontend-pr-1442

#1448 Exclude the acb.yaml file from being ignored on acr build
  .dockerignore
Labels: ns:cmc-citizen-frontend-pr-1448

#1410 ROC-4647: Disposable income issues
  src/main/common/helpers/paymentPlanHelper.ts
  src/main/features/claimant-response/routes/payment-plan.ts
  src/test/common/helpers/paymentIntentionHelper.ts
Labels: ns:cmc-citizen-frontend-pr-1410

#1450 Added one word ('free') to mediation button
  src/main/features/mediation/views/free-mediation.njk
Labels: ns:cmc-citizen-frontend-pr-1450

#1449 One mediation text change
  src/main/features/mediation/views/how-mediation-works.njk
Labels: ns:cmc-citizen-frontend-pr-1449

#1452 Integrating the key vault flex volume for secrets.
  Jenkinsfile_CNP
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.template.yaml
  config/custom-environment-variables.json
  config/default.json
  package.json
  server.js
  src/main/app.ts
  src/main/app/idam/idamClient.ts
  src/main/app/postcode-lookup/clientFactory.ts
  src/main/modules/app-insights/index.ts
  src/main/modules/nunjucks/index.ts
  src/main/services/draftService.ts
  src/test/routes/receiver.ts
  yarn.lock
Labels: ns:cmc-citizen-frontend-pr-1452
