Repository hmcts/cmc-citizen-frontend, pull requests merged in 2020-10, with the labels that each got.

#2560 Deactivate 'My Account' and 'Sign Out' links on the 'first-contact/claim-summary' page
  charts/cmc-citizen-frontend/values.preview.template.yaml
  src/main/app/idam/authorizationMiddleware.ts
  src/main/views/includes/propositional_navigation.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2560

#2591 Update values.preview.template.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2591

#2595 Added 'SQL Injection - Oracle - Time Based' to the exception list
  audit.json
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2595

#2597 Remove proxyout config
  docker-compose.functional-tests.yml
  docker-compose.nightly-functional-tests.yml
  docker-compose.smoke-tests.yml
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2597

#2535 Feature/ROC-7363-Bespoke-Dashboard
  src/main/app/claims/models/claim.ts
  src/main/app/claims/models/claimState.ts
  src/main/app/claims/models/claimStatus.ts
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/caseStatus.njk
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/test/app/claims/models/claim.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2535

#2596 Update OCMC with new CTSC working hours.
  src/main/public/waf.html
  src/main/public/webchat/javascript/webchart-init.js
  src/main/views/macro/support.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2596

#2603 Added security scan exceptions
  audit.json
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2603
