Repository hmcts/cmc-citizen-frontend, pull requests merged in 2020-09, with the labels that each got.

#2478 ROC-8276 Postcode validation
  src/main/app/forms/validation/formValidator.ts
  src/main/public/js/postcode-lookup.js
  src/test/app/forms/validation/formValidator.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2478

#2470 ROC-8275-Validation-Contact-person-character-length
  charts/cmc-citizen-frontend/values.preview.template.yaml
  src/main/app/forms/models/organisationDetails.ts
  src/test/features/claim/routes/claimant-organisation-details.ts
  src/test/features/claim/routes/defendant-organisation-details.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2470

#2493 CCD Def Version Bump
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2493

#2467 feature(ROC-8263): Configure zap-cli to report only Medium risk and above
  audit.json
  security.sh
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2467

#2502 Feature/roc 7794 capture all dq
  src/main/features/directions-questionnaire/forms/models/supportRequired.ts
  src/main/features/directions-questionnaire/routes/support-required.ts
  src/test/features/directions-questionnaire/form/models/supportRequired.ts
  src/test/features/directions-questionnaire/routes/support-required.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2502

#2494 feature: ignore more 'Informational' security scan alerts as too low priority
  audit.json
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2494

#2505 Rdm 9523 bump ccd version
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2505

#2469 Features/roc 7786 accessibility non descriptive form elements issue
  src/main/features/claim/views/amount.njk
  src/main/features/claim/views/resolving-this-dispute.njk
  src/main/features/response/views/macro/statement-of-means/incomeExpenseSource.njk
  src/main/features/response/views/statement-of-means/monthly-expenses.njk
  src/main/features/response/views/statement-of-means/monthly-income.njk
  src/main/features/response/views/statement-of-means/priority-debts.njk
  src/main/public/js/append-row.js
  src/main/views/macro/form.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2469

#2458 Bug/roc 8224 task list
  .sass-lint.yml
  gulpfile.js
  package.json
  src/main/app/utils/taskStatus.ts
  src/main/common/components/free-mediation/freeMediationCheckAndSendBlock.njk
  src/main/features/claim/helpers/taskListBuilder.ts
  src/main/features/claim/routes/task-list.ts
  src/main/features/claim/views/check-and-send.njk
  src/main/features/claim/views/claimant-party-type-selection.njk
  src/main/features/claim/views/defendant-party-type-selection.njk
  src/main/features/claim/views/task-list.njk
  src/main/features/claim/views/total.njk
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/claimant-response/routes/task-list.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/task-list.njk
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/main/features/directions-questionnaire/views/name-results.njk
  src/main/features/eligibility/views/not-eligible.njk
  src/main/features/response/helpers/taskListBuilder.ts
  src/main/features/response/routes/task-list.ts
  src/main/features/response/views/check-and-send.njk
  src/main/features/response/views/evidence.njk
  src/main/features/response/views/macro/check-and-send/admission.njk
  src/main/features/response/views/statement-of-means/check-and-send.njk
  src/main/features/response/views/task-list.njk
  src/main/features/response/views/timeline.njk
  src/main/public/stylesheets/README.md
  src/main/public/stylesheets/application.scss
  src/main/public/stylesheets/components/_colours.scss
  src/main/public/stylesheets/components/_external_link.scss
  src/main/public/stylesheets/components/_font-size.scss
  src/main/public/stylesheets/components/_form.scss
  src/main/public/stylesheets/govuk-frontend/patterns/_task-list.scss
  src/main/public/stylesheets/govuk-frontend/task-list.scss
  src/main/views/macro/address.njk
  src/main/views/macro/date.njk
  src/main/views/macro/externalLink.njk
  src/main/views/macro/form.njk
  src/main/views/macro/party/details.njk
  src/main/views/macro/statementOfTruth.njk
  src/main/views/macro/table.njk
  src/main/views/macro/task-list.njk
  src/main/views/macro/timelineCheckAndSend.njk
  src/test/app/utils/taskStatus.ts
  src/test/features/claim/routes/check-and-send.ts
  src/test/features/claim/routes/task-list.ts
  src/test/features/claimant-response/routes/task-list.ts
  src/test/features/response/routes/task-list.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2458

#2517 Bug/roc 8224 task list
  .sass-lint.yml
  gulpfile.js
  package.json
  src/main/app/utils/taskStatus.ts
  src/main/common/components/free-mediation/freeMediationCheckAndSendBlock.njk
  src/main/features/claim/helpers/taskListBuilder.ts
  src/main/features/claim/routes/task-list.ts
  src/main/features/claim/views/check-and-send.njk
  src/main/features/claim/views/claimant-party-type-selection.njk
  src/main/features/claim/views/defendant-party-type-selection.njk
  src/main/features/claim/views/task-list.njk
  src/main/features/claim/views/total.njk
  src/main/features/claimant-response/helpers/taskListBuilder.ts
  src/main/features/claimant-response/routes/task-list.ts
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/task-list.njk
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/main/features/directions-questionnaire/views/name-results.njk
  src/main/features/eligibility/views/not-eligible.njk
  src/main/features/response/helpers/taskListBuilder.ts
  src/main/features/response/routes/task-list.ts
  src/main/features/response/views/check-and-send.njk
  src/main/features/response/views/evidence.njk
  src/main/features/response/views/macro/check-and-send/admission.njk
  src/main/features/response/views/statement-of-means/check-and-send.njk
  src/main/features/response/views/task-list.njk
  src/main/features/response/views/timeline.njk
  src/main/public/stylesheets/README.md
  src/main/public/stylesheets/application.scss
  src/main/public/stylesheets/components/_colours.scss
  src/main/public/stylesheets/components/_external_link.scss
  src/main/public/stylesheets/components/_font-size.scss
  src/main/public/stylesheets/components/_form.scss
  src/main/public/stylesheets/govuk-frontend/patterns/_task-list.scss
  src/main/public/stylesheets/govuk-frontend/task-list.scss
  src/main/views/macro/address.njk
  src/main/views/macro/date.njk
  src/main/views/macro/externalLink.njk
  src/main/views/macro/form.njk
  src/main/views/macro/party/details.njk
  src/main/views/macro/statementOfTruth.njk
  src/main/views/macro/table.njk
  src/main/views/macro/task-list.njk
  src/main/views/macro/timelineCheckAndSend.njk
  src/test/app/utils/taskStatus.ts
  src/test/features/claim/routes/check-and-send.ts
  src/test/features/claim/routes/task-list.ts
  src/test/features/claimant-response/routes/task-list.ts
  src/test/features/response/routes/task-list.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2517

#2534 Features/roc 7793 accessiblity dac issue fix
  package.json
  src/main/features/claim/views/total.njk
  src/main/features/claimant-response/views/check-and-send.njk
  src/main/features/claimant-response/views/macro/evidenceTable.njk
  src/main/features/claimant-response/views/macro/timelineTable.njk
  src/main/features/dashboard/views/index.njk
  src/main/features/directions-questionnaire/views/components/date-list.njk
  src/main/features/directions-questionnaire/views/hearing-dates.njk
  src/main/features/response/views/statement-of-means/bank-accounts.njk
  src/main/features/response/views/timeline.njk
  src/main/public/js/append-row.js
  src/main/public/js/date-picker.js
  src/main/public/waf.html
  src/main/views/includes/phase_banner_beta.njk
  src/main/views/macro/address.njk
  src/main/views/macro/amountBreakdown.njk
  src/main/views/macro/date.njk
  src/main/views/macro/evidenceFragment.njk
  src/main/views/macro/feesTable.njk
  src/main/views/macro/form.njk
  src/main/views/macro/internalLink.njk
  src/main/views/macro/summaryTable.njk
  src/test/a11y/README.md
  src/test/a11y/a11y.ts
  src/test/a11y/customChecks.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2534

#2538 Features/accessibility issue fix
  src/main/features/claim/views/claimant-party-type-selection.njk
  src/main/features/claim/views/defendant-party-type-selection.njk
  src/main/features/claim/views/total.njk
  src/main/public/stylesheets/components/_colours.scss
  src/main/views/macro/date.njk
  src/main/views/macro/externalLink.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2538

#2540 DAC master pull request for all DAC fixes and test cases
  src/main/public/js/date-picker.js
  src/test/a11y/a11y.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2540

#2512 Update to accessibility statement (ROC-7964)
  src/main/views/accessibility-statement.njk
  src/main/views/macro/support.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2512

#2488 Feature/enable and fix pa11y warning checks
  src/test/a11y/a11y.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2488

#2462 ROC-8240 Defendant Incomplete Submission Page Fix
  src/main/features/response/routes/incomplete-submission.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2462

#2548 [Bug Fix] Claimant-Response : Check and send page issue
  src/main/features/claimant-response/views/check-and-send.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2548

#2546 Citizen Nightly security scan issue fix
  src/main/modules/helmet/index.ts
  src/main/modules/nunjucks/index.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2546

#2558 Update values.preview.template.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2558

#2559 Update terraform
  infrastructure/main.tf
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2559

#2561 Taraform update
  infrastructure/.terraform-version
  infrastructure/main.tf
  infrastructure/state.tf
  infrastructure/variables.tf
  infrastructure/versions.tf
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2561

#2549 ROC-8313 - Claims stuck in draft
  src/main/features/claim/routes/confirmation.ts
  src/test/features/claim/routes/confirmation.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-2549
