Repository hmcts/cmc-citizen-frontend, pull requests merged in 2020-03, with the labels that each got.

#2208 Upgrade nodejs chart to latest
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2208

#2129 ROC-7343 Add contact name
  src/main/features/claim/views/defendant-organisation-details.njk
  src/test/features/claim/routes/defendant-organisation-details.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2129

#2209 Switch to AKS AAT
  Jenkinsfile_CNP
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2209

#2182 Increase threshold of Online DQs to 10,000
  src/main/features/claim/helpers/featuresBuilder.ts
  src/test/features/claim/helpers/featuresBuilder.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2182, stale

#2214 upgrade claim-store
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2214

#2215 ROC-7594 | Fix for E2E: 'I can as an Individual make a claim against …
  src/integration-test/tests/citizen/claimantResponse/steps/claimant-reponse.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2215

#2217 Enable webchat on all environment
  infrastructure/variables.tf
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2217

#2216 ROC-7642: Fix draft discrepancies in testing support
  src/main/app/drafts/draft-data/claimDraft.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2216

#2218 Updated nightly build failed configuration issue
  docker-compose.nightly-functional-tests.yml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2218

#2195 Stop nightly tests failing as badly
  Jenkinsfile_nightly
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2195

#2104 ROC-72412: Keep formatting of multiline fields
  src/main/views/macro/table.njk
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2104

#2226 Rename web chat config variables names
  config/custom-environment-variables.json
  config/default.json
  src/main/public/webchat/javascript/webchart-init.js
  src/main/routes/webchat.ts
  src/test/routes/webchat.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2226

#2232 bump frontend chart version
  charts/cmc-citizen-frontend/Chart.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2232

#2238 fixing pr issues
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2238

#2211 [To merge 19 March] ROC-7619 Decide features from the saved claim, in IoC
  src/main/features/claim/helpers/featuresBuilder.ts
  src/main/features/claim/routes/finish-payment.ts
  src/main/features/claim/routes/pay.ts
  src/test/features/claim/helpers/featuresBuilder.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2211

#2233 decommission ase aat
  infrastructure/main.tf
  infrastructure/prod.tfvars
  infrastructure/variables.tf
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2233

#2243 decommission ase prod
  infrastructure/demo.tfvars
  infrastructure/prod.tfvars
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2243

#2244 ROC-7769-Banner to warn people CCBC is down
  src/main/public/stylesheets/application.scss
  src/main/public/stylesheets/components/_banner.scss
  src/main/public/stylesheets/components/_colours.scss
  src/main/views/govukTemplate.njk
  src/main/views/includes/banner.njk
  src/main/views/layout.njk
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2244

#2249 ROC-7813 Take down downtime banner
  src/main/views/layout.njk
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2249

#2250 update terraform
  infrastructure/main.tf
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2250
