Repository hmcts/cmc-citizen-frontend, pull requests merged in 2020-02, with the labels that each got.

#2162 ROC-7473: Add date as postfix to functional test user
  src/integration-test/data/test-data.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2162

#2163 ROC-7473: Update email pattern for test user
  src/integration-test/data/test-data.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2163

#2164 upgrade claimstore chart
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2164

#2166 add postcode lookup key
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/values.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2166

#2134 ROC-5803 ROC-5805 Bump OS Names dependency to 1.0.7
  package.json
  yarn.lock
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2134

#2165 ROC-7263: Incorrect fees
  src/main/app/fees/models/currentVersion.ts
  src/main/features/claim/helpers/feesTableViewHelper.ts
  src/test/features/claim/helpers/feesTableViewHelper.ts
  src/test/http-mocks/fees.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2165

#2127 ROC-6396: Hidden date picker errors
  src/main/public/js/date-picker.js
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2127

#2128 ROC-7365: Page format
  src/main/features/dashboard/views/claimant.njk
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2128

#2107 ROC-7300 : Resolve logout failure for header
  src/main/app/idam/idamClient.ts
  src/main/routes/logout.ts
  src/test/routes/logout.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2107

#2183 Aks migration prep
  .github/workflows/push.yml
  .nvmrc
  Dockerfile
  Jenkinsfile_CNP
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.aat.template.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  charts/cmc-citizen-frontend/values.yaml
  infrastructure/main.tf
  integration-tests.Dockerfile
  package.json
  src/main/modules/app-insights/index.ts
  src/test/modules/app-insights/facade.ts
  yarn.lock
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2183

#2192 Use forked cookie-encrypter
  package.json
  src/main/app.ts
  src/test/routes/receiver.ts
  yarn.lock
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2192

#2199 Fix postgres issues
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2199

#2200 [WIP] to investigate keyVault issue
  README.md
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  charts/cmc-citizen-frontend/values.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2200

#2206 upgrade postgresDb and bump chart version
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2206

#2188 RDM-7731: Upgrade ccd definition version to 1.5.10
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2188
