Repository hmcts/cmc-citizen-frontend, pull requests merged in 2020-01, with the labels that each got.

#2064 enable ioc aat
  infrastructure/aat.tfvars
Labels: ns:cmc-citizen-frontend-pr-2064

#2077 integration-test-fix-for-offer-date-in-test-data-to-never-expire
  src/integration-test/data/test-data.ts
Labels: ns:cmc-citizen-frontend-pr-2077

#2081 Remove duplicate env variables from nightly
  docker-compose.nightly-functional-tests.yml
Labels: ns:cmc-citizen-frontend-pr-2081

#2083 fix Zap-cli complaining about python2 and python3 compatibility
  security.sh
Labels: ns:cmc-citizen-frontend-pr-2083

#2020 ROC-7116 Enable IoC for Citizen in Production
  infrastructure/prod.tfvars
Labels: ns:cmc-citizen-frontend-pr-2020

#2099 Fix payment reference
  src/main/features/claim/routes/initiate-payment.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2099

#2084 ROC-7129 Updated split name to readonly
  src/main/features/response/views/your-details.njk
Labels: ns:cmc-citizen-frontend-pr-2084, ns:money-claims, rel:cmc-citizen-frontend-pr-2084

#2105 infrastructure change to consistently run functional test with IoC
  Jenkinsfile_CNP
  Jenkinsfile_nightly
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  charts/cmc-citizen-frontend/values.yaml
  config/default.json
  config/development.json
  config/dockertests.json
  config/mocha.json
  docker-compose.functional-tests.yml
  docker-compose.nightly-functional-tests.yml
  docker-compose.smoke-tests.yml
  infrastructure/aat.tfvars
  infrastructure/variables.tf
  src/integration-test/bootstrap/bootstrap.ts
  src/main/features/claim/routes/finish-payment.ts
  src/main/features/claim/routes/initiate-payment.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2105

#2047 ROC- 6908 Add cmc judge pilot in features and in ff4j
  charts/cmc-citizen-frontend/values.preview.template.yaml
  src/main/features/claim/helpers/featuresBuilder.ts
  src/main/features/dashboard/routes/claimant.ts
  src/main/features/dashboard/routes/defendant.ts
  src/main/features/dashboard/views/claimant.njk
  src/main/features/dashboard/views/defendant.njk
  src/main/features/dashboard/views/macro/caseHistory.njk
  src/main/features/dashboard/views/macro/claimStatus/orders.njk
  src/test/features/claim/helpers/featuresBuilder.ts
Labels: ns:cmc-citizen-frontend-pr-2047, ns:money-claims, rel:cmc-citizen-frontend-pr-2047

#2086 ROC-7225 Content changes from description
  .gitignore
  src/integration-test/tests/citizen/mediation/pages/continue-without-mediation.ts
  src/main/features/mediation/views/continue-without-mediation.njk
  src/main/features/mediation/views/free-mediation.njk
  src/main/features/mediation/views/mediation-agreement.njk
  src/main/features/mediation/views/mediation-disagreement.njk
Labels: ns:cmc-citizen-frontend-pr-2086, ns:money-claims, rel:cmc-citizen-frontend-pr-2086

#2132 upgrade nodejs chart
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2132

#2013 ROC-6966: Add Mediation Agreement link
  src/main/app/documents/documentsClient.ts
  src/main/features/dashboard/views/macro/claimStatus/claimRejected.njk
  src/main/features/mediation/paths.ts
  src/main/features/mediation/routes/mediation-agreement-receipt.ts
  src/test/a11y/a11y.ts
  src/test/features/dashboard/routes/claimStatus/full-defence.ts
  src/test/features/dashboard/routes/claimStatus/part-admission.ts
  src/test/features/dashboard/routes/claimStatus/states-paid.ts
  src/test/features/mediation/routes/agreement.ts
Labels: ns:cmc-citizen-frontend-pr-2013, ns:money-claims, rel:cmc-citizen-frontend-pr-2013

#2078 ROC-6820 Remove court decision from check and send page when not applicable
  src/main/features/claimant-response/views/check-and-send.njk
  src/test/features/claimant-response/routes/check-and-send.ts
Labels: ns:cmc-citizen-frontend-pr-2078, ns:money-claims, rel:cmc-citizen-frontend-pr-2078

#2135 Bump helm chart version and dependency of claim-store
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2135

#2136 Cleaning up chart conditions
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  charts/cmc-citizen-frontend/values.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2136

#2137 Revert dependency upgrades
  package.json
  yarn.lock
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2137

#2149 Revert "Cleaning up chart conditions"
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  charts/cmc-citizen-frontend/values.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2149

#2153 Revert 2078 bug/roc 6820 remove court decision from check and send karim
  src/main/features/claimant-response/views/check-and-send.njk
  src/test/features/claimant-response/routes/check-and-send.ts
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2153

#2154 add praveen changes
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/requirements.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  charts/cmc-citizen-frontend/values.yaml
Labels: ns:money-claims, rel:cmc-citizen-frontend-pr-2154
