Repository hmcts/cmc-citizen-frontend, pull requests merged in 2021-12, with the labels that each got.

#3293 CCD chart upgrade and hwf release update
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3293

#3294 Roc 9208 update LADO claims threshold
  src/main/features/claim/helpers/featuresBuilder.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3294

#3298 Revert "Roc 9208 update LADO claims threshold (#3294)"
  src/main/features/claim/helpers/featuresBuilder.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3298
