Repository hmcts/cmc-citizen-frontend, pull requests merged in 2021-11, with the labels that each got.

#3275 Dependency suppression
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3275

#3285 Removed mcol links and updated content of the initial eligibility page.
  src/main/features/eligibility/views/index.njk
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3285

#3282 Roc 9421 - Consistency in capturing names for Sole traders and individuals
  src/integration-test/data/test-data.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/main/app/drafts/draft-data/claimDraft.ts
  src/main/app/forms/models/splitNamedPartyDetails.ts
  src/main/features/claim/views/claimant-individual-details.njk
  src/main/features/claim/views/claimant-sole-trader-details.njk
  src/test/app/claims/claimModelConverter.ts
  src/test/app/claims/responseModelConverter.ts
  src/test/app/drafts/tasks/yourDetails.ts
  src/test/data/draft/partyDetails.ts
  src/test/data/entity/party.ts
  src/test/features/claim/routes/check-and-send.ts
  src/test/features/claim/routes/claimant-individual-details.ts
  src/test/features/claim/routes/claimant-soleTrader-details.ts
  src/test/http-mocks/draft-store.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3282
