Repository hmcts/cmc-citizen-frontend, pull requests merged in 2021-06, with the labels that each got.

#3130 Fix/yarn audit
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3130

#3116 Bug/roc 9143 counter claim form
  src/main/features/claim/helpers/feesTableViewHelper.ts
  src/test/features/claim/helpers/feesTableViewHelper.ts
  yarn-audit-known-issues
Labels: OCMC-PET-TEAM, ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3116

#3111 Feature/roc 9081 enhance hearing location
  config/development.json
  src/main/features/directions-questionnaire/forms/models/hearingLocation.ts
  src/main/features/directions-questionnaire/helpers/hearingLocationsHelper.ts
  src/main/features/directions-questionnaire/routes/hearing-location.ts
  src/main/features/directions-questionnaire/views/hearing-location.njk
  src/main/views/macro/form.njk
  src/test/features/directions-questionnaire/form/models/hearingLocation.ts
  src/test/features/directions-questionnaire/routes/hearing-location.ts
  src/test/features/directions-questionnaire/routes/name-results.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3111

#3134 ROC-9204-gov.uk-cookie-banner-removed
  package.json
  src/integration-test/tests/citizen/endToEnd/defence_test.ts
  src/main/modules/nunjucks/index.ts
  src/main/public/waf.html
  src/main/views/govukTemplate.njk
  src/main/views/layout.njk
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3134

#3145 Fix title missing on cookies page
  src/main/views/cookies.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3145

#3147 Roc 7168 postcode changes
  package.json
  src/main/app/forms/models/address.ts
  src/main/app/forms/models/correspondenceAddress.ts
  src/main/app/forms/validation/validators/isCountrySupported.ts
  src/test/app/forms/validation/validators/isCountrySupported.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3147

#3141 change for DAC
  src/main/common/components/payment-intention/payment-date.njk
  src/main/common/components/payment-intention/payment-plan.njk
  src/main/features/breathing-space/views/respite-end.njk
  src/main/features/breathing-space/views/respite-lifted.njk
  src/main/features/breathing-space/views/respite-start.njk
  src/main/features/ccj/views/date-of-birth.njk
  src/main/features/ccj/views/pay-by-set-date.njk
  src/main/features/ccj/views/repayment-plan.njk
  src/main/features/claim/views/claimant-dob.njk
  src/main/features/claim/views/interest-start-date.njk
  src/main/features/claimant-response/views/payment-plan.njk
  src/main/features/directions-questionnaire/views/expert-reports.njk
  src/main/features/directions-questionnaire/views/hearing-dates.njk
  src/main/features/offer/views/your-offer.njk
  src/main/features/paid-in-full/views/date-paid.njk
  src/main/features/response/views/evidence.njk
  src/main/features/response/views/full-rejection/how-much-have-you-paid.njk
  src/main/features/response/views/how-much-paid.njk
  src/main/features/response/views/partial-admission/how-much-have-you-paid.njk
  src/main/features/response/views/when-did-you-pay.njk
  src/main/features/response/views/your-dob.njk
  src/main/features/testing-support/views/update-response-deadline.njk
  src/main/views/macro/date.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3141

#3157 Post code lookup fix
  package.json
  src/main/app/postcode-lookup/clientFactory.ts
  src/main/app/postcode-lookup/postcodeToCountryClient.ts
  src/test/app/forms/validation/validators/isCountrySupported.ts
  src/test/app/postcode-lookup/postcodeToCountryClient.ts
  src/test/data/entity/mockCountryLookupResponse.ts
  src/test/data/entity/mockPostcodeLookupResponse.ts
  src/test/routes/postcode-lookup.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3157

#3161 cookie manager version upgrade to 3.0.2
  package.json
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3161

#3149 Update 'Hwf' with Help with fees on all relevant screens
  src/main/features/eligibility/views/apply-for-help-with-fees.njk
Labels: Prathap, help-with-fees, ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3149

#3165 Feature/ROC-9192-nightly-fix
  README.md
  bin/run-crossbrowser-tests.sh
  default.conf.js
  docker-compose.functional-tests.yml
  docker-compose.nightly-functional-tests.yml
  docker-compose.smoke-tests.yml
  package.json
  saucelabs.conf.js
  src/integration-test/tests/citizen/claimantResponse/part_admission_defendant_is_business_test.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3165
