Repository hmcts/cmc-citizen-frontend, pull requests merged in 2022-12, with the labels that each got.

#3465 CIV-446: Update content security policy
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
  src/main/modules/nunjucks/index.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3465

#3466 CIV-446: Update content security policy
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3466

#3468 CIV-4989: Update nodejs-healthcheck library version
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3468

#3459 Feat/civ 5560
  src/main/features/ccj/views/confirmation-ccj.njk
  src/main/features/dashboard/views/macro/claimStatus/ccjRequested.njk
  src/test/features/dashboard/routes/claimStatus/ccj.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3459

#3476 CIV-6379: Christmas Holidays Notification
  src/main/views/macro/support.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3476

#3478 udpate packages
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3478
