Repository hmcts/cmc-citizen-frontend, pull requests merged in 2022-07, with the labels that each got.

#3407 vulnerabilities supress
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3407

#3409 add logs for finish payment
  src/main/features/claim/routes/finish-payment.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3409

#3411 Update chart.yaml for node.js to 2.4.5
  charts/cmc-citizen-frontend/Chart.yaml
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3411

#3413 Add new ccd role for retain and dispose
  bin/add-roles.sh
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3413
