Repository hmcts/cmc-citizen-frontend, pull requests merged in 2022-03, with the labels that each got.

#3337 CIV-1507 : Suppress dependency vulnerabilities
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3337

#3336 Enable security scan & Fix fortify and dependency stages in nightly
  Dockerfile
  Jenkinsfile_nightly
  charts/cmc-citizen-frontend/Chart.yaml
  docker-compose.nightly-functional-tests.yml
  integration-tests.Dockerfile
  package-lock.json
  security.sh
  src/integration-test/tests/citizen/claim/helpWithFees_test.ts
  src/integration-test/tests/citizen/claim/steps/claim.ts
  types/steps-override.d.ts
  types/steps.d.ts
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3336

#3342 CIV-1507: Update yarn-audit-known-issues
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3342

#3343 Fix dependency check fix
  Dockerfile
  package.json
  src/integration-test/helpers/clients/idamClient.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3343

#3355 Fix pipeline
  Jenkinsfile_CNP
  bin/add-roles.sh
  bin/ccd-add-role.sh
  bin/ccd-import-definition.sh
  bin/idam-lease-service-token.sh
  bin/idam-lease-user-token.sh
  bin/import-ccd-definition.sh
  bin/pull-latest-ccd-defintion.sh
  bin/variables/load-preview-env-variables.sh
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/values.preview.template.yaml
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3355

#3349 CIV-1186 : added default reviewers
  .github/CODEOWNERS.md
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3349

#3334 CIV-1188 : added codeql analysis to git workflows
  .github/codeql/codeql-configuration.yml
  .github/workflows/codeql-analysis.yml
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3334
