Repository hmcts/cmc-citizen-frontend, pull requests merged in 2023-05, with the labels that each got.

#3537 CIV-7911: Remove validation if Address + Post Code is manually entered
  src/main/app/forms/models/address.ts
  src/main/app/forms/models/correspondenceAddress.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3537

#3566 CIV-446 update csp
  src/main/modules/helmet/modules/contentSecurityPolicy.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3566

#3578 CIV-8456 pipelines with node16
  .gitignore
  .mocharc.js
  .nvmrc
  Dockerfile
  README.md
  integration-tests.Dockerfile
  package-lock.json
  package.json
  src/integration-test/helpers/pcqHelper.js
  src/integration-test/tests/citizen/claim/steps/claim.ts
  src/main/applicationCluster.ts
  src/main/features/claim/helpers/taskListBuilder.ts
  src/main/features/claim/routes/task-list.ts
  src/test/app/claims/claimStoreClient.ts
  src/test/app/documents/scannedDocumentsClient.ts
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3578

#3567 Civ 446 gtm csp incorporated
  src/main/routes/google-tag-manager.ts
  src/main/views/govukTemplate.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3567

#3584 Update renovate config
  renovate.json
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3584
