Repository hmcts/cmc-citizen-frontend, pull requests merged in 2023-06, with the labels that each got.

#3587 Update ReadMe
  README.md
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3587

#3586 CIV-8596 Migrate to ESLint from TSLint
  .eslintignore
  .eslintrc.js
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3586

#3444 CIV-4987 Update error message with AddressInfoResponse issue
  src/main/routes/postcode-lookup.ts
  src/test/routes/postcode-lookup.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3444

#3591 CIV 8456 upgrade to 18
  .eslintrc.js
  Dockerfile
  README.md
  integration-tests.Dockerfile
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3591

#3560 CIV-7809: Update Contact Information for OCMC
  src/main/views/macro/paperFormAddress.njk
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3560

#3595 CIV-8457
  README.md
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3595

#3596 Upgrade Node to 18.16.0
  .nvmrc
  package.json
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3596

#3565 CIV-8369: Update the form urls to correct ones
  src/main/features/eligibility/views/not-eligible.njk
Labels: ns:money-claims, prd:cmc, enableHelm, rel:cmc-citizen-frontend-pr-3565
