Repository hmcts/cmc-citizen-frontend, pull requests merged in 2023-07, with the labels that each got.

#3601 CIV-9010 update cookie manager 3.0.3
  charts/cmc-citizen-frontend/Chart.yaml
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3601

#3605 Fix/master
  sonar-project.properties
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3605

#3608 CIV-9010 update cookie manager
  .gitignore
  .sass-lint.yml
  gulpfile.js
  package.json
  src/main/app/paths.ts
  src/main/common/components/cookie-manager/cookie-banner.njk
  src/main/common/components/cookie-manager/cookie-preferences.njk
  src/main/routes/cookie-banner.ts
  src/main/routes/cookie-preferences.ts
  src/main/views/cookies.njk
  src/main/views/govukTemplate.njk
  yarn.lock
Labels: ns:money-claims, prd:cmc, enableHelm, rel:cmc-citizen-frontend-pr-3608

#3562 CIV-8150: Update Claimant and Defendant Survey Link
  charts/cmc-citizen-frontend/Chart.yaml
  charts/cmc-citizen-frontend/values.yaml
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3562

#3597 Civ 5313 postcode validation
  src/main/app/forms/models/address.ts
  src/main/app/forms/models/correspondenceAddress.ts
  src/main/app/forms/validation/validationErrors.ts
  src/main/app/forms/validation/validators/postCodeNotInScotlandOrNI.ts
  src/main/public/js/postcode-lookup.js
  src/test/app/drafts/models/address.ts
  src/test/app/forms/validation/validators/PostcodeNotInScotlandOrNIValidator.ts
  src/test/data/draft/partyDetails.ts
  src/test/data/entity/party.ts
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3597
