Repository hmcts/cmc-citizen-frontend, pull requests merged in 2024-03, with the labels that each got.

#3654 CIV-11605 - TRACK NON-JAVASCRIPT VISITS IN GOOGLE ANALYTICS
  src/main/views/govukTemplate.njk
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, enable_keep_helm, rel:cmc-citizen-frontend-pr-3654

#3655 Yarn fix for CIV-11605 Jenkins master build issue.
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3655

#3653 CIV-12657 using frontend 4.8
  gulpfile.js
  package.json
  src/main/public/img/govuk-mask-icon-white.svg
  src/main/public/waf.html
  src/main/views/govukTemplate.njk
  src/main/views/macro/support.njk
  src/main/views/web-chat.njk
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3653
