Repository hmcts/cmc-citizen-frontend, pull requests merged in 2024-04, with the labels that each got.

#3663 DTSCCI-0000 Switch jq to yq
  .nvmrc
  bin/idam-lease-user-token.sh
  yarn-audit-known-issues
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3663

#3664 CIV-0000_DTSCCI-76: OCMC setup to run integration/functional tests on…
  integration-tests.Dockerfile
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3664

#3666 CIV-0000_fix-vulnerabilities: fixed vulnerabilities
  package.json
  yarn-audit-known-issues
  yarn.lock
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3666

#3668 DTSCCI-180: cmc-citizen-frontend nightly is failing on security scan
  Jenkinsfile_nightly
  security.sh
Labels: ns:money-claims, prd:cmc, rel:cmc-citizen-frontend-pr-3668
